// Revisioned feature proposals over existing annotation-pack evidence.
// This is an annotation document, NOT a VRLOG observation or display frame.
// Field numbers are permanent. Zero sample/point indices are valid; absent
// anchors stay absent. Legacy pack references do not claim retained IDs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: features.proto

package recordingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureGeometry int32

const (
	FeatureGeometry_FEATURE_GEOMETRY_UNKNOWN    FeatureGeometry = 0
	FeatureGeometry_FEATURE_GEOMETRY_EDGE       FeatureGeometry = 1
	FeatureGeometry_FEATURE_GEOMETRY_CORNER     FeatureGeometry = 2
	FeatureGeometry_FEATURE_GEOMETRY_PATCH      FeatureGeometry = 3
	FeatureGeometry_FEATURE_GEOMETRY_PROTRUSION FeatureGeometry = 4
)

// Enum value maps for FeatureGeometry.
var (
	FeatureGeometry_name = map[int32]string{
		0: "FEATURE_GEOMETRY_UNKNOWN",
		1: "FEATURE_GEOMETRY_EDGE",
		2: "FEATURE_GEOMETRY_CORNER",
		3: "FEATURE_GEOMETRY_PATCH",
		4: "FEATURE_GEOMETRY_PROTRUSION",
	}
	FeatureGeometry_value = map[string]int32{
		"FEATURE_GEOMETRY_UNKNOWN":    0,
		"FEATURE_GEOMETRY_EDGE":       1,
		"FEATURE_GEOMETRY_CORNER":     2,
		"FEATURE_GEOMETRY_PATCH":      3,
		"FEATURE_GEOMETRY_PROTRUSION": 4,
	}
)

func (x FeatureGeometry) Enum() *FeatureGeometry {
	p := new(FeatureGeometry)
	*p = x
	return p
}

func (x FeatureGeometry) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureGeometry) Descriptor() protoreflect.EnumDescriptor {
	return file_features_proto_enumTypes[0].Descriptor()
}

func (FeatureGeometry) Type() protoreflect.EnumType {
	return &file_features_proto_enumTypes[0]
}

func (x FeatureGeometry) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureGeometry.Descriptor instead.
func (FeatureGeometry) EnumDescriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

type FeatureDecision int32

const (
	FeatureDecision_FEATURE_DECISION_UNSPECIFIED FeatureDecision = 0
	// Accepted as an operator's feature proposal, never physical-reference truth.
	FeatureDecision_FEATURE_DECISION_ACCEPTED_PROPOSAL FeatureDecision = 1
	FeatureDecision_FEATURE_DECISION_REJECTED          FeatureDecision = 2
	FeatureDecision_FEATURE_DECISION_MISSING           FeatureDecision = 3
	FeatureDecision_FEATURE_DECISION_OCCLUDED          FeatureDecision = 4
)

// Enum value maps for FeatureDecision.
var (
	FeatureDecision_name = map[int32]string{
		0: "FEATURE_DECISION_UNSPECIFIED",
		1: "FEATURE_DECISION_ACCEPTED_PROPOSAL",
		2: "FEATURE_DECISION_REJECTED",
		3: "FEATURE_DECISION_MISSING",
		4: "FEATURE_DECISION_OCCLUDED",
	}
	FeatureDecision_value = map[string]int32{
		"FEATURE_DECISION_UNSPECIFIED":       0,
		"FEATURE_DECISION_ACCEPTED_PROPOSAL": 1,
		"FEATURE_DECISION_REJECTED":          2,
		"FEATURE_DECISION_MISSING":           3,
		"FEATURE_DECISION_OCCLUDED":          4,
	}
)

func (x FeatureDecision) Enum() *FeatureDecision {
	p := new(FeatureDecision)
	*p = x
	return p
}

func (x FeatureDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_features_proto_enumTypes[1].Descriptor()
}

func (FeatureDecision) Type() protoreflect.EnumType {
	return &file_features_proto_enumTypes[1]
}

func (x FeatureDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureDecision.Descriptor instead.
func (FeatureDecision) EnumDescriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

type FeatureSphere struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XM            float64                `protobuf:"fixed64,1,opt,name=x_m,json=xM,proto3" json:"x_m,omitempty"`
	YM            float64                `protobuf:"fixed64,2,opt,name=y_m,json=yM,proto3" json:"y_m,omitempty"`
	ZM            float64                `protobuf:"fixed64,3,opt,name=z_m,json=zM,proto3" json:"z_m,omitempty"`
	RadiusM       float64                `protobuf:"fixed64,4,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureSphere) Reset() {
	*x = FeatureSphere{}
	mi := &file_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSphere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSphere) ProtoMessage() {}

func (x *FeatureSphere) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSphere.ProtoReflect.Descriptor instead.
func (*FeatureSphere) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureSphere) GetXM() float64 {
	if x != nil {
		return x.XM
	}
	return 0
}

func (x *FeatureSphere) GetYM() float64 {
	if x != nil {
		return x.YM
	}
	return 0
}

func (x *FeatureSphere) GetZM() float64 {
	if x != nil {
		return x.ZM
	}
	return 0
}

func (x *FeatureSphere) GetRadiusM() float64 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

type FeatureObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleId      uint32                 `protobuf:"varint,1,opt,name=sample_id,json=sampleId,proto3" json:"sample_id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SourceOrdinal uint32                 `protobuf:"varint,3,opt,name=source_ordinal,json=sourceOrdinal,proto3" json:"source_ordinal,omitempty"`
	// Exact indices in this pack sample only. Different features may overlap.
	PointIndices       []uint32        `protobuf:"varint,4,rep,packed,name=point_indices,json=pointIndices,proto3" json:"point_indices,omitempty"`
	UncertainIndices   []uint32        `protobuf:"varint,5,rep,packed,name=uncertain_indices,json=uncertainIndices,proto3" json:"uncertain_indices,omitempty"`
	Sphere             *FeatureSphere  `protobuf:"bytes,6,opt,name=sphere,proto3" json:"sphere,omitempty"`
	Decision           FeatureDecision `protobuf:"varint,7,opt,name=decision,proto3,enum=velocity.recording.v1.FeatureDecision" json:"decision,omitempty"`
	Method             string          `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	Author             string          `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	MembershipRevision uint64          `protobuf:"varint,10,opt,name=membership_revision,json=membershipRevision,proto3" json:"membership_revision,omitempty"`
	MembershipDigest   string          `protobuf:"bytes,11,opt,name=membership_digest,json=membershipDigest,proto3" json:"membership_digest,omitempty"`
	ProposedFromSample *uint32         `protobuf:"varint,12,opt,name=proposed_from_sample,json=proposedFromSample,proto3,oneof" json:"proposed_from_sample,omitempty"`
	Note               string          `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`
	// Proposals never claim independent-reference provenance. Preserve whether
	// an algorithmic suggestion or prediction was visible to the operator.
	Origin        string `protobuf:"bytes,14,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureObservation) Reset() {
	*x = FeatureObservation{}
	mi := &file_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureObservation) ProtoMessage() {}

func (x *FeatureObservation) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureObservation.ProtoReflect.Descriptor instead.
func (*FeatureObservation) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureObservation) GetSampleId() uint32 {
	if x != nil {
		return x.SampleId
	}
	return 0
}

func (x *FeatureObservation) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *FeatureObservation) GetSourceOrdinal() uint32 {
	if x != nil {
		return x.SourceOrdinal
	}
	return 0
}

func (x *FeatureObservation) GetPointIndices() []uint32 {
	if x != nil {
		return x.PointIndices
	}
	return nil
}

func (x *FeatureObservation) GetUncertainIndices() []uint32 {
	if x != nil {
		return x.UncertainIndices
	}
	return nil
}

func (x *FeatureObservation) GetSphere() *FeatureSphere {
	if x != nil {
		return x.Sphere
	}
	return nil
}

func (x *FeatureObservation) GetDecision() FeatureDecision {
	if x != nil {
		return x.Decision
	}
	return FeatureDecision_FEATURE_DECISION_UNSPECIFIED
}

func (x *FeatureObservation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FeatureObservation) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FeatureObservation) GetMembershipRevision() uint64 {
	if x != nil {
		return x.MembershipRevision
	}
	return 0
}

func (x *FeatureObservation) GetMembershipDigest() string {
	if x != nil {
		return x.MembershipDigest
	}
	return ""
}

func (x *FeatureObservation) GetProposedFromSample() uint32 {
	if x != nil && x.ProposedFromSample != nil {
		return *x.ProposedFromSample
	}
	return 0
}

func (x *FeatureObservation) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *FeatureObservation) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type FeatureAnchor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable metric part frame, not a changing bounding-box origin.
	PartFrameId       string  `protobuf:"bytes,1,opt,name=part_frame_id,json=partFrameId,proto3" json:"part_frame_id,omitempty"`
	PartFrameRevision uint64  `protobuf:"varint,2,opt,name=part_frame_revision,json=partFrameRevision,proto3" json:"part_frame_revision,omitempty"`
	XM                float64 `protobuf:"fixed64,3,opt,name=x_m,json=xM,proto3" json:"x_m,omitempty"`
	YM                float64 `protobuf:"fixed64,4,opt,name=y_m,json=yM,proto3" json:"y_m,omitempty"`
	ZM                float64 `protobuf:"fixed64,5,opt,name=z_m,json=zM,proto3" json:"z_m,omitempty"`
	PhysicalRevision  uint64  `protobuf:"varint,6,opt,name=physical_revision,json=physicalRevision,proto3" json:"physical_revision,omitempty"`
	PhysicalDigest    string  `protobuf:"bytes,7,opt,name=physical_digest,json=physicalDigest,proto3" json:"physical_digest,omitempty"`
	BodyId            string  `protobuf:"bytes,8,opt,name=body_id,json=bodyId,proto3" json:"body_id,omitempty"`
	KeyframeId        string  `protobuf:"bytes,9,opt,name=keyframe_id,json=keyframeId,proto3" json:"keyframe_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeatureAnchor) Reset() {
	*x = FeatureAnchor{}
	mi := &file_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureAnchor) ProtoMessage() {}

func (x *FeatureAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureAnchor.ProtoReflect.Descriptor instead.
func (*FeatureAnchor) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureAnchor) GetPartFrameId() string {
	if x != nil {
		return x.PartFrameId
	}
	return ""
}

func (x *FeatureAnchor) GetPartFrameRevision() uint64 {
	if x != nil {
		return x.PartFrameRevision
	}
	return 0
}

func (x *FeatureAnchor) GetXM() float64 {
	if x != nil {
		return x.XM
	}
	return 0
}

func (x *FeatureAnchor) GetYM() float64 {
	if x != nil {
		return x.YM
	}
	return 0
}

func (x *FeatureAnchor) GetZM() float64 {
	if x != nil {
		return x.ZM
	}
	return 0
}

func (x *FeatureAnchor) GetPhysicalRevision() uint64 {
	if x != nil {
		return x.PhysicalRevision
	}
	return 0
}

func (x *FeatureAnchor) GetPhysicalDigest() string {
	if x != nil {
		return x.PhysicalDigest
	}
	return ""
}

func (x *FeatureAnchor) GetBodyId() string {
	if x != nil {
		return x.BodyId
	}
	return ""
}

func (x *FeatureAnchor) GetKeyframeId() string {
	if x != nil {
		return x.KeyframeId
	}
	return ""
}

type FeatureCandidate struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FeatureId    string                 `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	ObjectId     string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Geometry     FeatureGeometry        `protobuf:"varint,4,opt,name=geometry,proto3,enum=velocity.recording.v1.FeatureGeometry" json:"geometry,omitempty"`
	SemanticHint string                 `protobuf:"bytes,5,opt,name=semantic_hint,json=semanticHint,proto3" json:"semantic_hint,omitempty"`
	PartId       string                 `protobuf:"bytes,6,opt,name=part_id,json=partId,proto3" json:"part_id,omitempty"`
	// Pilot writes "unknown"; it does not assert a rigid/articulated transform.
	PartRelation string                `protobuf:"bytes,7,opt,name=part_relation,json=partRelation,proto3" json:"part_relation,omitempty"`
	Anchor       *FeatureAnchor        `protobuf:"bytes,8,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Observations []*FeatureObservation `protobuf:"bytes,9,rep,name=observations,proto3" json:"observations,omitempty"`
	// Keep historic evidence when a facet retires. Absent means active for v1.
	// At most four active facets per logical object; zero is valid abstention.
	Inactive      bool `protobuf:"varint,10,opt,name=inactive,proto3" json:"inactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureCandidate) Reset() {
	*x = FeatureCandidate{}
	mi := &file_features_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureCandidate) ProtoMessage() {}

func (x *FeatureCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureCandidate.ProtoReflect.Descriptor instead.
func (*FeatureCandidate) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{3}
}

func (x *FeatureCandidate) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *FeatureCandidate) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *FeatureCandidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureCandidate) GetGeometry() FeatureGeometry {
	if x != nil {
		return x.Geometry
	}
	return FeatureGeometry_FEATURE_GEOMETRY_UNKNOWN
}

func (x *FeatureCandidate) GetSemanticHint() string {
	if x != nil {
		return x.SemanticHint
	}
	return ""
}

func (x *FeatureCandidate) GetPartId() string {
	if x != nil {
		return x.PartId
	}
	return ""
}

func (x *FeatureCandidate) GetPartRelation() string {
	if x != nil {
		return x.PartRelation
	}
	return ""
}

func (x *FeatureCandidate) GetAnchor() *FeatureAnchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *FeatureCandidate) GetObservations() []*FeatureObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *FeatureCandidate) GetInactive() bool {
	if x != nil {
		return x.Inactive
	}
	return false
}

type FeatureAnnotations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact kind: velocity.report/feature-proposals. Never an observation stream.
	Schema        string              `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	SchemaVersion uint32              `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	PackDigest    string              `protobuf:"bytes,3,opt,name=pack_digest,json=packDigest,proto3" json:"pack_digest,omitempty"`
	DatasetId     string              `protobuf:"bytes,4,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Revision      uint64              `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	UpdatedUtc    string              `protobuf:"bytes,6,opt,name=updated_utc,json=updatedUtc,proto3" json:"updated_utc,omitempty"`
	Author        string              `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	Features      []*FeatureCandidate `protobuf:"bytes,8,rep,name=features,proto3" json:"features,omitempty"`
	// Pilot: legacy_pack. No synthetic mapping to 1.x retained point IDs.
	PointDomain   string `protobuf:"bytes,9,opt,name=point_domain,json=pointDomain,proto3" json:"point_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureAnnotations) Reset() {
	*x = FeatureAnnotations{}
	mi := &file_features_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureAnnotations) ProtoMessage() {}

func (x *FeatureAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureAnnotations.ProtoReflect.Descriptor instead.
func (*FeatureAnnotations) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureAnnotations) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *FeatureAnnotations) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *FeatureAnnotations) GetPackDigest() string {
	if x != nil {
		return x.PackDigest
	}
	return ""
}

func (x *FeatureAnnotations) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *FeatureAnnotations) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *FeatureAnnotations) GetUpdatedUtc() string {
	if x != nil {
		return x.UpdatedUtc
	}
	return ""
}

func (x *FeatureAnnotations) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FeatureAnnotations) GetFeatures() []*FeatureCandidate {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *FeatureAnnotations) GetPointDomain() string {
	if x != nil {
		return x.PointDomain
	}
	return ""
}

type FeatureState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Document         *FeatureAnnotations    `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Digest           string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	MembershipDigest string                 `protobuf:"bytes,3,opt,name=membership_digest,json=membershipDigest,proto3" json:"membership_digest,omitempty"`
	// Local writer identity: equal pack bytes in another folder are not this copy.
	PackDirectory string `protobuf:"bytes,4,opt,name=pack_directory,json=packDirectory,proto3" json:"pack_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureState) Reset() {
	*x = FeatureState{}
	mi := &file_features_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureState) ProtoMessage() {}

func (x *FeatureState) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureState.ProtoReflect.Descriptor instead.
func (*FeatureState) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{5}
}

func (x *FeatureState) GetDocument() *FeatureAnnotations {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *FeatureState) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *FeatureState) GetMembershipDigest() string {
	if x != nil {
		return x.MembershipDigest
	}
	return ""
}

func (x *FeatureState) GetPackDirectory() string {
	if x != nil {
		return x.PackDirectory
	}
	return ""
}

type FeatureEdit struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Document         *FeatureAnnotations    `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	BaseDigest       string                 `protobuf:"bytes,2,opt,name=base_digest,json=baseDigest,proto3" json:"base_digest,omitempty"`
	MembershipDigest string                 `protobuf:"bytes,3,opt,name=membership_digest,json=membershipDigest,proto3" json:"membership_digest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureEdit) Reset() {
	*x = FeatureEdit{}
	mi := &file_features_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureEdit) ProtoMessage() {}

func (x *FeatureEdit) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureEdit.ProtoReflect.Descriptor instead.
func (*FeatureEdit) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{6}
}

func (x *FeatureEdit) GetDocument() *FeatureAnnotations {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *FeatureEdit) GetBaseDigest() string {
	if x != nil {
		return x.BaseDigest
	}
	return ""
}

func (x *FeatureEdit) GetMembershipDigest() string {
	if x != nil {
		return x.MembershipDigest
	}
	return ""
}

var File_features_proto protoreflect.FileDescriptor

const file_features_proto_rawDesc = "" +
	"\n" +
	"\x0efeatures.proto\x12\x15velocity.recording.v1\"]\n" +
	"\rFeatureSphere\x12\x0f\n" +
	"\x03x_m\x18\x01 \x01(\x01R\x02xM\x12\x0f\n" +
	"\x03y_m\x18\x02 \x01(\x01R\x02yM\x12\x0f\n" +
	"\x03z_m\x18\x03 \x01(\x01R\x02zM\x12\x19\n" +
	"\bradius_m\x18\x04 \x01(\x01R\aradiusM\"\xe1\x04\n" +
	"\x12FeatureObservation\x12\x1b\n" +
	"\tsample_id\x18\x01 \x01(\rR\bsampleId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12%\n" +
	"\x0esource_ordinal\x18\x03 \x01(\rR\rsourceOrdinal\x12'\n" +
	"\rpoint_indices\x18\x04 \x03(\rB\x02\x10\x01R\fpointIndices\x12/\n" +
	"\x11uncertain_indices\x18\x05 \x03(\rB\x02\x10\x01R\x10uncertainIndices\x12<\n" +
	"\x06sphere\x18\x06 \x01(\v2$.velocity.recording.v1.FeatureSphereR\x06sphere\x12B\n" +
	"\bdecision\x18\a \x01(\x0e2&.velocity.recording.v1.FeatureDecisionR\bdecision\x12\x16\n" +
	"\x06method\x18\b \x01(\tR\x06method\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\x12/\n" +
	"\x13membership_revision\x18\n" +
	" \x01(\x04R\x12membershipRevision\x12+\n" +
	"\x11membership_digest\x18\v \x01(\tR\x10membershipDigest\x125\n" +
	"\x14proposed_from_sample\x18\f \x01(\rH\x00R\x12proposedFromSample\x88\x01\x01\x12\x12\n" +
	"\x04note\x18\r \x01(\tR\x04note\x12\x16\n" +
	"\x06origin\x18\x0e \x01(\tR\x06originB\x17\n" +
	"\x15_proposed_from_sample\"\xa6\x02\n" +
	"\rFeatureAnchor\x12\"\n" +
	"\rpart_frame_id\x18\x01 \x01(\tR\vpartFrameId\x12.\n" +
	"\x13part_frame_revision\x18\x02 \x01(\x04R\x11partFrameRevision\x12\x0f\n" +
	"\x03x_m\x18\x03 \x01(\x01R\x02xM\x12\x0f\n" +
	"\x03y_m\x18\x04 \x01(\x01R\x02yM\x12\x0f\n" +
	"\x03z_m\x18\x05 \x01(\x01R\x02zM\x12+\n" +
	"\x11physical_revision\x18\x06 \x01(\x04R\x10physicalRevision\x12'\n" +
	"\x0fphysical_digest\x18\a \x01(\tR\x0ephysicalDigest\x12\x17\n" +
	"\abody_id\x18\b \x01(\tR\x06bodyId\x12\x1f\n" +
	"\vkeyframe_id\x18\t \x01(\tR\n" +
	"keyframeId\"\xb2\x03\n" +
	"\x10FeatureCandidate\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x01 \x01(\tR\tfeatureId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12B\n" +
	"\bgeometry\x18\x04 \x01(\x0e2&.velocity.recording.v1.FeatureGeometryR\bgeometry\x12#\n" +
	"\rsemantic_hint\x18\x05 \x01(\tR\fsemanticHint\x12\x17\n" +
	"\apart_id\x18\x06 \x01(\tR\x06partId\x12#\n" +
	"\rpart_relation\x18\a \x01(\tR\fpartRelation\x12<\n" +
	"\x06anchor\x18\b \x01(\v2$.velocity.recording.v1.FeatureAnchorR\x06anchor\x12M\n" +
	"\fobservations\x18\t \x03(\v2).velocity.recording.v1.FeatureObservationR\fobservations\x12\x1a\n" +
	"\binactive\x18\n" +
	" \x01(\bR\binactive\"\xd0\x02\n" +
	"\x12FeatureAnnotations\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12\x1f\n" +
	"\vpack_digest\x18\x03 \x01(\tR\n" +
	"packDigest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x04 \x01(\tR\tdatasetId\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12\x1f\n" +
	"\vupdated_utc\x18\x06 \x01(\tR\n" +
	"updatedUtc\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12C\n" +
	"\bfeatures\x18\b \x03(\v2'.velocity.recording.v1.FeatureCandidateR\bfeatures\x12!\n" +
	"\fpoint_domain\x18\t \x01(\tR\vpointDomain\"\xc1\x01\n" +
	"\fFeatureState\x12E\n" +
	"\bdocument\x18\x01 \x01(\v2).velocity.recording.v1.FeatureAnnotationsR\bdocument\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12+\n" +
	"\x11membership_digest\x18\x03 \x01(\tR\x10membershipDigest\x12%\n" +
	"\x0epack_directory\x18\x04 \x01(\tR\rpackDirectory\"\xa2\x01\n" +
	"\vFeatureEdit\x12E\n" +
	"\bdocument\x18\x01 \x01(\v2).velocity.recording.v1.FeatureAnnotationsR\bdocument\x12\x1f\n" +
	"\vbase_digest\x18\x02 \x01(\tR\n" +
	"baseDigest\x12+\n" +
	"\x11membership_digest\x18\x03 \x01(\tR\x10membershipDigest*\xa4\x01\n" +
	"\x0fFeatureGeometry\x12\x1c\n" +
	"\x18FEATURE_GEOMETRY_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15FEATURE_GEOMETRY_EDGE\x10\x01\x12\x1b\n" +
	"\x17FEATURE_GEOMETRY_CORNER\x10\x02\x12\x1a\n" +
	"\x16FEATURE_GEOMETRY_PATCH\x10\x03\x12\x1f\n" +
	"\x1bFEATURE_GEOMETRY_PROTRUSION\x10\x04*\xb7\x01\n" +
	"\x0fFeatureDecision\x12 \n" +
	"\x1cFEATURE_DECISION_UNSPECIFIED\x10\x00\x12&\n" +
	"\"FEATURE_DECISION_ACCEPTED_PROPOSAL\x10\x01\x12\x1d\n" +
	"\x19FEATURE_DECISION_REJECTED\x10\x02\x12\x1c\n" +
	"\x18FEATURE_DECISION_MISSING\x10\x03\x12\x1d\n" +
	"\x19FEATURE_DECISION_OCCLUDED\x10\x04BDZBgithub.com/banshee-data/velocity.report/internal/lidar/recordingpbb\x06proto3"

var (
	file_features_proto_rawDescOnce sync.Once
	file_features_proto_rawDescData []byte
)

func file_features_proto_rawDescGZIP() []byte {
	file_features_proto_rawDescOnce.Do(func() {
		file_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)))
	})
	return file_features_proto_rawDescData
}

var file_features_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_features_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_features_proto_goTypes = []any{
	(FeatureGeometry)(0),       // 0: velocity.recording.v1.FeatureGeometry
	(FeatureDecision)(0),       // 1: velocity.recording.v1.FeatureDecision
	(*FeatureSphere)(nil),      // 2: velocity.recording.v1.FeatureSphere
	(*FeatureObservation)(nil), // 3: velocity.recording.v1.FeatureObservation
	(*FeatureAnchor)(nil),      // 4: velocity.recording.v1.FeatureAnchor
	(*FeatureCandidate)(nil),   // 5: velocity.recording.v1.FeatureCandidate
	(*FeatureAnnotations)(nil), // 6: velocity.recording.v1.FeatureAnnotations
	(*FeatureState)(nil),       // 7: velocity.recording.v1.FeatureState
	(*FeatureEdit)(nil),        // 8: velocity.recording.v1.FeatureEdit
}
var file_features_proto_depIdxs = []int32{
	2, // 0: velocity.recording.v1.FeatureObservation.sphere:type_name -> velocity.recording.v1.FeatureSphere
	1, // 1: velocity.recording.v1.FeatureObservation.decision:type_name -> velocity.recording.v1.FeatureDecision
	0, // 2: velocity.recording.v1.FeatureCandidate.geometry:type_name -> velocity.recording.v1.FeatureGeometry
	4, // 3: velocity.recording.v1.FeatureCandidate.anchor:type_name -> velocity.recording.v1.FeatureAnchor
	3, // 4: velocity.recording.v1.FeatureCandidate.observations:type_name -> velocity.recording.v1.FeatureObservation
	5, // 5: velocity.recording.v1.FeatureAnnotations.features:type_name -> velocity.recording.v1.FeatureCandidate
	6, // 6: velocity.recording.v1.FeatureState.document:type_name -> velocity.recording.v1.FeatureAnnotations
	6, // 7: velocity.recording.v1.FeatureEdit.document:type_name -> velocity.recording.v1.FeatureAnnotations
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_features_proto_init() }
func file_features_proto_init() {
	if File_features_proto != nil {
		return
	}
	file_features_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_features_proto_goTypes,
		DependencyIndexes: file_features_proto_depIdxs,
		EnumInfos:         file_features_proto_enumTypes,
		MessageInfos:      file_features_proto_msgTypes,
	}.Build()
	File_features_proto = out.File
	file_features_proto_goTypes = nil
	file_features_proto_depIdxs = nil
}
