// velocity.report recording domain
// Version: v1
// Package: velocity.recording.v1
//
// Typed payloads for VRLOG 1.x containers: the capture manifest, the L4
// observation frame and gap records, and the chunk header, seal, index and
// closing-summary objects. The container's fixed-binary record envelope,
// object preambles and record kinds are specified in
// data/structures/VRLOG_FORMAT.md, not here: the envelope is deliberately
// independent of this package so a reader can reject a file before it
// trusts any protobuf.
//
// This schema is independent of velocity.visualiser.v1. A FrameBundle is a
// display projection; nothing here may be derived from it, and a
// FrameBundle may be derived from this but never stored in its place.
//
// Evolution rules. They exist because protobuf accepts a different message
// whose field numbers overlap, so a version string alone cannot protect a
// reader:
//   - Field and enum numbers are never reused. A retired field's number and
//     name are reserved in its message, with the reason.
//   - A new field is a minor change only if a reader that ignores it still
//     reads every existing field correctly. A field that changes the meaning
//     of another must also add a manifest required feature, which older
//     readers refuse.
//   - Enum values equal the l4bobserve constants they carry; a reader
//     rejects values it does not know rather than mapping them to a default.
//   - Scalars whose zero is valid data (ring 0, intensity 0, a count of 0)
//     carry explicit presence: `optional`, a presence bit set, or a
//     sub-message. Absent never means zero.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: recording.proto

package recordingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaVersion names the revision of this file's message definitions that
// a container's records use. A reader refuses a version it does not know.
type SchemaVersion int32

const (
	SchemaVersion_SCHEMA_VERSION_UNSPECIFIED SchemaVersion = 0
	SchemaVersion_SCHEMA_VERSION_1           SchemaVersion = 1
)

// Enum value maps for SchemaVersion.
var (
	SchemaVersion_name = map[int32]string{
		0: "SCHEMA_VERSION_UNSPECIFIED",
		1: "SCHEMA_VERSION_1",
	}
	SchemaVersion_value = map[string]int32{
		"SCHEMA_VERSION_UNSPECIFIED": 0,
		"SCHEMA_VERSION_1":           1,
	}
)

func (x SchemaVersion) Enum() *SchemaVersion {
	p := new(SchemaVersion)
	*p = x
	return p
}

func (x SchemaVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[0].Descriptor()
}

func (SchemaVersion) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[0]
}

func (x SchemaVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaVersion.Descriptor instead.
func (SchemaVersion) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{0}
}

// StreamKind says what a container's records are. A full capture is an
// observation stream; analysis runs and portable selections are planned
// kinds that reference committed observations without claiming to be one.
type StreamKind int32

const (
	StreamKind_STREAM_KIND_UNSPECIFIED StreamKind = 0
	StreamKind_STREAM_KIND_OBSERVATION StreamKind = 1
)

// Enum value maps for StreamKind.
var (
	StreamKind_name = map[int32]string{
		0: "STREAM_KIND_UNSPECIFIED",
		1: "STREAM_KIND_OBSERVATION",
	}
	StreamKind_value = map[string]int32{
		"STREAM_KIND_UNSPECIFIED": 0,
		"STREAM_KIND_OBSERVATION": 1,
	}
)

func (x StreamKind) Enum() *StreamKind {
	p := new(StreamKind)
	*p = x
	return p
}

func (x StreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[1].Descriptor()
}

func (StreamKind) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[1]
}

func (x StreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamKind.Descriptor instead.
func (StreamKind) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{1}
}

type Completeness int32

const (
	Completeness_COMPLETENESS_UNKNOWN  Completeness = 0
	Completeness_COMPLETENESS_COMPLETE Completeness = 1
	Completeness_COMPLETENESS_PARTIAL  Completeness = 2
)

// Enum value maps for Completeness.
var (
	Completeness_name = map[int32]string{
		0: "COMPLETENESS_UNKNOWN",
		1: "COMPLETENESS_COMPLETE",
		2: "COMPLETENESS_PARTIAL",
	}
	Completeness_value = map[string]int32{
		"COMPLETENESS_UNKNOWN":  0,
		"COMPLETENESS_COMPLETE": 1,
		"COMPLETENESS_PARTIAL":  2,
	}
)

func (x Completeness) Enum() *Completeness {
	p := new(Completeness)
	*p = x
	return p
}

func (x Completeness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Completeness) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[2].Descriptor()
}

func (Completeness) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[2]
}

func (x Completeness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Completeness.Descriptor instead.
func (Completeness) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{2}
}

type BackgroundState int32

const (
	BackgroundState_BACKGROUND_STATE_UNKNOWN  BackgroundState = 0
	BackgroundState_BACKGROUND_STATE_SETTLING BackgroundState = 1
	BackgroundState_BACKGROUND_STATE_SETTLED  BackgroundState = 2
)

// Enum value maps for BackgroundState.
var (
	BackgroundState_name = map[int32]string{
		0: "BACKGROUND_STATE_UNKNOWN",
		1: "BACKGROUND_STATE_SETTLING",
		2: "BACKGROUND_STATE_SETTLED",
	}
	BackgroundState_value = map[string]int32{
		"BACKGROUND_STATE_UNKNOWN":  0,
		"BACKGROUND_STATE_SETTLING": 1,
		"BACKGROUND_STATE_SETTLED":  2,
	}
)

func (x BackgroundState) Enum() *BackgroundState {
	p := new(BackgroundState)
	*p = x
	return p
}

func (x BackgroundState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackgroundState) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[3].Descriptor()
}

func (BackgroundState) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[3]
}

func (x BackgroundState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackgroundState.Descriptor instead.
func (BackgroundState) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{3}
}

type Disposition int32

const (
	Disposition_DISPOSITION_UNSPECIFIED Disposition = 0
	Disposition_DISPOSITION_OBSERVED    Disposition = 1
	Disposition_DISPOSITION_UNSETTLED   Disposition = 2
	Disposition_DISPOSITION_SUPPRESSED  Disposition = 3
	Disposition_DISPOSITION_FAILED      Disposition = 4
)

// Enum value maps for Disposition.
var (
	Disposition_name = map[int32]string{
		0: "DISPOSITION_UNSPECIFIED",
		1: "DISPOSITION_OBSERVED",
		2: "DISPOSITION_UNSETTLED",
		3: "DISPOSITION_SUPPRESSED",
		4: "DISPOSITION_FAILED",
	}
	Disposition_value = map[string]int32{
		"DISPOSITION_UNSPECIFIED": 0,
		"DISPOSITION_OBSERVED":    1,
		"DISPOSITION_UNSETTLED":   2,
		"DISPOSITION_SUPPRESSED":  3,
		"DISPOSITION_FAILED":      4,
	}
)

func (x Disposition) Enum() *Disposition {
	p := new(Disposition)
	*p = x
	return p
}

func (x Disposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Disposition) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[4].Descriptor()
}

func (Disposition) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[4]
}

func (x Disposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Disposition.Descriptor instead.
func (Disposition) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{4}
}

// Bits of RetainedPoints.columns. A column is present when its bit is set,
// even for an empty domain; its values are then exactly point_count long.
type PointColumn int32

const (
	PointColumn_POINT_COLUMN_UNSPECIFIED      PointColumn = 0
	PointColumn_POINT_COLUMN_ACQUISITION_TIME PointColumn = 1
	PointColumn_POINT_COLUMN_INTENSITY        PointColumn = 2
	PointColumn_POINT_COLUMN_CHANNEL          PointColumn = 4
	PointColumn_POINT_COLUMN_RETURN_INDEX     PointColumn = 8
	PointColumn_POINT_COLUMN_SOURCE_ORDINAL   PointColumn = 16
	PointColumn_POINT_COLUMN_PACKET_SEQUENCE  PointColumn = 32
	PointColumn_POINT_COLUMN_BLOCK_INDEX      PointColumn = 64
)

// Enum value maps for PointColumn.
var (
	PointColumn_name = map[int32]string{
		0:  "POINT_COLUMN_UNSPECIFIED",
		1:  "POINT_COLUMN_ACQUISITION_TIME",
		2:  "POINT_COLUMN_INTENSITY",
		4:  "POINT_COLUMN_CHANNEL",
		8:  "POINT_COLUMN_RETURN_INDEX",
		16: "POINT_COLUMN_SOURCE_ORDINAL",
		32: "POINT_COLUMN_PACKET_SEQUENCE",
		64: "POINT_COLUMN_BLOCK_INDEX",
	}
	PointColumn_value = map[string]int32{
		"POINT_COLUMN_UNSPECIFIED":      0,
		"POINT_COLUMN_ACQUISITION_TIME": 1,
		"POINT_COLUMN_INTENSITY":        2,
		"POINT_COLUMN_CHANNEL":          4,
		"POINT_COLUMN_RETURN_INDEX":     8,
		"POINT_COLUMN_SOURCE_ORDINAL":   16,
		"POINT_COLUMN_PACKET_SEQUENCE":  32,
		"POINT_COLUMN_BLOCK_INDEX":      64,
	}
)

func (x PointColumn) Enum() *PointColumn {
	p := new(PointColumn)
	*p = x
	return p
}

func (x PointColumn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointColumn) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[5].Descriptor()
}

func (PointColumn) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[5]
}

func (x PointColumn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointColumn.Descriptor instead.
func (PointColumn) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{5}
}

// RejectionReason values are the bytes of Membership.unassigned_reasons.
type RejectionReason int32

const (
	RejectionReason_REJECTION_REASON_UNKNOWN               RejectionReason = 0
	RejectionReason_REJECTION_REASON_HEIGHT_BAND           RejectionReason = 1
	RejectionReason_REJECTION_REASON_SURFACE_BELOW_FLOOR   RejectionReason = 2
	RejectionReason_REJECTION_REASON_SURFACE_ABOVE_CEILING RejectionReason = 3
	RejectionReason_REJECTION_REASON_VOXEL_REDUCED         RejectionReason = 4
	RejectionReason_REJECTION_REASON_CLUSTER_INPUT_CAP     RejectionReason = 5
	RejectionReason_REJECTION_REASON_CLUSTER_NOISE         RejectionReason = 6
	RejectionReason_REJECTION_REASON_CLUSTER_SHAPE         RejectionReason = 7
)

// Enum value maps for RejectionReason.
var (
	RejectionReason_name = map[int32]string{
		0: "REJECTION_REASON_UNKNOWN",
		1: "REJECTION_REASON_HEIGHT_BAND",
		2: "REJECTION_REASON_SURFACE_BELOW_FLOOR",
		3: "REJECTION_REASON_SURFACE_ABOVE_CEILING",
		4: "REJECTION_REASON_VOXEL_REDUCED",
		5: "REJECTION_REASON_CLUSTER_INPUT_CAP",
		6: "REJECTION_REASON_CLUSTER_NOISE",
		7: "REJECTION_REASON_CLUSTER_SHAPE",
	}
	RejectionReason_value = map[string]int32{
		"REJECTION_REASON_UNKNOWN":               0,
		"REJECTION_REASON_HEIGHT_BAND":           1,
		"REJECTION_REASON_SURFACE_BELOW_FLOOR":   2,
		"REJECTION_REASON_SURFACE_ABOVE_CEILING": 3,
		"REJECTION_REASON_VOXEL_REDUCED":         4,
		"REJECTION_REASON_CLUSTER_INPUT_CAP":     5,
		"REJECTION_REASON_CLUSTER_NOISE":         6,
		"REJECTION_REASON_CLUSTER_SHAPE":         7,
	}
)

func (x RejectionReason) Enum() *RejectionReason {
	p := new(RejectionReason)
	*p = x
	return p
}

func (x RejectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[6].Descriptor()
}

func (RejectionReason) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[6]
}

func (x RejectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectionReason.Descriptor instead.
func (RejectionReason) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{6}
}

type GapTime int32

const (
	GapTime_GAP_TIME_UNKNOWN GapTime = 0
	GapTime_GAP_TIME_BOUNDED GapTime = 1
)

// Enum value maps for GapTime.
var (
	GapTime_name = map[int32]string{
		0: "GAP_TIME_UNKNOWN",
		1: "GAP_TIME_BOUNDED",
	}
	GapTime_value = map[string]int32{
		"GAP_TIME_UNKNOWN": 0,
		"GAP_TIME_BOUNDED": 1,
	}
)

func (x GapTime) Enum() *GapTime {
	p := new(GapTime)
	*p = x
	return p
}

func (x GapTime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GapTime) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_proto_enumTypes[7].Descriptor()
}

func (GapTime) Type() protoreflect.EnumType {
	return &file_recording_proto_enumTypes[7]
}

func (x GapTime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GapTime.Descriptor instead.
func (GapTime) EnumDescriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{7}
}

// RecordingManifest is the container's immutable root: written once, before
// any record is admitted, and never rewritten.
type RecordingManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion SchemaVersion          `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,enum=velocity.recording.v1.SchemaVersion" json:"schema_version,omitempty"`
	StreamKind    StreamKind             `protobuf:"varint,2,opt,name=stream_kind,json=streamKind,proto3,enum=velocity.recording.v1.StreamKind" json:"stream_kind,omitempty"`
	// Evidence profile (l4bobserve.ProfileName) and its capabilities, sorted.
	// Both are stored so a reader in another language needs no Go mapping; a
	// Go reader refuses a known profile whose list disagrees with its
	// declaration.
	Profile      string   `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Format features a reader must understand to read the records correctly.
	// A reader refuses any it does not know. Empty in container 1.0.
	RequiredFeatures []string `protobuf:"bytes,5,rep,name=required_features,json=requiredFeatures,proto3" json:"required_features,omitempty"`
	// Version of the semantic digest recorded in chunk seals
	// (l4bobserve.SemanticDigestVersion).
	SemanticDigestVersion string              `protobuf:"bytes,6,opt,name=semantic_digest_version,json=semanticDigestVersion,proto3" json:"semantic_digest_version,omitempty"`
	Capture               *CaptureIdentity    `protobuf:"bytes,7,opt,name=capture,proto3" json:"capture,omitempty"`
	Extraction            *ExtractionIdentity `protobuf:"bytes,8,opt,name=extraction,proto3" json:"extraction,omitempty"`
	Calibration           *Calibration        `protobuf:"bytes,9,opt,name=calibration,proto3" json:"calibration,omitempty"`
	Limits                *Limits             `protobuf:"bytes,10,opt,name=limits,proto3" json:"limits,omitempty"`
	Provenance            *Provenance         `protobuf:"bytes,11,opt,name=provenance,proto3" json:"provenance,omitempty"`
	// Metadata objects embedded by value, each with its SHA-256, so the
	// manifest reproduces its configuration without an external path.
	Metadata      []*MetadataObject `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingManifest) Reset() {
	*x = RecordingManifest{}
	mi := &file_recording_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingManifest) ProtoMessage() {}

func (x *RecordingManifest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingManifest.ProtoReflect.Descriptor instead.
func (*RecordingManifest) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{0}
}

func (x *RecordingManifest) GetSchemaVersion() SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return SchemaVersion_SCHEMA_VERSION_UNSPECIFIED
}

func (x *RecordingManifest) GetStreamKind() StreamKind {
	if x != nil {
		return x.StreamKind
	}
	return StreamKind_STREAM_KIND_UNSPECIFIED
}

func (x *RecordingManifest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *RecordingManifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RecordingManifest) GetRequiredFeatures() []string {
	if x != nil {
		return x.RequiredFeatures
	}
	return nil
}

func (x *RecordingManifest) GetSemanticDigestVersion() string {
	if x != nil {
		return x.SemanticDigestVersion
	}
	return ""
}

func (x *RecordingManifest) GetCapture() *CaptureIdentity {
	if x != nil {
		return x.Capture
	}
	return nil
}

func (x *RecordingManifest) GetExtraction() *ExtractionIdentity {
	if x != nil {
		return x.Extraction
	}
	return nil
}

func (x *RecordingManifest) GetCalibration() *Calibration {
	if x != nil {
		return x.Calibration
	}
	return nil
}

func (x *RecordingManifest) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *RecordingManifest) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *RecordingManifest) GetMetadata() []*MetadataObject {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CaptureIdentity names one capture. The UUID is random and allocated before
// ingestion: two replays of the same PCAP are two captures, and the UUID and
// creation time are the only fields that legitimately differ between them.
type CaptureIdentity struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CaptureUuid string                 `protobuf:"bytes,1,opt,name=capture_uuid,json=captureUuid,proto3" json:"capture_uuid,omitempty"`
	SensorId    string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	// "pcap", "live" or "synthetic".
	SourceType string `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Set when this capture is derived from another (a salvage or selection).
	ParentCaptureUuid string `protobuf:"bytes,4,opt,name=parent_capture_uuid,json=parentCaptureUuid,proto3" json:"parent_capture_uuid,omitempty"`
	CreatedUnixNanos  int64  `protobuf:"fixed64,5,opt,name=created_unix_nanos,json=createdUnixNanos,proto3" json:"created_unix_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CaptureIdentity) Reset() {
	*x = CaptureIdentity{}
	mi := &file_recording_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureIdentity) ProtoMessage() {}

func (x *CaptureIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureIdentity.ProtoReflect.Descriptor instead.
func (*CaptureIdentity) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{1}
}

func (x *CaptureIdentity) GetCaptureUuid() string {
	if x != nil {
		return x.CaptureUuid
	}
	return ""
}

func (x *CaptureIdentity) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *CaptureIdentity) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CaptureIdentity) GetParentCaptureUuid() string {
	if x != nil {
		return x.ParentCaptureUuid
	}
	return ""
}

func (x *CaptureIdentity) GetCreatedUnixNanos() int64 {
	if x != nil {
		return x.CreatedUnixNanos
	}
	return 0
}

// ExtractionIdentity binds the records to the ordered source and the
// extractor that produced them. source_id and calibration_id are the
// l4bobserve identities; a reader recomputes both from the fields beside them.
type ExtractionIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CalibrationId string                 `protobuf:"bytes,2,opt,name=calibration_id,json=calibrationId,proto3" json:"calibration_id,omitempty"`
	// Frame of the retained XYZ, e.g. "site/<sensor>".
	CoordinateFrame string `protobuf:"bytes,3,opt,name=coordinate_frame,json=coordinateFrame,proto3" json:"coordinate_frame,omitempty"`
	ReplayCaseId    string `protobuf:"bytes,4,opt,name=replay_case_id,json=replayCaseId,proto3" json:"replay_case_id,omitempty"`
	// Ordered capture files exactly as they entered source_id.
	CaptureFiles []*CaptureFile `protobuf:"bytes,5,rep,name=capture_files,json=captureFiles,proto3" json:"capture_files,omitempty"`
	ExtractorId  string         `protobuf:"bytes,6,opt,name=extractor_id,json=extractorId,proto3" json:"extractor_id,omitempty"`
	// Replay window as configured, relative to the capture sequence's first
	// packet. Zero duration means the remainder of the capture.
	Window        *SourceWindow `protobuf:"bytes,7,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractionIdentity) Reset() {
	*x = ExtractionIdentity{}
	mi := &file_recording_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractionIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractionIdentity) ProtoMessage() {}

func (x *ExtractionIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractionIdentity.ProtoReflect.Descriptor instead.
func (*ExtractionIdentity) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractionIdentity) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ExtractionIdentity) GetCalibrationId() string {
	if x != nil {
		return x.CalibrationId
	}
	return ""
}

func (x *ExtractionIdentity) GetCoordinateFrame() string {
	if x != nil {
		return x.CoordinateFrame
	}
	return ""
}

func (x *ExtractionIdentity) GetReplayCaseId() string {
	if x != nil {
		return x.ReplayCaseId
	}
	return ""
}

func (x *ExtractionIdentity) GetCaptureFiles() []*CaptureFile {
	if x != nil {
		return x.CaptureFiles
	}
	return nil
}

func (x *ExtractionIdentity) GetExtractorId() string {
	if x != nil {
		return x.ExtractorId
	}
	return ""
}

func (x *ExtractionIdentity) GetWindow() *SourceWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

type CaptureFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Lower-case hex SHA-256 of the file's bytes.
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureFile) Reset() {
	*x = CaptureFile{}
	mi := &file_recording_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureFile) ProtoMessage() {}

func (x *CaptureFile) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureFile.ProtoReflect.Descriptor instead.
func (*CaptureFile) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CaptureFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type SourceWindow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartOffsetNanos int64                  `protobuf:"fixed64,1,opt,name=start_offset_nanos,json=startOffsetNanos,proto3" json:"start_offset_nanos,omitempty"`
	WarmupNanos      int64                  `protobuf:"fixed64,2,opt,name=warmup_nanos,json=warmupNanos,proto3" json:"warmup_nanos,omitempty"`
	DurationNanos    int64                  `protobuf:"fixed64,3,opt,name=duration_nanos,json=durationNanos,proto3" json:"duration_nanos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SourceWindow) Reset() {
	*x = SourceWindow{}
	mi := &file_recording_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceWindow) ProtoMessage() {}

func (x *SourceWindow) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceWindow.ProtoReflect.Descriptor instead.
func (*SourceWindow) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{4}
}

func (x *SourceWindow) GetStartOffsetNanos() int64 {
	if x != nil {
		return x.StartOffsetNanos
	}
	return 0
}

func (x *SourceWindow) GetWarmupNanos() int64 {
	if x != nil {
		return x.WarmupNanos
	}
	return 0
}

func (x *SourceWindow) GetDurationNanos() int64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

// Calibration is the transform that placed sensor points in the coordinate
// frame, embedded so the geometry is reproducible without a database row.
type Calibration struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SensorId  string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	FromFrame string                 `protobuf:"bytes,2,opt,name=from_frame,json=fromFrame,proto3" json:"from_frame,omitempty"`
	ToFrame   string                 `protobuf:"bytes,3,opt,name=to_frame,json=toFrame,proto3" json:"to_frame,omitempty"`
	// Row-major 4x4; exactly 16 values.
	Transform     []float64 `protobuf:"fixed64,4,rep,packed,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calibration) Reset() {
	*x = Calibration{}
	mi := &file_recording_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calibration) ProtoMessage() {}

func (x *Calibration) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calibration.ProtoReflect.Descriptor instead.
func (*Calibration) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{5}
}

func (x *Calibration) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Calibration) GetFromFrame() string {
	if x != nil {
		return x.FromFrame
	}
	return ""
}

func (x *Calibration) GetToFrame() string {
	if x != nil {
		return x.ToFrame
	}
	return ""
}

func (x *Calibration) GetTransform() []float64 {
	if x != nil {
		return x.Transform
	}
	return nil
}

// Limits a writer promises and a reader enforces before allocating. A
// reader also refuses limits above its own hard ceilings.
type Limits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TargetChunkBytes    uint64                 `protobuf:"varint,1,opt,name=target_chunk_bytes,json=targetChunkBytes,proto3" json:"target_chunk_bytes,omitempty"`
	MaxChunkBytes       uint64                 `protobuf:"varint,2,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"`
	MaxRecordBytes      uint32                 `protobuf:"varint,3,opt,name=max_record_bytes,json=maxRecordBytes,proto3" json:"max_record_bytes,omitempty"`
	MaxRecordsPerChunk  uint32                 `protobuf:"varint,4,opt,name=max_records_per_chunk,json=maxRecordsPerChunk,proto3" json:"max_records_per_chunk,omitempty"`
	MaxPointsPerFrame   uint32                 `protobuf:"varint,5,opt,name=max_points_per_frame,json=maxPointsPerFrame,proto3" json:"max_points_per_frame,omitempty"`
	MaxClustersPerFrame uint32                 `protobuf:"varint,6,opt,name=max_clusters_per_frame,json=maxClustersPerFrame,proto3" json:"max_clusters_per_frame,omitempty"`
	MaxStagesPerFrame   uint32                 `protobuf:"varint,7,opt,name=max_stages_per_frame,json=maxStagesPerFrame,proto3" json:"max_stages_per_frame,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_recording_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{6}
}

func (x *Limits) GetTargetChunkBytes() uint64 {
	if x != nil {
		return x.TargetChunkBytes
	}
	return 0
}

func (x *Limits) GetMaxChunkBytes() uint64 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

func (x *Limits) GetMaxRecordBytes() uint32 {
	if x != nil {
		return x.MaxRecordBytes
	}
	return 0
}

func (x *Limits) GetMaxRecordsPerChunk() uint32 {
	if x != nil {
		return x.MaxRecordsPerChunk
	}
	return 0
}

func (x *Limits) GetMaxPointsPerFrame() uint32 {
	if x != nil {
		return x.MaxPointsPerFrame
	}
	return 0
}

func (x *Limits) GetMaxClustersPerFrame() uint32 {
	if x != nil {
		return x.MaxClustersPerFrame
	}
	return 0
}

func (x *Limits) GetMaxStagesPerFrame() uint32 {
	if x != nil {
		return x.MaxStagesPerFrame
	}
	return 0
}

// Provenance identifies the software and configuration that wrote the
// container. params_hash is the same identity the legacy VRLOG header and
// replay manifest carry for the effective tuning.
type Provenance struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BuildVersion string                 `protobuf:"bytes,1,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	BuildGitSha  string                 `protobuf:"bytes,2,opt,name=build_git_sha,json=buildGitSha,proto3" json:"build_git_sha,omitempty"`
	// Component that wrote the container, e.g. "replayeval".
	Writer              string   `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer,omitempty"`
	ParamsHash          string   `protobuf:"bytes,4,opt,name=params_hash,json=paramsHash,proto3" json:"params_hash,omitempty"`
	ParamsSchemaVersion string   `protobuf:"bytes,5,opt,name=params_schema_version,json=paramsSchemaVersion,proto3" json:"params_schema_version,omitempty"`
	Experiments         []string `protobuf:"bytes,6,rep,name=experiments,proto3" json:"experiments,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_recording_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{7}
}

func (x *Provenance) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *Provenance) GetBuildGitSha() string {
	if x != nil {
		return x.BuildGitSha
	}
	return ""
}

func (x *Provenance) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *Provenance) GetParamsHash() string {
	if x != nil {
		return x.ParamsHash
	}
	return ""
}

func (x *Provenance) GetParamsSchemaVersion() string {
	if x != nil {
		return x.ParamsSchemaVersion
	}
	return ""
}

func (x *Provenance) GetExperiments() []string {
	if x != nil {
		return x.Experiments
	}
	return nil
}

type MetadataObject struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MediaType string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Content   []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Lower-case hex SHA-256 of content.
	Sha256        string `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataObject) Reset() {
	*x = MetadataObject{}
	mi := &file_recording_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataObject) ProtoMessage() {}

func (x *MetadataObject) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataObject.ProtoReflect.Descriptor instead.
func (*MetadataObject) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{8}
}

func (x *MetadataObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataObject) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MetadataObject) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MetadataObject) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// FrameRecord is one l4bobserve.FrameRecord: the evidence for one frame the
// extractor received, in source sequence.
type FrameRecord struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Sequence              uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SensorFrameId         string                 `protobuf:"bytes,2,opt,name=sensor_frame_id,json=sensorFrameId,proto3" json:"sensor_frame_id,omitempty"`
	FrameUnixNanos        int64                  `protobuf:"fixed64,3,opt,name=frame_unix_nanos,json=frameUnixNanos,proto3" json:"frame_unix_nanos,omitempty"`
	CaptureStartUnixNanos int64                  `protobuf:"fixed64,4,opt,name=capture_start_unix_nanos,json=captureStartUnixNanos,proto3" json:"capture_start_unix_nanos,omitempty"`
	CaptureEndUnixNanos   int64                  `protobuf:"fixed64,5,opt,name=capture_end_unix_nanos,json=captureEndUnixNanos,proto3" json:"capture_end_unix_nanos,omitempty"`
	Completeness          Completeness           `protobuf:"varint,6,opt,name=completeness,proto3,enum=velocity.recording.v1.Completeness" json:"completeness,omitempty"`
	// Absent: the loss is unknown, which is not a loss of zero.
	LostPackets *uint64         `protobuf:"varint,7,opt,name=lost_packets,json=lostPackets,proto3,oneof" json:"lost_packets,omitempty"`
	Background  BackgroundState `protobuf:"varint,8,opt,name=background,proto3,enum=velocity.recording.v1.BackgroundState" json:"background,omitempty"`
	Disposition Disposition     `protobuf:"varint,9,opt,name=disposition,proto3,enum=velocity.recording.v1.Disposition" json:"disposition,omitempty"`
	// Required for suppressed and failed frames, empty otherwise.
	DispositionStage  string `protobuf:"bytes,10,opt,name=disposition_stage,json=dispositionStage,proto3" json:"disposition_stage,omitempty"`
	DispositionReason string `protobuf:"bytes,11,opt,name=disposition_reason,json=dispositionReason,proto3" json:"disposition_reason,omitempty"`
	// In the order the pipeline reported them.
	Stages []*StageCount `protobuf:"bytes,12,rep,name=stages,proto3" json:"stages,omitempty"`
	// Presence is payload availability: points present means the retained
	// domain is recorded (possibly empty); membership present means clusters
	// and unassigned points partition it.
	Points        *RetainedPoints `protobuf:"bytes,13,opt,name=points,proto3" json:"points,omitempty"`
	Membership    *Membership     `protobuf:"bytes,14,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRecord) Reset() {
	*x = FrameRecord{}
	mi := &file_recording_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRecord) ProtoMessage() {}

func (x *FrameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRecord.ProtoReflect.Descriptor instead.
func (*FrameRecord) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{9}
}

func (x *FrameRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FrameRecord) GetSensorFrameId() string {
	if x != nil {
		return x.SensorFrameId
	}
	return ""
}

func (x *FrameRecord) GetFrameUnixNanos() int64 {
	if x != nil {
		return x.FrameUnixNanos
	}
	return 0
}

func (x *FrameRecord) GetCaptureStartUnixNanos() int64 {
	if x != nil {
		return x.CaptureStartUnixNanos
	}
	return 0
}

func (x *FrameRecord) GetCaptureEndUnixNanos() int64 {
	if x != nil {
		return x.CaptureEndUnixNanos
	}
	return 0
}

func (x *FrameRecord) GetCompleteness() Completeness {
	if x != nil {
		return x.Completeness
	}
	return Completeness_COMPLETENESS_UNKNOWN
}

func (x *FrameRecord) GetLostPackets() uint64 {
	if x != nil && x.LostPackets != nil {
		return *x.LostPackets
	}
	return 0
}

func (x *FrameRecord) GetBackground() BackgroundState {
	if x != nil {
		return x.Background
	}
	return BackgroundState_BACKGROUND_STATE_UNKNOWN
}

func (x *FrameRecord) GetDisposition() Disposition {
	if x != nil {
		return x.Disposition
	}
	return Disposition_DISPOSITION_UNSPECIFIED
}

func (x *FrameRecord) GetDispositionStage() string {
	if x != nil {
		return x.DispositionStage
	}
	return ""
}

func (x *FrameRecord) GetDispositionReason() string {
	if x != nil {
		return x.DispositionReason
	}
	return ""
}

func (x *FrameRecord) GetStages() []*StageCount {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *FrameRecord) GetPoints() *RetainedPoints {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *FrameRecord) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

type StageCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Input         *uint64                `protobuf:"varint,2,opt,name=input,proto3,oneof" json:"input,omitempty"`
	Output        *uint64                `protobuf:"varint,3,opt,name=output,proto3,oneof" json:"output,omitempty"`
	Rejected      *uint64                `protobuf:"varint,4,opt,name=rejected,proto3,oneof" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageCount) Reset() {
	*x = StageCount{}
	mi := &file_recording_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageCount) ProtoMessage() {}

func (x *StageCount) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageCount.ProtoReflect.Descriptor instead.
func (*StageCount) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{10}
}

func (x *StageCount) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StageCount) GetInput() uint64 {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return 0
}

func (x *StageCount) GetOutput() uint64 {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return 0
}

func (x *StageCount) GetRejected() uint64 {
	if x != nil && x.Rejected != nil {
		return *x.Rejected
	}
	return 0
}

// RetainedPoints is the frame's ordered retained-point domain in columns.
// Index i in every present column is the same return. The domain holds only
// valid returns, so there is no per-point validity column: an invalid
// return is counted at its stage, never stored as zeros.
type RetainedPoints struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PointCount uint32                 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// PointColumn bits.
	Columns uint32 `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	// Float64 exactly as L4 computed them; always present, point_count long.
	X []float64 `protobuf:"fixed64,3,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y []float64 `protobuf:"fixed64,4,rep,packed,name=y,proto3" json:"y,omitempty"`
	Z []float64 `protobuf:"fixed64,5,rep,packed,name=z,proto3" json:"z,omitempty"`
	// Acquisition time minus FrameRecord.frame_unix_nanos.
	TimeOffsetNanos []int64 `protobuf:"zigzag64,6,rep,packed,name=time_offset_nanos,json=timeOffsetNanos,proto3" json:"time_offset_nanos,omitempty"`
	// One byte per point, the sensor's native scale.
	Intensity []byte   `protobuf:"bytes,7,opt,name=intensity,proto3" json:"intensity,omitempty"`
	Channel   []uint32 `protobuf:"varint,8,rep,packed,name=channel,proto3" json:"channel,omitempty"`
	// One byte per point.
	ReturnIndex    []byte   `protobuf:"bytes,9,opt,name=return_index,json=returnIndex,proto3" json:"return_index,omitempty"`
	SourceOrdinal  []uint32 `protobuf:"varint,10,rep,packed,name=source_ordinal,json=sourceOrdinal,proto3" json:"source_ordinal,omitempty"`
	PacketSequence []uint32 `protobuf:"varint,11,rep,packed,name=packet_sequence,json=packetSequence,proto3" json:"packet_sequence,omitempty"`
	BlockIndex     []uint32 `protobuf:"varint,12,rep,packed,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetainedPoints) Reset() {
	*x = RetainedPoints{}
	mi := &file_recording_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainedPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedPoints) ProtoMessage() {}

func (x *RetainedPoints) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedPoints.ProtoReflect.Descriptor instead.
func (*RetainedPoints) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{11}
}

func (x *RetainedPoints) GetPointCount() uint32 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *RetainedPoints) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *RetainedPoints) GetX() []float64 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *RetainedPoints) GetY() []float64 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *RetainedPoints) GetZ() []float64 {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *RetainedPoints) GetTimeOffsetNanos() []int64 {
	if x != nil {
		return x.TimeOffsetNanos
	}
	return nil
}

func (x *RetainedPoints) GetIntensity() []byte {
	if x != nil {
		return x.Intensity
	}
	return nil
}

func (x *RetainedPoints) GetChannel() []uint32 {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *RetainedPoints) GetReturnIndex() []byte {
	if x != nil {
		return x.ReturnIndex
	}
	return nil
}

func (x *RetainedPoints) GetSourceOrdinal() []uint32 {
	if x != nil {
		return x.SourceOrdinal
	}
	return nil
}

func (x *RetainedPoints) GetPacketSequence() []uint32 {
	if x != nil {
		return x.PacketSequence
	}
	return nil
}

func (x *RetainedPoints) GetBlockIndex() []uint32 {
	if x != nil {
		return x.BlockIndex
	}
	return nil
}

type Membership struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Clusters []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	// Ascending retained indices in no cluster.
	Unassigned []uint32 `protobuf:"varint,2,rep,packed,name=unassigned,proto3" json:"unassigned,omitempty"`
	// One RejectionReason byte per unassigned index.
	UnassignedReasons []byte `protobuf:"bytes,3,opt,name=unassigned_reasons,json=unassignedReasons,proto3" json:"unassigned_reasons,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_recording_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{12}
}

func (x *Membership) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *Membership) GetUnassigned() []uint32 {
	if x != nil {
		return x.Unassigned
	}
	return nil
}

func (x *Membership) GetUnassignedReasons() []byte {
	if x != nil {
		return x.UnassignedReasons
	}
	return nil
}

type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frame-local; never implies a persistent object.
	ClusterId int64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Sorted, unique retained indices.
	Members       []uint32        `protobuf:"varint,2,rep,packed,name=members,proto3" json:"members,omitempty"`
	Summary       *ClusterSummary `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_recording_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{13}
}

func (x *Cluster) GetClusterId() int64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *Cluster) GetMembers() []uint32 {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Cluster) GetSummary() *ClusterSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// ClusterSummary is L4's summary at its original float32 precision.
type ClusterSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FirstMemberUnixNanos int64                  `protobuf:"fixed64,1,opt,name=first_member_unix_nanos,json=firstMemberUnixNanos,proto3" json:"first_member_unix_nanos,omitempty"`
	CentroidX            float32                `protobuf:"fixed32,2,opt,name=centroid_x,json=centroidX,proto3" json:"centroid_x,omitempty"`
	CentroidY            float32                `protobuf:"fixed32,3,opt,name=centroid_y,json=centroidY,proto3" json:"centroid_y,omitempty"`
	CentroidZ            float32                `protobuf:"fixed32,4,opt,name=centroid_z,json=centroidZ,proto3" json:"centroid_z,omitempty"`
	BoundingBoxLength    float32                `protobuf:"fixed32,5,opt,name=bounding_box_length,json=boundingBoxLength,proto3" json:"bounding_box_length,omitempty"`
	BoundingBoxWidth     float32                `protobuf:"fixed32,6,opt,name=bounding_box_width,json=boundingBoxWidth,proto3" json:"bounding_box_width,omitempty"`
	BoundingBoxHeight    float32                `protobuf:"fixed32,7,opt,name=bounding_box_height,json=boundingBoxHeight,proto3" json:"bounding_box_height,omitempty"`
	HeightP95            float32                `protobuf:"fixed32,8,opt,name=height_p95,json=heightP95,proto3" json:"height_p95,omitempty"`
	IntensityMean        float32                `protobuf:"fixed32,9,opt,name=intensity_mean,json=intensityMean,proto3" json:"intensity_mean,omitempty"`
	PointsCount          uint64                 `protobuf:"varint,10,opt,name=points_count,json=pointsCount,proto3" json:"points_count,omitempty"`
	GroundClipped        bool                   `protobuf:"varint,11,opt,name=ground_clipped,json=groundClipped,proto3" json:"ground_clipped,omitempty"`
	// Absent when L4 produced no oriented box.
	Obb           *OrientedBox `protobuf:"bytes,12,opt,name=obb,proto3" json:"obb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSummary) Reset() {
	*x = ClusterSummary{}
	mi := &file_recording_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSummary) ProtoMessage() {}

func (x *ClusterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSummary.ProtoReflect.Descriptor instead.
func (*ClusterSummary) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{14}
}

func (x *ClusterSummary) GetFirstMemberUnixNanos() int64 {
	if x != nil {
		return x.FirstMemberUnixNanos
	}
	return 0
}

func (x *ClusterSummary) GetCentroidX() float32 {
	if x != nil {
		return x.CentroidX
	}
	return 0
}

func (x *ClusterSummary) GetCentroidY() float32 {
	if x != nil {
		return x.CentroidY
	}
	return 0
}

func (x *ClusterSummary) GetCentroidZ() float32 {
	if x != nil {
		return x.CentroidZ
	}
	return 0
}

func (x *ClusterSummary) GetBoundingBoxLength() float32 {
	if x != nil {
		return x.BoundingBoxLength
	}
	return 0
}

func (x *ClusterSummary) GetBoundingBoxWidth() float32 {
	if x != nil {
		return x.BoundingBoxWidth
	}
	return 0
}

func (x *ClusterSummary) GetBoundingBoxHeight() float32 {
	if x != nil {
		return x.BoundingBoxHeight
	}
	return 0
}

func (x *ClusterSummary) GetHeightP95() float32 {
	if x != nil {
		return x.HeightP95
	}
	return 0
}

func (x *ClusterSummary) GetIntensityMean() float32 {
	if x != nil {
		return x.IntensityMean
	}
	return 0
}

func (x *ClusterSummary) GetPointsCount() uint64 {
	if x != nil {
		return x.PointsCount
	}
	return 0
}

func (x *ClusterSummary) GetGroundClipped() bool {
	if x != nil {
		return x.GroundClipped
	}
	return false
}

func (x *ClusterSummary) GetObb() *OrientedBox {
	if x != nil {
		return x.Obb
	}
	return nil
}

type OrientedBox struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CenterX float32                `protobuf:"fixed32,1,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	CenterY float32                `protobuf:"fixed32,2,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
	CenterZ float32                `protobuf:"fixed32,3,opt,name=center_z,json=centerZ,proto3" json:"center_z,omitempty"`
	Length  float32                `protobuf:"fixed32,4,opt,name=length,proto3" json:"length,omitempty"`
	Width   float32                `protobuf:"fixed32,5,opt,name=width,proto3" json:"width,omitempty"`
	Height  float32                `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	// An axis: heading and heading + pi describe the same box.
	HeadingRad    float32 `protobuf:"fixed32,7,opt,name=heading_rad,json=headingRad,proto3" json:"heading_rad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrientedBox) Reset() {
	*x = OrientedBox{}
	mi := &file_recording_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrientedBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrientedBox) ProtoMessage() {}

func (x *OrientedBox) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrientedBox.ProtoReflect.Descriptor instead.
func (*OrientedBox) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{15}
}

func (x *OrientedBox) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *OrientedBox) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *OrientedBox) GetCenterZ() float32 {
	if x != nil {
		return x.CenterZ
	}
	return 0
}

func (x *OrientedBox) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *OrientedBox) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *OrientedBox) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *OrientedBox) GetHeadingRad() float32 {
	if x != nil {
		return x.HeadingRad
	}
	return 0
}

// GapRecord is one l4bobserve.GapRecord: a missing interval made explicit.
type GapRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Present when the gap covers sequence numbers already assigned.
	SequenceRange  *SequenceRange `protobuf:"bytes,1,opt,name=sequence_range,json=sequenceRange,proto3" json:"sequence_range,omitempty"`
	MissingFrames  *uint64        `protobuf:"varint,2,opt,name=missing_frames,json=missingFrames,proto3,oneof" json:"missing_frames,omitempty"`
	Time           GapTime        `protobuf:"varint,3,opt,name=time,proto3,enum=velocity.recording.v1.GapTime" json:"time,omitempty"`
	StartUnixNanos int64          `protobuf:"fixed64,4,opt,name=start_unix_nanos,json=startUnixNanos,proto3" json:"start_unix_nanos,omitempty"`
	EndUnixNanos   int64          `protobuf:"fixed64,5,opt,name=end_unix_nanos,json=endUnixNanos,proto3" json:"end_unix_nanos,omitempty"`
	Cause          string         `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GapRecord) Reset() {
	*x = GapRecord{}
	mi := &file_recording_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GapRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GapRecord) ProtoMessage() {}

func (x *GapRecord) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GapRecord.ProtoReflect.Descriptor instead.
func (*GapRecord) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{16}
}

func (x *GapRecord) GetSequenceRange() *SequenceRange {
	if x != nil {
		return x.SequenceRange
	}
	return nil
}

func (x *GapRecord) GetMissingFrames() uint64 {
	if x != nil && x.MissingFrames != nil {
		return *x.MissingFrames
	}
	return 0
}

func (x *GapRecord) GetTime() GapTime {
	if x != nil {
		return x.Time
	}
	return GapTime_GAP_TIME_UNKNOWN
}

func (x *GapRecord) GetStartUnixNanos() int64 {
	if x != nil {
		return x.StartUnixNanos
	}
	return 0
}

func (x *GapRecord) GetEndUnixNanos() int64 {
	if x != nil {
		return x.EndUnixNanos
	}
	return 0
}

func (x *GapRecord) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type SequenceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         uint64                 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last          uint64                 `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceRange) Reset() {
	*x = SequenceRange{}
	mi := &file_recording_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceRange) ProtoMessage() {}

func (x *SequenceRange) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceRange.ProtoReflect.Descriptor instead.
func (*SequenceRange) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{17}
}

func (x *SequenceRange) GetFirst() uint64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *SequenceRange) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

// ChunkHeader opens a chunk and binds it to its manifest.
type ChunkHeader struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ordinal uint64                 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// SHA-256 of the manifest object's bytes.
	ManifestSha256 []byte `protobuf:"bytes,2,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChunkHeader) Reset() {
	*x = ChunkHeader{}
	mi := &file_recording_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkHeader) ProtoMessage() {}

func (x *ChunkHeader) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkHeader.ProtoReflect.Descriptor instead.
func (*ChunkHeader) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{18}
}

func (x *ChunkHeader) GetOrdinal() uint64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ChunkHeader) GetManifestSha256() []byte {
	if x != nil {
		return x.ManifestSha256
	}
	return nil
}

// ChunkSeal closes a chunk. body_sha256 covers every byte before the seal
// record; a chunk without a valid seal is an unsealed tail, not evidence.
type ChunkSeal struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Ordinal     uint64                 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	RecordCount uint64                 `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	FrameCount  uint64                 `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	GapCount    uint64                 `protobuf:"varint,4,opt,name=gap_count,json=gapCount,proto3" json:"gap_count,omitempty"`
	// Source sequences covered: [first_sequence, end_sequence).
	FirstSequence uint64 `protobuf:"varint,5,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	EndSequence   uint64 `protobuf:"varint,6,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	// Earliest and latest record start in capture time; absent when no
	// record in the chunk has a known time.
	FirstStartUnixNanos *int64 `protobuf:"fixed64,7,opt,name=first_start_unix_nanos,json=firstStartUnixNanos,proto3,oneof" json:"first_start_unix_nanos,omitempty"`
	LastStartUnixNanos  *int64 `protobuf:"fixed64,8,opt,name=last_start_unix_nanos,json=lastStartUnixNanos,proto3,oneof" json:"last_start_unix_nanos,omitempty"`
	BodyBytes           uint64 `protobuf:"varint,9,opt,name=body_bytes,json=bodyBytes,proto3" json:"body_bytes,omitempty"`
	BodySha256          []byte `protobuf:"bytes,10,opt,name=body_sha256,json=bodySha256,proto3" json:"body_sha256,omitempty"`
	// Semantic digest of the chunk's records in order, computed by the writer
	// from the values it was given; a reader recomputes it from decoded ones.
	SemanticSha256 []byte `protobuf:"bytes,11,opt,name=semantic_sha256,json=semanticSha256,proto3" json:"semantic_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChunkSeal) Reset() {
	*x = ChunkSeal{}
	mi := &file_recording_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSeal) ProtoMessage() {}

func (x *ChunkSeal) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSeal.ProtoReflect.Descriptor instead.
func (*ChunkSeal) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{19}
}

func (x *ChunkSeal) GetOrdinal() uint64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ChunkSeal) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *ChunkSeal) GetFrameCount() uint64 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *ChunkSeal) GetGapCount() uint64 {
	if x != nil {
		return x.GapCount
	}
	return 0
}

func (x *ChunkSeal) GetFirstSequence() uint64 {
	if x != nil {
		return x.FirstSequence
	}
	return 0
}

func (x *ChunkSeal) GetEndSequence() uint64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

func (x *ChunkSeal) GetFirstStartUnixNanos() int64 {
	if x != nil && x.FirstStartUnixNanos != nil {
		return *x.FirstStartUnixNanos
	}
	return 0
}

func (x *ChunkSeal) GetLastStartUnixNanos() int64 {
	if x != nil && x.LastStartUnixNanos != nil {
		return *x.LastStartUnixNanos
	}
	return 0
}

func (x *ChunkSeal) GetBodyBytes() uint64 {
	if x != nil {
		return x.BodyBytes
	}
	return 0
}

func (x *ChunkSeal) GetBodySha256() []byte {
	if x != nil {
		return x.BodySha256
	}
	return nil
}

func (x *ChunkSeal) GetSemanticSha256() []byte {
	if x != nil {
		return x.SemanticSha256
	}
	return nil
}

// ChunkIndex locates every record of one sealed chunk. It is derived data:
// rebuildable from the chunk, and never trusted over the chunk's digest.
// Entries are parallel arrays so allocation is bounded by the object size;
// the wide columns are fixed-width for the same reason.
type ChunkIndex struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ordinal         uint64                 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	ChunkBytes      uint64                 `protobuf:"varint,2,opt,name=chunk_bytes,json=chunkBytes,proto3" json:"chunk_bytes,omitempty"`
	ChunkBodySha256 []byte                 `protobuf:"bytes,3,opt,name=chunk_body_sha256,json=chunkBodySha256,proto3" json:"chunk_body_sha256,omitempty"`
	SealOffset      uint64                 `protobuf:"varint,4,opt,name=seal_offset,json=sealOffset,proto3" json:"seal_offset,omitempty"`
	SealLength      uint32                 `protobuf:"varint,5,opt,name=seal_length,json=sealLength,proto3" json:"seal_length,omitempty"`
	Offset          []uint64               `protobuf:"fixed64,6,rep,packed,name=offset,proto3" json:"offset,omitempty"`
	Length          []uint32               `protobuf:"fixed32,7,rep,packed,name=length,proto3" json:"length,omitempty"`
	Kind            []uint32               `protobuf:"varint,8,rep,packed,name=kind,proto3" json:"kind,omitempty"`
	SequenceFirst   []uint64               `protobuf:"fixed64,9,rep,packed,name=sequence_first,json=sequenceFirst,proto3" json:"sequence_first,omitempty"`
	// Sequences the record covers: 1 for a frame, the range for a gap over
	// assigned sequences, 0 for a gap between received frames.
	SequenceCount []uint64 `protobuf:"fixed64,10,rep,packed,name=sequence_count,json=sequenceCount,proto3" json:"sequence_count,omitempty"`
	TimeStart     []int64  `protobuf:"fixed64,11,rep,packed,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       []int64  `protobuf:"fixed64,12,rep,packed,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// Bit 0: the record's time is known.
	Flags []uint32 `protobuf:"varint,13,rep,packed,name=flags,proto3" json:"flags,omitempty"`
	// Clock/metadata epoch; 0 until epoch records exist.
	Epoch         []uint32 `protobuf:"varint,14,rep,packed,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkIndex) Reset() {
	*x = ChunkIndex{}
	mi := &file_recording_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkIndex) ProtoMessage() {}

func (x *ChunkIndex) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkIndex.ProtoReflect.Descriptor instead.
func (*ChunkIndex) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{20}
}

func (x *ChunkIndex) GetOrdinal() uint64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ChunkIndex) GetChunkBytes() uint64 {
	if x != nil {
		return x.ChunkBytes
	}
	return 0
}

func (x *ChunkIndex) GetChunkBodySha256() []byte {
	if x != nil {
		return x.ChunkBodySha256
	}
	return nil
}

func (x *ChunkIndex) GetSealOffset() uint64 {
	if x != nil {
		return x.SealOffset
	}
	return 0
}

func (x *ChunkIndex) GetSealLength() uint32 {
	if x != nil {
		return x.SealLength
	}
	return 0
}

func (x *ChunkIndex) GetOffset() []uint64 {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *ChunkIndex) GetLength() []uint32 {
	if x != nil {
		return x.Length
	}
	return nil
}

func (x *ChunkIndex) GetKind() []uint32 {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ChunkIndex) GetSequenceFirst() []uint64 {
	if x != nil {
		return x.SequenceFirst
	}
	return nil
}

func (x *ChunkIndex) GetSequenceCount() []uint64 {
	if x != nil {
		return x.SequenceCount
	}
	return nil
}

func (x *ChunkIndex) GetTimeStart() []int64 {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *ChunkIndex) GetTimeEnd() []int64 {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *ChunkIndex) GetFlags() []uint32 {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ChunkIndex) GetEpoch() []uint32 {
	if x != nil {
		return x.Epoch
	}
	return nil
}

// CaptureSummary is written by a clean close. It is optional: sealed chunks
// are readable without it. When present, a reader requires the sealed
// chunks to match it exactly, which detects a missing final chunk.
type CaptureSummary struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChunkCount uint64                 `protobuf:"varint,1,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	// chain_i = SHA-256(chain_{i-1} || body_sha256_i), chain_{-1} = 32 zero
	// bytes; this is chain_{chunk_count-1}, or zeros for no chunks.
	ChunkChainSha256 []byte `protobuf:"bytes,2,opt,name=chunk_chain_sha256,json=chunkChainSha256,proto3" json:"chunk_chain_sha256,omitempty"`
	RecordCount      uint64 `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	FrameCount       uint64 `protobuf:"varint,4,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	GapCount         uint64 `protobuf:"varint,5,opt,name=gap_count,json=gapCount,proto3" json:"gap_count,omitempty"`
	EndSequence      uint64 `protobuf:"varint,6,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	// Frames the writer refused (over a limit), each replaced by a gap over
	// its sequence. Non-zero means the capture is incomplete.
	RejectedFrames uint64 `protobuf:"varint,7,opt,name=rejected_frames,json=rejectedFrames,proto3" json:"rejected_frames,omitempty"`
	// Semantic digest of every record in order.
	SemanticSha256 []byte `protobuf:"bytes,8,opt,name=semantic_sha256,json=semanticSha256,proto3" json:"semantic_sha256,omitempty"`
	// Sum of the sealed chunk files' sizes.
	TotalChunkBytes uint64 `protobuf:"varint,9,opt,name=total_chunk_bytes,json=totalChunkBytes,proto3" json:"total_chunk_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureSummary) Reset() {
	*x = CaptureSummary{}
	mi := &file_recording_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSummary) ProtoMessage() {}

func (x *CaptureSummary) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSummary.ProtoReflect.Descriptor instead.
func (*CaptureSummary) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{21}
}

func (x *CaptureSummary) GetChunkCount() uint64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *CaptureSummary) GetChunkChainSha256() []byte {
	if x != nil {
		return x.ChunkChainSha256
	}
	return nil
}

func (x *CaptureSummary) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *CaptureSummary) GetFrameCount() uint64 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *CaptureSummary) GetGapCount() uint64 {
	if x != nil {
		return x.GapCount
	}
	return 0
}

func (x *CaptureSummary) GetEndSequence() uint64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

func (x *CaptureSummary) GetRejectedFrames() uint64 {
	if x != nil {
		return x.RejectedFrames
	}
	return 0
}

func (x *CaptureSummary) GetSemanticSha256() []byte {
	if x != nil {
		return x.SemanticSha256
	}
	return nil
}

func (x *CaptureSummary) GetTotalChunkBytes() uint64 {
	if x != nil {
		return x.TotalChunkBytes
	}
	return 0
}

var File_recording_proto protoreflect.FileDescriptor

const file_recording_proto_rawDesc = "" +
	"\n" +
	"\x0frecording.proto\x12\x15velocity.recording.v1\"\xd7\x05\n" +
	"\x11RecordingManifest\x12K\n" +
	"\x0eschema_version\x18\x01 \x01(\x0e2$.velocity.recording.v1.SchemaVersionR\rschemaVersion\x12B\n" +
	"\vstream_kind\x18\x02 \x01(\x0e2!.velocity.recording.v1.StreamKindR\n" +
	"streamKind\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12+\n" +
	"\x11required_features\x18\x05 \x03(\tR\x10requiredFeatures\x126\n" +
	"\x17semantic_digest_version\x18\x06 \x01(\tR\x15semanticDigestVersion\x12@\n" +
	"\acapture\x18\a \x01(\v2&.velocity.recording.v1.CaptureIdentityR\acapture\x12I\n" +
	"\n" +
	"extraction\x18\b \x01(\v2).velocity.recording.v1.ExtractionIdentityR\n" +
	"extraction\x12D\n" +
	"\vcalibration\x18\t \x01(\v2\".velocity.recording.v1.CalibrationR\vcalibration\x125\n" +
	"\x06limits\x18\n" +
	" \x01(\v2\x1d.velocity.recording.v1.LimitsR\x06limits\x12A\n" +
	"\n" +
	"provenance\x18\v \x01(\v2!.velocity.recording.v1.ProvenanceR\n" +
	"provenance\x12A\n" +
	"\bmetadata\x18\f \x03(\v2%.velocity.recording.v1.MetadataObjectR\bmetadata\"\xd0\x01\n" +
	"\x0fCaptureIdentity\x12!\n" +
	"\fcapture_uuid\x18\x01 \x01(\tR\vcaptureUuid\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12.\n" +
	"\x13parent_capture_uuid\x18\x04 \x01(\tR\x11parentCaptureUuid\x12,\n" +
	"\x12created_unix_nanos\x18\x05 \x01(\x10R\x10createdUnixNanos\"\xd2\x02\n" +
	"\x12ExtractionIdentity\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12%\n" +
	"\x0ecalibration_id\x18\x02 \x01(\tR\rcalibrationId\x12)\n" +
	"\x10coordinate_frame\x18\x03 \x01(\tR\x0fcoordinateFrame\x12$\n" +
	"\x0ereplay_case_id\x18\x04 \x01(\tR\freplayCaseId\x12G\n" +
	"\rcapture_files\x18\x05 \x03(\v2\".velocity.recording.v1.CaptureFileR\fcaptureFiles\x12!\n" +
	"\fextractor_id\x18\x06 \x01(\tR\vextractorId\x12;\n" +
	"\x06window\x18\a \x01(\v2#.velocity.recording.v1.SourceWindowR\x06window\"9\n" +
	"\vCaptureFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\x86\x01\n" +
	"\fSourceWindow\x12,\n" +
	"\x12start_offset_nanos\x18\x01 \x01(\x10R\x10startOffsetNanos\x12!\n" +
	"\fwarmup_nanos\x18\x02 \x01(\x10R\vwarmupNanos\x12%\n" +
	"\x0eduration_nanos\x18\x03 \x01(\x10R\rdurationNanos\"\x82\x01\n" +
	"\vCalibration\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1d\n" +
	"\n" +
	"from_frame\x18\x02 \x01(\tR\tfromFrame\x12\x19\n" +
	"\bto_frame\x18\x03 \x01(\tR\atoFrame\x12\x1c\n" +
	"\ttransform\x18\x04 \x03(\x01R\ttransform\"\xd2\x02\n" +
	"\x06Limits\x12,\n" +
	"\x12target_chunk_bytes\x18\x01 \x01(\x04R\x10targetChunkBytes\x12&\n" +
	"\x0fmax_chunk_bytes\x18\x02 \x01(\x04R\rmaxChunkBytes\x12(\n" +
	"\x10max_record_bytes\x18\x03 \x01(\rR\x0emaxRecordBytes\x121\n" +
	"\x15max_records_per_chunk\x18\x04 \x01(\rR\x12maxRecordsPerChunk\x12/\n" +
	"\x14max_points_per_frame\x18\x05 \x01(\rR\x11maxPointsPerFrame\x123\n" +
	"\x16max_clusters_per_frame\x18\x06 \x01(\rR\x13maxClustersPerFrame\x12/\n" +
	"\x14max_stages_per_frame\x18\a \x01(\rR\x11maxStagesPerFrame\"\xe4\x01\n" +
	"\n" +
	"Provenance\x12#\n" +
	"\rbuild_version\x18\x01 \x01(\tR\fbuildVersion\x12\"\n" +
	"\rbuild_git_sha\x18\x02 \x01(\tR\vbuildGitSha\x12\x16\n" +
	"\x06writer\x18\x03 \x01(\tR\x06writer\x12\x1f\n" +
	"\vparams_hash\x18\x04 \x01(\tR\n" +
	"paramsHash\x122\n" +
	"\x15params_schema_version\x18\x05 \x01(\tR\x13paramsSchemaVersion\x12 \n" +
	"\vexperiments\x18\x06 \x03(\tR\vexperiments\"u\n" +
	"\x0eMetadataObject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\x92\x06\n" +
	"\vFrameRecord\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12&\n" +
	"\x0fsensor_frame_id\x18\x02 \x01(\tR\rsensorFrameId\x12(\n" +
	"\x10frame_unix_nanos\x18\x03 \x01(\x10R\x0eframeUnixNanos\x127\n" +
	"\x18capture_start_unix_nanos\x18\x04 \x01(\x10R\x15captureStartUnixNanos\x123\n" +
	"\x16capture_end_unix_nanos\x18\x05 \x01(\x10R\x13captureEndUnixNanos\x12G\n" +
	"\fcompleteness\x18\x06 \x01(\x0e2#.velocity.recording.v1.CompletenessR\fcompleteness\x12&\n" +
	"\flost_packets\x18\a \x01(\x04H\x00R\vlostPackets\x88\x01\x01\x12F\n" +
	"\n" +
	"background\x18\b \x01(\x0e2&.velocity.recording.v1.BackgroundStateR\n" +
	"background\x12D\n" +
	"\vdisposition\x18\t \x01(\x0e2\".velocity.recording.v1.DispositionR\vdisposition\x12+\n" +
	"\x11disposition_stage\x18\n" +
	" \x01(\tR\x10dispositionStage\x12-\n" +
	"\x12disposition_reason\x18\v \x01(\tR\x11dispositionReason\x129\n" +
	"\x06stages\x18\f \x03(\v2!.velocity.recording.v1.StageCountR\x06stages\x12=\n" +
	"\x06points\x18\r \x01(\v2%.velocity.recording.v1.RetainedPointsR\x06points\x12A\n" +
	"\n" +
	"membership\x18\x0e \x01(\v2!.velocity.recording.v1.MembershipR\n" +
	"membershipB\x0f\n" +
	"\r_lost_packets\"\x9d\x01\n" +
	"\n" +
	"StageCount\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x19\n" +
	"\x05input\x18\x02 \x01(\x04H\x00R\x05input\x88\x01\x01\x12\x1b\n" +
	"\x06output\x18\x03 \x01(\x04H\x01R\x06output\x88\x01\x01\x12\x1f\n" +
	"\brejected\x18\x04 \x01(\x04H\x02R\brejected\x88\x01\x01B\b\n" +
	"\x06_inputB\t\n" +
	"\a_outputB\v\n" +
	"\t_rejected\"\xed\x02\n" +
	"\x0eRetainedPoints\x12\x1f\n" +
	"\vpoint_count\x18\x01 \x01(\rR\n" +
	"pointCount\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\rR\acolumns\x12\f\n" +
	"\x01x\x18\x03 \x03(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x03(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x05 \x03(\x01R\x01z\x12*\n" +
	"\x11time_offset_nanos\x18\x06 \x03(\x12R\x0ftimeOffsetNanos\x12\x1c\n" +
	"\tintensity\x18\a \x01(\fR\tintensity\x12\x18\n" +
	"\achannel\x18\b \x03(\rR\achannel\x12!\n" +
	"\freturn_index\x18\t \x01(\fR\vreturnIndex\x12%\n" +
	"\x0esource_ordinal\x18\n" +
	" \x03(\rR\rsourceOrdinal\x12'\n" +
	"\x0fpacket_sequence\x18\v \x03(\rR\x0epacketSequence\x12\x1f\n" +
	"\vblock_index\x18\f \x03(\rR\n" +
	"blockIndex\"\x97\x01\n" +
	"\n" +
	"Membership\x12:\n" +
	"\bclusters\x18\x01 \x03(\v2\x1e.velocity.recording.v1.ClusterR\bclusters\x12\x1e\n" +
	"\n" +
	"unassigned\x18\x02 \x03(\rR\n" +
	"unassigned\x12-\n" +
	"\x12unassigned_reasons\x18\x03 \x01(\fR\x11unassignedReasons\"\x83\x01\n" +
	"\aCluster\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x03R\tclusterId\x12\x18\n" +
	"\amembers\x18\x02 \x03(\rR\amembers\x12?\n" +
	"\asummary\x18\x03 \x01(\v2%.velocity.recording.v1.ClusterSummaryR\asummary\"\xf8\x03\n" +
	"\x0eClusterSummary\x125\n" +
	"\x17first_member_unix_nanos\x18\x01 \x01(\x10R\x14firstMemberUnixNanos\x12\x1d\n" +
	"\n" +
	"centroid_x\x18\x02 \x01(\x02R\tcentroidX\x12\x1d\n" +
	"\n" +
	"centroid_y\x18\x03 \x01(\x02R\tcentroidY\x12\x1d\n" +
	"\n" +
	"centroid_z\x18\x04 \x01(\x02R\tcentroidZ\x12.\n" +
	"\x13bounding_box_length\x18\x05 \x01(\x02R\x11boundingBoxLength\x12,\n" +
	"\x12bounding_box_width\x18\x06 \x01(\x02R\x10boundingBoxWidth\x12.\n" +
	"\x13bounding_box_height\x18\a \x01(\x02R\x11boundingBoxHeight\x12\x1d\n" +
	"\n" +
	"height_p95\x18\b \x01(\x02R\theightP95\x12%\n" +
	"\x0eintensity_mean\x18\t \x01(\x02R\rintensityMean\x12!\n" +
	"\fpoints_count\x18\n" +
	" \x01(\x04R\vpointsCount\x12%\n" +
	"\x0eground_clipped\x18\v \x01(\bR\rgroundClipped\x124\n" +
	"\x03obb\x18\f \x01(\v2\".velocity.recording.v1.OrientedBoxR\x03obb\"\xc5\x01\n" +
	"\vOrientedBox\x12\x19\n" +
	"\bcenter_x\x18\x01 \x01(\x02R\acenterX\x12\x19\n" +
	"\bcenter_y\x18\x02 \x01(\x02R\acenterY\x12\x19\n" +
	"\bcenter_z\x18\x03 \x01(\x02R\acenterZ\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x02R\x06length\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x02R\x06height\x12\x1f\n" +
	"\vheading_rad\x18\a \x01(\x02R\n" +
	"headingRad\"\xb1\x02\n" +
	"\tGapRecord\x12K\n" +
	"\x0esequence_range\x18\x01 \x01(\v2$.velocity.recording.v1.SequenceRangeR\rsequenceRange\x12*\n" +
	"\x0emissing_frames\x18\x02 \x01(\x04H\x00R\rmissingFrames\x88\x01\x01\x122\n" +
	"\x04time\x18\x03 \x01(\x0e2\x1e.velocity.recording.v1.GapTimeR\x04time\x12(\n" +
	"\x10start_unix_nanos\x18\x04 \x01(\x10R\x0estartUnixNanos\x12$\n" +
	"\x0eend_unix_nanos\x18\x05 \x01(\x10R\fendUnixNanos\x12\x14\n" +
	"\x05cause\x18\x06 \x01(\tR\x05causeB\x11\n" +
	"\x0f_missing_frames\"9\n" +
	"\rSequenceRange\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x04R\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\x04R\x04last\"P\n" +
	"\vChunkHeader\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x04R\aordinal\x12'\n" +
	"\x0fmanifest_sha256\x18\x02 \x01(\fR\x0emanifestSha256\"\xe0\x03\n" +
	"\tChunkSeal\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x04R\aordinal\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x04R\vrecordCount\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\x04R\n" +
	"frameCount\x12\x1b\n" +
	"\tgap_count\x18\x04 \x01(\x04R\bgapCount\x12%\n" +
	"\x0efirst_sequence\x18\x05 \x01(\x04R\rfirstSequence\x12!\n" +
	"\fend_sequence\x18\x06 \x01(\x04R\vendSequence\x128\n" +
	"\x16first_start_unix_nanos\x18\a \x01(\x10H\x00R\x13firstStartUnixNanos\x88\x01\x01\x126\n" +
	"\x15last_start_unix_nanos\x18\b \x01(\x10H\x01R\x12lastStartUnixNanos\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"body_bytes\x18\t \x01(\x04R\tbodyBytes\x12\x1f\n" +
	"\vbody_sha256\x18\n" +
	" \x01(\fR\n" +
	"bodySha256\x12'\n" +
	"\x0fsemantic_sha256\x18\v \x01(\fR\x0esemanticSha256B\x19\n" +
	"\x17_first_start_unix_nanosB\x18\n" +
	"\x16_last_start_unix_nanos\"\xad\x03\n" +
	"\n" +
	"ChunkIndex\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x04R\aordinal\x12\x1f\n" +
	"\vchunk_bytes\x18\x02 \x01(\x04R\n" +
	"chunkBytes\x12*\n" +
	"\x11chunk_body_sha256\x18\x03 \x01(\fR\x0fchunkBodySha256\x12\x1f\n" +
	"\vseal_offset\x18\x04 \x01(\x04R\n" +
	"sealOffset\x12\x1f\n" +
	"\vseal_length\x18\x05 \x01(\rR\n" +
	"sealLength\x12\x16\n" +
	"\x06offset\x18\x06 \x03(\x06R\x06offset\x12\x16\n" +
	"\x06length\x18\a \x03(\aR\x06length\x12\x12\n" +
	"\x04kind\x18\b \x03(\rR\x04kind\x12%\n" +
	"\x0esequence_first\x18\t \x03(\x06R\rsequenceFirst\x12%\n" +
	"\x0esequence_count\x18\n" +
	" \x03(\x06R\rsequenceCount\x12\x1d\n" +
	"\n" +
	"time_start\x18\v \x03(\x10R\ttimeStart\x12\x19\n" +
	"\btime_end\x18\f \x03(\x10R\atimeEnd\x12\x14\n" +
	"\x05flags\x18\r \x03(\rR\x05flags\x12\x14\n" +
	"\x05epoch\x18\x0e \x03(\rR\x05epoch\"\xe1\x02\n" +
	"\x0eCaptureSummary\x12\x1f\n" +
	"\vchunk_count\x18\x01 \x01(\x04R\n" +
	"chunkCount\x12,\n" +
	"\x12chunk_chain_sha256\x18\x02 \x01(\fR\x10chunkChainSha256\x12!\n" +
	"\frecord_count\x18\x03 \x01(\x04R\vrecordCount\x12\x1f\n" +
	"\vframe_count\x18\x04 \x01(\x04R\n" +
	"frameCount\x12\x1b\n" +
	"\tgap_count\x18\x05 \x01(\x04R\bgapCount\x12!\n" +
	"\fend_sequence\x18\x06 \x01(\x04R\vendSequence\x12'\n" +
	"\x0frejected_frames\x18\a \x01(\x04R\x0erejectedFrames\x12'\n" +
	"\x0fsemantic_sha256\x18\b \x01(\fR\x0esemanticSha256\x12*\n" +
	"\x11total_chunk_bytes\x18\t \x01(\x04R\x0ftotalChunkBytes*E\n" +
	"\rSchemaVersion\x12\x1e\n" +
	"\x1aSCHEMA_VERSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SCHEMA_VERSION_1\x10\x01*F\n" +
	"\n" +
	"StreamKind\x12\x1b\n" +
	"\x17STREAM_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_KIND_OBSERVATION\x10\x01*]\n" +
	"\fCompleteness\x12\x18\n" +
	"\x14COMPLETENESS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15COMPLETENESS_COMPLETE\x10\x01\x12\x18\n" +
	"\x14COMPLETENESS_PARTIAL\x10\x02*l\n" +
	"\x0fBackgroundState\x12\x1c\n" +
	"\x18BACKGROUND_STATE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19BACKGROUND_STATE_SETTLING\x10\x01\x12\x1c\n" +
	"\x18BACKGROUND_STATE_SETTLED\x10\x02*\x93\x01\n" +
	"\vDisposition\x12\x1b\n" +
	"\x17DISPOSITION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DISPOSITION_OBSERVED\x10\x01\x12\x19\n" +
	"\x15DISPOSITION_UNSETTLED\x10\x02\x12\x1a\n" +
	"\x16DISPOSITION_SUPPRESSED\x10\x03\x12\x16\n" +
	"\x12DISPOSITION_FAILED\x10\x04*\x84\x02\n" +
	"\vPointColumn\x12\x1c\n" +
	"\x18POINT_COLUMN_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPOINT_COLUMN_ACQUISITION_TIME\x10\x01\x12\x1a\n" +
	"\x16POINT_COLUMN_INTENSITY\x10\x02\x12\x18\n" +
	"\x14POINT_COLUMN_CHANNEL\x10\x04\x12\x1d\n" +
	"\x19POINT_COLUMN_RETURN_INDEX\x10\b\x12\x1f\n" +
	"\x1bPOINT_COLUMN_SOURCE_ORDINAL\x10\x10\x12 \n" +
	"\x1cPOINT_COLUMN_PACKET_SEQUENCE\x10 \x12\x1c\n" +
	"\x18POINT_COLUMN_BLOCK_INDEX\x10@*\xbb\x02\n" +
	"\x0fRejectionReason\x12\x1c\n" +
	"\x18REJECTION_REASON_UNKNOWN\x10\x00\x12 \n" +
	"\x1cREJECTION_REASON_HEIGHT_BAND\x10\x01\x12(\n" +
	"$REJECTION_REASON_SURFACE_BELOW_FLOOR\x10\x02\x12*\n" +
	"&REJECTION_REASON_SURFACE_ABOVE_CEILING\x10\x03\x12\"\n" +
	"\x1eREJECTION_REASON_VOXEL_REDUCED\x10\x04\x12&\n" +
	"\"REJECTION_REASON_CLUSTER_INPUT_CAP\x10\x05\x12\"\n" +
	"\x1eREJECTION_REASON_CLUSTER_NOISE\x10\x06\x12\"\n" +
	"\x1eREJECTION_REASON_CLUSTER_SHAPE\x10\a*5\n" +
	"\aGapTime\x12\x14\n" +
	"\x10GAP_TIME_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10GAP_TIME_BOUNDED\x10\x01BDZBgithub.com/banshee-data/velocity.report/internal/lidar/recordingpbb\x06proto3"

var (
	file_recording_proto_rawDescOnce sync.Once
	file_recording_proto_rawDescData []byte
)

func file_recording_proto_rawDescGZIP() []byte {
	file_recording_proto_rawDescOnce.Do(func() {
		file_recording_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recording_proto_rawDesc), len(file_recording_proto_rawDesc)))
	})
	return file_recording_proto_rawDescData
}

var file_recording_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_recording_proto_goTypes = []any{
	(SchemaVersion)(0),         // 0: velocity.recording.v1.SchemaVersion
	(StreamKind)(0),            // 1: velocity.recording.v1.StreamKind
	(Completeness)(0),          // 2: velocity.recording.v1.Completeness
	(BackgroundState)(0),       // 3: velocity.recording.v1.BackgroundState
	(Disposition)(0),           // 4: velocity.recording.v1.Disposition
	(PointColumn)(0),           // 5: velocity.recording.v1.PointColumn
	(RejectionReason)(0),       // 6: velocity.recording.v1.RejectionReason
	(GapTime)(0),               // 7: velocity.recording.v1.GapTime
	(*RecordingManifest)(nil),  // 8: velocity.recording.v1.RecordingManifest
	(*CaptureIdentity)(nil),    // 9: velocity.recording.v1.CaptureIdentity
	(*ExtractionIdentity)(nil), // 10: velocity.recording.v1.ExtractionIdentity
	(*CaptureFile)(nil),        // 11: velocity.recording.v1.CaptureFile
	(*SourceWindow)(nil),       // 12: velocity.recording.v1.SourceWindow
	(*Calibration)(nil),        // 13: velocity.recording.v1.Calibration
	(*Limits)(nil),             // 14: velocity.recording.v1.Limits
	(*Provenance)(nil),         // 15: velocity.recording.v1.Provenance
	(*MetadataObject)(nil),     // 16: velocity.recording.v1.MetadataObject
	(*FrameRecord)(nil),        // 17: velocity.recording.v1.FrameRecord
	(*StageCount)(nil),         // 18: velocity.recording.v1.StageCount
	(*RetainedPoints)(nil),     // 19: velocity.recording.v1.RetainedPoints
	(*Membership)(nil),         // 20: velocity.recording.v1.Membership
	(*Cluster)(nil),            // 21: velocity.recording.v1.Cluster
	(*ClusterSummary)(nil),     // 22: velocity.recording.v1.ClusterSummary
	(*OrientedBox)(nil),        // 23: velocity.recording.v1.OrientedBox
	(*GapRecord)(nil),          // 24: velocity.recording.v1.GapRecord
	(*SequenceRange)(nil),      // 25: velocity.recording.v1.SequenceRange
	(*ChunkHeader)(nil),        // 26: velocity.recording.v1.ChunkHeader
	(*ChunkSeal)(nil),          // 27: velocity.recording.v1.ChunkSeal
	(*ChunkIndex)(nil),         // 28: velocity.recording.v1.ChunkIndex
	(*CaptureSummary)(nil),     // 29: velocity.recording.v1.CaptureSummary
}
var file_recording_proto_depIdxs = []int32{
	0,  // 0: velocity.recording.v1.RecordingManifest.schema_version:type_name -> velocity.recording.v1.SchemaVersion
	1,  // 1: velocity.recording.v1.RecordingManifest.stream_kind:type_name -> velocity.recording.v1.StreamKind
	9,  // 2: velocity.recording.v1.RecordingManifest.capture:type_name -> velocity.recording.v1.CaptureIdentity
	10, // 3: velocity.recording.v1.RecordingManifest.extraction:type_name -> velocity.recording.v1.ExtractionIdentity
	13, // 4: velocity.recording.v1.RecordingManifest.calibration:type_name -> velocity.recording.v1.Calibration
	14, // 5: velocity.recording.v1.RecordingManifest.limits:type_name -> velocity.recording.v1.Limits
	15, // 6: velocity.recording.v1.RecordingManifest.provenance:type_name -> velocity.recording.v1.Provenance
	16, // 7: velocity.recording.v1.RecordingManifest.metadata:type_name -> velocity.recording.v1.MetadataObject
	11, // 8: velocity.recording.v1.ExtractionIdentity.capture_files:type_name -> velocity.recording.v1.CaptureFile
	12, // 9: velocity.recording.v1.ExtractionIdentity.window:type_name -> velocity.recording.v1.SourceWindow
	2,  // 10: velocity.recording.v1.FrameRecord.completeness:type_name -> velocity.recording.v1.Completeness
	3,  // 11: velocity.recording.v1.FrameRecord.background:type_name -> velocity.recording.v1.BackgroundState
	4,  // 12: velocity.recording.v1.FrameRecord.disposition:type_name -> velocity.recording.v1.Disposition
	18, // 13: velocity.recording.v1.FrameRecord.stages:type_name -> velocity.recording.v1.StageCount
	19, // 14: velocity.recording.v1.FrameRecord.points:type_name -> velocity.recording.v1.RetainedPoints
	20, // 15: velocity.recording.v1.FrameRecord.membership:type_name -> velocity.recording.v1.Membership
	21, // 16: velocity.recording.v1.Membership.clusters:type_name -> velocity.recording.v1.Cluster
	22, // 17: velocity.recording.v1.Cluster.summary:type_name -> velocity.recording.v1.ClusterSummary
	23, // 18: velocity.recording.v1.ClusterSummary.obb:type_name -> velocity.recording.v1.OrientedBox
	25, // 19: velocity.recording.v1.GapRecord.sequence_range:type_name -> velocity.recording.v1.SequenceRange
	7,  // 20: velocity.recording.v1.GapRecord.time:type_name -> velocity.recording.v1.GapTime
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_recording_proto_init() }
func file_recording_proto_init() {
	if File_recording_proto != nil {
		return
	}
	file_recording_proto_msgTypes[9].OneofWrappers = []any{}
	file_recording_proto_msgTypes[10].OneofWrappers = []any{}
	file_recording_proto_msgTypes[16].OneofWrappers = []any{}
	file_recording_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recording_proto_rawDesc), len(file_recording_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recording_proto_goTypes,
		DependencyIndexes: file_recording_proto_depIdxs,
		EnumInfos:         file_recording_proto_enumTypes,
		MessageInfos:      file_recording_proto_msgTypes,
	}.Build()
	File_recording_proto = out.File
	file_recording_proto_goTypes = nil
	file_recording_proto_depIdxs = nil
}
