#!/usr/bin/env python3
"""
draw_rack.py — Rack-mount engineering drawing sheets.

Directory layout
───────────────
  build/     Intermediate 3D-view SVGs (one per projection).
             Contents are gitignored; directory is kept with .gitkeep.
  output/    Final output: combined drawing sheet PNG.
             Checked into git so the guide can reference it directly.

Both directories are created automatically if absent.

The 3D view SVGs are generated by model.py (build123d / OCCT).
The BOM table, dimension annotations, and title block are overlaid via
drawsvg, and the finished SVG is rasterised to PNG via rsvg-convert.

Usage:
    python draw_rack.py
    python draw_rack.py --config rack.json
"""

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

import drawsvg as draw

from components import (
    bom_table,
    dim_h,
    dim_v,
    leader,
    DIM_COLOUR,
    FONT,
    FS_LABEL,
    FS_HEAD,
)

# ── Sheet geometry ────────────────────────────────────────────────────────────

SHEET_W = 1200
SHEET_H = 850
COMBINED_H = 1600
MARGIN = 28

# ── SVG viewport embed ────────────────────────────────────────────────────────


def embed_svg_as_image(
    d: draw.Drawing,
    svg_path: str,
    x: float,
    y: float,
    w: float,
    h: float,
) -> None:
    """Embed an SVG file as a base64-encoded <image> element (self-contained output)."""
    import base64

    with open(svg_path, "rb") as f:
        data = base64.b64encode(f.read()).decode("ascii")
    uri = f"data:image/svg+xml;base64,{data}"
    d.append(draw.Image(x, y, w, h, uri, embed=False))


# ── Title block ───────────────────────────────────────────────────────────────

TB_W = 380  # title block width
TB_H = 96  # title block height


def draw_title_block(d: draw.Drawing, cfg: dict, sheet_h: float = SHEET_H) -> None:
    """Standard lower-right title block."""
    tb_x = SHEET_W - MARGIN - TB_W
    tb_y = sheet_h - MARGIN - TB_H

    # Background + outer border
    d.append(
        draw.Rectangle(
            tb_x,
            tb_y,
            TB_W,
            TB_H,
            fill="white",
            stroke="#333",
            stroke_width=1.0,
        )
    )

    # ── Row heights from top: title(28) | row1(28) | row2(20) | row3(20) ──
    r0_h, r1_h, r2_h, r3_h = 28, 24, 22, 22
    r0_y = tb_y
    r1_y = r0_y + r0_h
    r2_y = r1_y + r1_h
    r3_y = r2_y + r2_h

    # Row dividers
    for ry in (r1_y, r2_y, r3_y):
        d.append(draw.Line(tb_x, ry, tb_x + TB_W, ry, stroke="#333", stroke_width=0.5))

    # Row 0 — drawing title (full width, bold centre)
    d.append(
        draw.Text(
            "velocity.report Radar Mount",
            FS_HEAD,
            tb_x + TB_W / 2,
            r0_y + r0_h / 2,
            text_anchor="middle",
            dominant_baseline="middle",
            font_family=FONT,
            fill="#1a1a2e",
            font_weight="bold",
        )
    )

    # Rows 1-3: two-column cells (label top-left, value centred)
    def cell(
        label: str,
        value: str,
        cx: float,
        cy: float,
        cw: float,
        ch: float,
        bold: bool = False,
    ) -> None:
        d.append(
            draw.Text(
                label,
                6,
                cx + 3,
                cy + 3,
                dominant_baseline="hanging",
                font_family=FONT,
                fill="#888",
            )
        )
        d.append(
            draw.Text(
                value,
                FS_LABEL if not bold else FS_LABEL + 1,
                cx + cw / 2,
                cy + ch / 2 + 3,
                text_anchor="middle",
                dominant_baseline="middle",
                font_family=FONT,
                fill="#1a1a2e",
                font_weight="bold" if bold else "normal",
            )
        )

    # Row 1: FIRM (60%) | DRAWN BY (40%)
    col_a = int(TB_W * 0.60)
    d.append(
        draw.Line(
            tb_x + col_a, r1_y, tb_x + col_a, r2_y, stroke="#333", stroke_width=0.4
        )
    )
    cell("FIRM", "Banshee Inc", tb_x, r1_y, col_a, r1_h, bold=True)
    cell("DRAWN BY", "D. Dolphin", tb_x + col_a, r1_y, TB_W - col_a, r1_h)

    # Row 2: DATE (40%) | REV (30%) | SCALE (30%)
    col_b, col_c = int(TB_W * 0.40), int(TB_W * 0.30)
    d.append(
        draw.Line(
            tb_x + col_b, r2_y, tb_x + col_b, r3_y, stroke="#333", stroke_width=0.4
        )
    )
    d.append(
        draw.Line(
            tb_x + col_b + col_c,
            r2_y,
            tb_x + col_b + col_c,
            r3_y,
            stroke="#333",
            stroke_width=0.4,
        )
    )
    cell("DATE", "2026-04-15", tb_x, r2_y, col_b, r2_h)
    cell(
        "REV",
        f"Rev {cfg.get('revision', 'A')}",
        tb_x + col_b,
        r2_y,
        col_c,
        r2_h,
        bold=True,
    )
    cell("SCALE", "1:10", tb_x + col_b + col_c, r2_y, TB_W - col_b - col_c, r2_h)

    # Row 3: PROJECTION (full width)
    cell("PROJECTION", "THIRD-ANGLE", tb_x, r3_y, TB_W, r3_h)

    # Sheet border
    d.append(
        draw.Rectangle(
            MARGIN,
            MARGIN,
            SHEET_W - 2 * MARGIN,
            sheet_h - 2 * MARGIN,
            fill="none",
            stroke="#333",
            stroke_width=1.5,
        )
    )


def view_label(d: draw.Drawing, text: str, x: float, y: float) -> None:
    pass  # labels removed


# ── Sheet builders ────────────────────────────────────────────────────────────


def build_iso_bom_sheet(cfg: dict, iso_svg: str, out_path: str) -> None:
    """Sheet 1: isometric view + BOM table + title block."""
    d = draw.Drawing(SHEET_W, SHEET_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, SHEET_H, fill="white"))

    vw, vh = 620, 460
    embed_svg_as_image(d, iso_svg, MARGIN, MARGIN + 10, vw, vh)
    view_label(d, "ISOMETRIC VIEW", MARGIN + vw / 2, MARGIN + 10 + vh + 14)

    d.append(
        draw.Line(
            MARGIN + vw + 10,
            MARGIN,
            MARGIN + vw + 10,
            SHEET_H - TITLE_H - MARGIN - 10,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    bom_table(
        d,
        x=MARGIN + vw + 22,
        y=MARGIN + 10,
        items=cfg["bom"],
        title="BILL OF MATERIALS  —  Sensor Mount Subassembly",
    )

    draw_title_block(d, cfg)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


def build_ortho_sheet(
    cfg: dict,
    front_svg: str,
    top_svg: str,
    side_svg: str,
    out_path: str,
) -> None:
    """Sheet 2: third-angle orthographic projection (front + top + side)."""
    d = draw.Drawing(SHEET_W, SHEET_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, SHEET_H, fill="white"))

    draw_w = SHEET_W - 2 * MARGIN
    draw_h = SHEET_H - 2 * MARGIN - 14  # small bottom gap above title block
    gap = 14
    lbl = 18

    # Third-angle layout:
    #     [  TOP VIEW  ]
    #     [FRONT] [SIDE]
    top_h = int(draw_h * 0.28)
    bot_h = draw_h - top_h - gap - lbl
    left_w = int(draw_w * 0.58)
    right_w = draw_w - left_w - gap

    # Top view
    embed_svg_as_image(d, top_svg, MARGIN, MARGIN, left_w, top_h)
    view_label(d, "TOP VIEW", MARGIN + left_w / 2, MARGIN + top_h + lbl - 4)

    # Front view
    fy = MARGIN + top_h + lbl + gap
    embed_svg_as_image(d, front_svg, MARGIN, fy, left_w, bot_h)
    view_label(d, "FRONT ELEVATION", MARGIN + left_w / 2, fy + bot_h + lbl - 4)

    # Side view (right of front, same baseline)
    sx = MARGIN + left_w + gap
    embed_svg_as_image(d, side_svg, sx, fy, right_w, bot_h)
    view_label(d, "SIDE ELEVATION", sx + right_w / 2, fy + bot_h + lbl - 4)

    # Divider between front and side
    d.append(
        draw.Line(
            sx - gap // 2,
            fy - gap // 2,
            sx - gap // 2,
            fy + bot_h,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    draw_title_block(d, cfg)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


# ── Combined sheet (iso+BOM top, ortho+dims bottom) ──────────────────────────


def build_combined_sheet(
    cfg: dict,
    iso_svg: str,
    front_svg: str,
    top_svg: str,
    side_svg: str,
    out_path: str,
) -> None:
    """Single combined sheet: iso+BOM on top half, annotated ortho projection below."""
    d = draw.Drawing(SHEET_W, COMBINED_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, COMBINED_H, fill="white"))

    # ── Zone 1: iso view (left) + BOM table (right) ───────────────────────
    ISO_ZONE_H = 510
    vw, vh = 490, 490
    embed_svg_as_image(d, iso_svg, MARGIN, MARGIN + 10, vw, vh)
    view_label(d, "ISOMETRIC VIEW", MARGIN + vw / 2, MARGIN + 10 + vh + 14)

    d.append(
        draw.Line(
            MARGIN + vw + 10,
            MARGIN,
            MARGIN + vw + 10,
            MARGIN + ISO_ZONE_H,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    # Centre BOM in the right-hand column
    from components import _COL_WIDTHS as _bom_cw  # noqa: PLC0415

    bom_total_w = sum(_bom_cw)
    bom_avail = SHEET_W - MARGIN - (MARGIN + vw + 10) - 20
    bom_x = MARGIN + vw + 10 + max(10, (bom_avail - bom_total_w) / 2)
    bom_table(
        d,
        x=bom_x,
        y=MARGIN + 10,
        items=cfg["bom"],
        title="BILL OF MATERIALS  —  Sensor Mount Subassembly",
    )

    # Zone separator
    sep_y = MARGIN + ISO_ZONE_H + 8
    d.append(
        draw.Line(
            MARGIN, sep_y, SHEET_W - MARGIN, sep_y, stroke="#bbb", stroke_width=1.0
        )
    )

    # ── Zone 2: ortho views + dimension annotations ────────────────────────
    # Reserve left margin for vertical dim lines and bottom margin for
    # horizontal dim lines so annotations don't overlap view labels.
    DIM_PAD_LEFT = 58
    DIM_PAD_BTM = 40

    title_y_comb = COMBINED_H - TB_H - MARGIN - 8
    ortho_y = sep_y + 14
    ortho_avail_h = title_y_comb - ortho_y - 8
    draw_w_ortho = SHEET_W - 2 * MARGIN - DIM_PAD_LEFT
    draw_h_ortho = ortho_avail_h - DIM_PAD_BTM

    gap = 14
    lbl = 18

    top_h = int(draw_h_ortho * 0.28)
    bot_h = draw_h_ortho - top_h - gap - lbl
    left_w = int(draw_w_ortho * 0.58)
    right_w = draw_w_ortho - left_w - gap

    ox = MARGIN + DIM_PAD_LEFT
    oy = ortho_y

    # Top view
    embed_svg_as_image(d, top_svg, ox, oy, left_w, top_h)
    view_label(d, "TOP VIEW", ox + left_w / 2, oy + top_h + lbl - 4)

    # Front view
    fy = oy + top_h + lbl + gap
    embed_svg_as_image(d, front_svg, ox, fy, left_w, bot_h)
    view_label(d, "FRONT ELEVATION", ox + left_w / 2, fy + bot_h + lbl - 4)

    # Side view
    sx = ox + left_w + gap
    embed_svg_as_image(d, side_svg, sx, fy, right_w, bot_h)
    view_label(d, "SIDE ELEVATION", sx + right_w / 2, fy + bot_h + lbl - 4)

    # Divider between front and side
    d.append(
        draw.Line(
            sx - gap // 2,
            fy - gap // 2,
            sx - gap // 2,
            fy + bot_h,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    # ── Dimension annotations ──────────────────────────────────────────────
    lbr = cfg["lumber"]
    cross_in = lbr["crossbar_length_in"]  # 32"
    up_in = lbr["upright_length_in"]  # 24"
    pipe_od = cfg["pipe"]["od_in"]  # 4.0"
    pipe_len = cfg["pipe"]["length_in"]  # 24"
    w_in = lbr["actual_width_in"]  # 1.5"
    d_in = lbr["actual_depth_in"]  # 3.5"
    brace_in = lbr["brace_top_edge_in"]  # 11"
    brace_deg = lbr["brace_angle_deg"]  # 45°
    h_offsets = cfg["holes"]["crossbar_clamp"]["offsets_from_end_in"]  # [3, 6]
    pipe_depths = cfg["holes"]["upright_pipe_screw"]["depths_from_top_in"]  # [6, 12]

    # ── Front elevation dims ───────────────────────────────────────────────
    # 1. Crossbar total length — below front view
    h_dim_y = fy + bot_h + lbl + 14
    dim_h(d, ox, ox + left_w, h_dim_y, f'{cross_in:.0f}"', ext=9, tick=3)

    # 2. Upright length — vertical left of front view
    dim_v(d, ox - 16, fy, fy + bot_h, f'{up_in:.0f}"', ext=10, tick=3)

    # 3. Pipe overlap (18" clamp zone) — second vertical dim further left
    overlap_frac = 18 / up_in
    dim_v(d, ox - 34, fy, fy + int(bot_h * overlap_frac), '18"', ext=10, tick=3)

    # 4. Crossbar width (1.5") — small vertical dim on the front view crossbar band
    crossbar_band_frac = w_in / (up_in + w_in)
    cb_top_y = fy + bot_h
    cb_bot_y = fy + bot_h - int(bot_h * crossbar_band_frac)
    dim_v(d, ox + left_w + 6, cb_bot_y, cb_top_y, f'{w_in}"', ext=8, tick=2)

    # 5. Hole positions on crossbar — dim along bottom of front view
    # Crossbar spans ox..ox+left_w in the drawing. Holes at 3" and 6" from each end.
    # Scale factor: left_w pixels = cross_in inches
    px_per_in = left_w / cross_in
    hole_dim_y = h_dim_y + 20
    # Left end holes
    x_hole_3_left = ox + h_offsets[0] * px_per_in
    x_hole_6_left = ox + h_offsets[1] * px_per_in
    dim_h(d, ox, x_hole_3_left, hole_dim_y, f'{h_offsets[0]:.0f}"', ext=8, tick=2)
    dim_h(d, ox, x_hole_6_left, hole_dim_y + 16, f'{h_offsets[1]:.0f}"', ext=8, tick=2)
    # Label
    d.append(
        draw.Text(
            "CLG BOLT HOLES ×4",
            7,
            ox + left_w * 0.15,
            hole_dim_y + 30,
            text_anchor="middle",
            font_family=FONT,
            fill=DIM_COLOUR,
        )
    )

    # 6. Brace callout
    leader(
        d,
        ox + left_w * 0.12,
        fy + bot_h * 0.08,
        ox + left_w * 0.04,
        fy - 14,
        f'BRACE 2\u00d7  {brace_in:.0f}"  {brace_deg:.0f}\u00b0',
        anchor="start",
    )

    # ── Top view dims ──────────────────────────────────────────────────────
    # 7. Crossbar depth (3.5") — vertical dim on top view
    dim_v(d, ox - 16, oy, oy + top_h, f'{d_in}"', ext=10, tick=2)

    # 8. Pipe OD — leader from centre of top view
    leader(
        d,
        ox + left_w * 0.50,
        oy + top_h * 0.50,
        ox + left_w * 0.68,
        oy + top_h * 0.26,
        f'\u00d8{pipe_od:.0f}" OD',
        anchor="start",
    )

    # ── Side elevation dims ────────────────────────────────────────────────
    # 9. Pipe screw hole depths from top
    leader(
        d,
        sx + right_w * 0.52,
        fy + bot_h * 0.20,
        sx + right_w * 0.75,
        fy + bot_h * 0.12,
        f'PIPE SCREWS: {pipe_depths[0]:.0f}" + {pipe_depths[1]:.0f}" FROM TOP',
        anchor="start",
    )

    # 10. Lumber section callout
    leader(
        d,
        sx + right_w * 0.35,
        fy + bot_h * 0.42,
        sx + right_w * 0.82,
        fy + bot_h * 0.32,
        f'2\u00d74 ACT {w_in:.1f}"\u00d7{d_in:.1f}"',
        anchor="start",
    )

    # 11. Pipe length — vertical dim right of side view
    pipe_frac = pipe_len / (up_in + w_in)
    dim_v(
        d,
        sx + right_w + 14,
        fy,
        fy + int(bot_h * pipe_frac),
        f'\u00d8{pipe_od:.0f}" PIPE\n{pipe_len:.0f}"',
        ext=14,
        tick=2,
    )

    # 12. Clamp hole spacing — small horizontal dim on side view crossbar
    # Crossbar occupies the bottom fraction of the side elevation
    cb_frac = w_in / (up_in + w_in)
    cb_side_h = int(bot_h * cb_frac)
    cb_side_y = fy + bot_h - cb_side_h
    clamp_span_px = (h_offsets[1] - h_offsets[0]) * px_per_in
    dim_h(
        d,
        sx + right_w * 0.2,
        sx + right_w * 0.2 + clamp_span_px,
        cb_side_y - 8,
        f'{h_offsets[1] - h_offsets[0]:.0f}" CLAMP SLOT',
        ext=7,
        tick=2,
    )

    draw_title_block(d, cfg, COMBINED_H)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


# ── Entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build rack-mount SVG sheet drawings from 3D model views"
    )
    parser.add_argument("--config", default="rack.json")
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    build_dir = script_dir / "build"
    output_dir = script_dir / "output"
    build_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    config_path = (
        Path(args.config) if os.path.isabs(args.config) else script_dir / args.config
    )

    with open(config_path) as f:
        cfg = json.load(f)

    # ── Step 1: generate 3D model views into build/ ───────────────────────
    print("Building 3D model views…")
    from model import main as model_main  # noqa: PLC0415 (intentional late import)

    model_main(str(config_path), str(build_dir))

    front_3d = str(build_dir / "rack_front.svg")
    side_3d = str(build_dir / "rack_side.svg")
    top_3d = str(build_dir / "rack_top.svg")
    iso_3d = str(build_dir / "rack_isometric.svg")

    # ── Step 2: assemble combined sheet SVG into build/ ───────────────────
    print("Assembling drawing sheet…")
    combined_svg = build_dir / "sheet_combined.svg"
    build_combined_sheet(cfg, iso_3d, front_3d, top_3d, side_3d, str(combined_svg))

    # ── Step 3: rasterise to output/ and web image directories ────────────
    rsvg = shutil.which("rsvg-convert")
    if rsvg:
        repo_root = script_dir.parent.parent
        # Canonical output checked into git
        local_png = output_dir / "rack-drawing-iso-bom.png"
        subprocess.run(
            [rsvg, "-w", "1200", str(combined_svg), "-o", str(local_png)],
            check=True,
        )
        print(f"  ✓ {local_png.relative_to(script_dir)}")

        # Copy to web + docs image directories
        web_img_dirs = [
            repo_root / "public_html" / "src" / "images",
            repo_root / "docs" / "images",
        ]
        for img_dir in web_img_dirs:
            dest = img_dir / "rack-drawing-iso-bom.png"
            shutil.copy2(local_png, dest)
            print(f"  ✓ {dest.relative_to(repo_root)}")
    else:
        print("  ⚠ rsvg-convert not found — skipping PNG export")
        print("    Install with: brew install librsvg")

    print("Done.")


if __name__ == "__main__":
    main()
