#!/usr/bin/env python3
"""
draw_rack.py — Rack-mount engineering drawing sheets.

Directory layout
───────────────
  build/     Intermediate 3D-view SVGs (one per projection).
             Contents are gitignored; directory is kept with .gitkeep.
  output/    Final output: combined drawing sheet PNG.
             Checked into git so the guide can reference it directly.

Both directories are created automatically if absent.

The 3D view SVGs are generated by model.py (build123d / OCCT).
The BOM table, dimension annotations, and title block are overlaid via
drawsvg, and the finished SVG is rasterised to PNG via rsvg-convert.

Usage:
    python draw_rack.py
    python draw_rack.py --config rack.json
"""

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

import drawsvg as draw

from components import (
    bom_table,
    FONT,
    FS_LABEL,
    FS_HEAD,
)

# ── Sheet geometry ────────────────────────────────────────────────────────────

SHEET_W = 1200
SHEET_H = 850
COMBINED_H = 1600
MARGIN = 28

# ── SVG viewport embed ────────────────────────────────────────────────────────


def embed_svg_as_image(
    d: draw.Drawing,
    svg_path: str,
    x: float,
    y: float,
    w: float,
    h: float,
) -> None:
    """Embed an SVG file as a base64-encoded <image> element (self-contained output)."""
    import base64

    with open(svg_path, "rb") as f:
        data = base64.b64encode(f.read()).decode("ascii")
    uri = f"data:image/svg+xml;base64,{data}"
    d.append(draw.Image(x, y, w, h, uri, embed=False))


# ── Title block ───────────────────────────────────────────────────────────────

TB_W = 380  # title block width
TB_H = 96  # title block height


def draw_title_block(d: draw.Drawing, cfg: dict, sheet_h: float = SHEET_H) -> None:
    """Standard lower-right title block."""
    tb_x = SHEET_W - MARGIN - TB_W
    tb_y = sheet_h - MARGIN - TB_H

    # Background + outer border
    d.append(
        draw.Rectangle(
            tb_x,
            tb_y,
            TB_W,
            TB_H,
            fill="white",
            stroke="#333",
            stroke_width=1.0,
        )
    )

    # ── Row heights from top: title(28) | row1(28) | row2(20) | row3(20) ──
    r0_h, r1_h, r2_h, r3_h = 28, 24, 22, 22
    r0_y = tb_y
    r1_y = r0_y + r0_h
    r2_y = r1_y + r1_h
    r3_y = r2_y + r2_h

    # Row dividers
    for ry in (r1_y, r2_y, r3_y):
        d.append(draw.Line(tb_x, ry, tb_x + TB_W, ry, stroke="#333", stroke_width=0.5))

    # Row 0 — drawing title (full width, bold centre)
    d.append(
        draw.Text(
            "velocity.report Radar Mount",
            FS_HEAD,
            tb_x + TB_W / 2,
            r0_y + r0_h / 2,
            text_anchor="middle",
            dominant_baseline="middle",
            font_family=FONT,
            fill="#1a1a2e",
            font_weight="bold",
        )
    )

    # Rows 1-3: two-column cells (label top-left, value centred)
    def cell(
        label: str,
        value: str,
        cx: float,
        cy: float,
        cw: float,
        ch: float,
        bold: bool = False,
    ) -> None:
        d.append(
            draw.Text(
                label,
                6,
                cx + 3,
                cy + 8,
                dominant_baseline="hanging",
                font_family=FONT,
                fill="#888",
            )
        )
        d.append(
            draw.Text(
                value,
                FS_LABEL if not bold else FS_LABEL + 1,
                cx + cw / 2,
                cy + ch / 2 + 3,
                text_anchor="middle",
                dominant_baseline="middle",
                font_family=FONT,
                fill="#1a1a2e",
                font_weight="bold" if bold else "normal",
            )
        )

    # Row 1: FIRM (60%) | DRAWN BY (40%)
    col_a = int(TB_W * 0.60)
    d.append(
        draw.Line(
            tb_x + col_a, r1_y, tb_x + col_a, r2_y, stroke="#333", stroke_width=0.4
        )
    )
    cell("FIRM", "Banshee Inc", tb_x, r1_y, col_a, r1_h, bold=True)
    cell("DRAWN BY", "D. Dolphin", tb_x + col_a, r1_y, TB_W - col_a, r1_h)

    # Row 2: DATE (40%) | REV (30%) | SCALE (30%)
    col_b, col_c = int(TB_W * 0.40), int(TB_W * 0.30)
    d.append(
        draw.Line(
            tb_x + col_b, r2_y, tb_x + col_b, r3_y, stroke="#333", stroke_width=0.4
        )
    )
    d.append(
        draw.Line(
            tb_x + col_b + col_c,
            r2_y,
            tb_x + col_b + col_c,
            r3_y,
            stroke="#333",
            stroke_width=0.4,
        )
    )
    cell("DATE", "2026-04-15", tb_x, r2_y, col_b, r2_h)
    cell(
        "REV",
        f"Rev {cfg.get('revision', 'A')}",
        tb_x + col_b,
        r2_y,
        col_c,
        r2_h,
        bold=True,
    )
    cell("SCALE", "1:10", tb_x + col_b + col_c, r2_y, TB_W - col_b - col_c, r2_h)

    # Row 3: PROJECTION (full width)
    cell("PROJECTION", "THIRD-ANGLE", tb_x, r3_y, TB_W, r3_h)

    # Sheet border
    d.append(
        draw.Rectangle(
            MARGIN,
            MARGIN,
            SHEET_W - 2 * MARGIN,
            sheet_h - 2 * MARGIN,
            fill="none",
            stroke="#333",
            stroke_width=1.5,
        )
    )


def view_label(d: draw.Drawing, text: str, x: float, y: float) -> None:
    pass  # labels removed


# ── Sheet builders ────────────────────────────────────────────────────────────


def build_iso_bom_sheet(cfg: dict, iso_svg: str, out_path: str) -> None:
    """Sheet 1: isometric view + BOM table + title block."""
    d = draw.Drawing(SHEET_W, SHEET_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, SHEET_H, fill="white"))

    vw, vh = 620, 460
    embed_svg_as_image(d, iso_svg, MARGIN, MARGIN + 10, vw, vh)
    view_label(d, "ISOMETRIC VIEW", MARGIN + vw / 2, MARGIN + 10 + vh + 14)

    d.append(
        draw.Line(
            MARGIN + vw + 10,
            MARGIN,
            MARGIN + vw + 10,
            SHEET_H - TB_H - MARGIN - 10,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    bom_table(
        d,
        x=MARGIN + vw + 22,
        y=MARGIN + 10,
        items=cfg["bom"],
        title="BILL OF MATERIALS  —  Sensor Mount Subassembly",
    )

    draw_title_block(d, cfg)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


def build_ortho_sheet(
    cfg: dict,
    front_svg: str,
    top_svg: str,
    side_svg: str,
    out_path: str,
) -> None:
    """Sheet 2: third-angle orthographic projection (front + top + side)."""
    d = draw.Drawing(SHEET_W, SHEET_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, SHEET_H, fill="white"))

    draw_w = SHEET_W - 2 * MARGIN
    draw_h = SHEET_H - 2 * MARGIN - 14  # small bottom gap above title block
    gap = 14
    lbl = 18

    # Third-angle layout:
    #     [  TOP VIEW  ]
    #     [FRONT] [SIDE]
    top_h = int(draw_h * 0.28)
    bot_h = draw_h - top_h - gap - lbl
    left_w = int(draw_w * 0.58)
    right_w = draw_w - left_w - gap

    # Top view
    embed_svg_as_image(d, top_svg, MARGIN, MARGIN, left_w, top_h)
    view_label(d, "TOP VIEW", MARGIN + left_w / 2, MARGIN + top_h + lbl - 4)

    # Front view
    fy = MARGIN + top_h + lbl + gap
    embed_svg_as_image(d, front_svg, MARGIN, fy, left_w, bot_h)
    view_label(d, "FRONT ELEVATION", MARGIN + left_w / 2, fy + bot_h + lbl - 4)

    # Side view (right of front, same baseline)
    sx = MARGIN + left_w + gap
    embed_svg_as_image(d, side_svg, sx, fy, right_w, bot_h)
    view_label(d, "SIDE ELEVATION", sx + right_w / 2, fy + bot_h + lbl - 4)

    # Divider between front and side
    d.append(
        draw.Line(
            sx - gap // 2,
            fy - gap // 2,
            sx - gap // 2,
            fy + bot_h,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    draw_title_block(d, cfg)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


# ── Combined sheet (iso+BOM top, ortho+dims bottom) ──────────────────────────


def build_combined_sheet(
    cfg: dict,
    iso_svg: str,
    front_svg: str,
    top_svg: str,
    side_svg: str,
    out_path: str,
) -> None:
    """Combined sheet: ortho top (with dims), iso lower-left, BOM lower-right."""
    d = draw.Drawing(SHEET_W, COMBINED_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, COMBINED_H, fill="white"))

    # ── Geometry ───────────────────────────────────────────────────────────
    ORTHO_H = 960  # ortho zone height
    BOT_Y = MARGIN + ORTHO_H + 10
    BOT_H = COMBINED_H - BOT_Y - MARGIN

    DIM_PAD_LEFT = 58
    DIM_PAD_BTM = 50
    draw_w_ortho = SHEET_W - 2 * MARGIN - DIM_PAD_LEFT
    draw_h_ortho = ORTHO_H - DIM_PAD_BTM
    gap = 14

    top_h = int(draw_h_ortho * 0.28)
    bot_h = draw_h_ortho - top_h - gap
    left_w = int(draw_w_ortho * 0.58)
    right_w = draw_w_ortho - left_w - gap

    ox = MARGIN + DIM_PAD_LEFT
    oy = MARGIN + 6
    fy = oy + top_h + gap
    sx = ox + left_w + gap

    # ── Zone 1 (top): ortho views ─────────────────────────────────────────
    embed_svg_as_image(d, top_svg, ox, oy, left_w, top_h)
    embed_svg_as_image(d, front_svg, ox, fy, left_w, bot_h)
    embed_svg_as_image(d, side_svg, sx, fy, right_w, bot_h)
    d.append(
        draw.Line(
            sx - gap // 2,
            fy - gap // 2,
            sx - gap // 2,
            fy + bot_h,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    # ── Zone separator ─────────────────────────────────────────────────────
    d.append(
        draw.Line(
            MARGIN, BOT_Y, SHEET_W - MARGIN, BOT_Y, stroke="#bbb", stroke_width=1.0
        )
    )

    # ── Zone 2 (bottom-left): isometric view ──────────────────────────────
    ISO_W = int((SHEET_W - 2 * MARGIN) * 0.52)
    embed_svg_as_image(d, iso_svg, MARGIN, BOT_Y + 6, ISO_W, BOT_H - 6)

    div_x = MARGIN + ISO_W + 10
    d.append(
        draw.Line(
            div_x, BOT_Y, div_x, COMBINED_H - MARGIN, stroke="#bbb", stroke_width=0.8
        )
    )

    # ── Zone 2 (bottom-right): BOM centred ────────────────────────────────
    from components import _COL_WIDTHS as _bom_cw  # noqa: PLC0415

    bom_total_w = sum(_bom_cw)
    bom_avail = SHEET_W - MARGIN - div_x - 10
    bom_x = div_x + 10 + max(0, (bom_avail - bom_total_w) / 2)
    n_rows = len(cfg["bom"])
    bom_total_h = 28 + 26 + n_rows * 26 + 28  # title + header + rows + total
    bom_y = BOT_Y + max(6, (BOT_H - bom_total_h) / 2)
    bom_table(
        d,
        x=bom_x,
        y=bom_y,
        items=cfg["bom"],
        title="BILL OF MATERIALS  —  Sensor Mount Subassembly",
    )

    draw_title_block(d, cfg, COMBINED_H)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


# ── Entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build rack-mount SVG sheet drawings from 3D model views"
    )
    parser.add_argument("--config", default="rack.json")
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    build_dir = script_dir / "build"
    output_dir = script_dir / "output"
    build_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    config_path = (
        Path(args.config) if os.path.isabs(args.config) else script_dir / args.config
    )

    with open(config_path) as f:
        cfg = json.load(f)

    # ── Step 1: generate 3D model views into build/ ───────────────────────
    print("Building 3D model views…")
    from model import main as model_main  # noqa: PLC0415 (intentional late import)

    model_main(str(config_path), str(build_dir))

    front_3d = str(build_dir / "rack_front.svg")
    side_3d = str(build_dir / "rack_side.svg")
    top_3d = str(build_dir / "rack_top.svg")
    iso_3d = str(build_dir / "rack_isometric.svg")

    # ── Step 2: assemble combined sheet SVG into build/ ───────────────────
    print("Assembling drawing sheet…")
    combined_svg = build_dir / "sheet_combined.svg"
    build_combined_sheet(cfg, iso_3d, front_3d, top_3d, side_3d, str(combined_svg))

    # ── Step 3: rasterise to output/ and web image directories ────────────
    rsvg = shutil.which("rsvg-convert")
    if rsvg:
        repo_root = script_dir.parent.parent
        # Canonical output checked into git
        local_png = output_dir / "rack-drawing-iso-bom.png"
        subprocess.run(
            [rsvg, "-w", "1200", str(combined_svg), "-o", str(local_png)],
            check=True,
        )
        print(f"  ✓ {local_png.relative_to(script_dir)}")

        # Copy to web + docs image directories
        web_img_dirs = [
            repo_root / "public_html" / "src" / "images",
            repo_root / "docs" / "images",
        ]
        for img_dir in web_img_dirs:
            dest = img_dir / "rack-drawing-iso-bom.png"
            shutil.copy2(local_png, dest)
            print(f"  ✓ {dest.relative_to(repo_root)}")
    else:
        print("  ⚠ rsvg-convert not found — skipping PNG export")
        print("    Install with: brew install librsvg")

    print("Done.")


if __name__ == "__main__":
    main()
