#!/usr/bin/env python3
"""
draw_rack.py — Rack-mount engineering drawing sheets.

Produces two output SVGs:
  sheet_iso_bom.svg  — Isometric view with BOM table + title block
  sheet_ortho.svg    — Third-angle orthographic (front + top + side) + title block

The 3D view SVGs are generated by model.py (build123d / OCCT).
The BOM table and title block are overlaid via drawsvg.

Usage:
    python draw_rack.py
    python draw_rack.py --config rack.json --out-dir .
"""

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

import drawsvg as draw

from components import (
    bom_table,
    dim_h,
    dim_v,
    leader,
    DIM_COLOUR,
    FONT,
    FS_LABEL,
    FS_HEAD,
)

# ── Sheet geometry ────────────────────────────────────────────────────────────

SHEET_W = 1200
SHEET_H = 850
COMBINED_H = 1600
MARGIN = 28
TITLE_H = 62


# ── SVG viewport embed ────────────────────────────────────────────────────────


def embed_svg_as_image(
    d: draw.Drawing,
    svg_path: str,
    x: float,
    y: float,
    w: float,
    h: float,
) -> None:
    """Embed an SVG file as a base64-encoded <image> element (self-contained output)."""
    import base64

    with open(svg_path, "rb") as f:
        data = base64.b64encode(f.read()).decode("ascii")
    uri = f"data:image/svg+xml;base64,{data}"
    d.append(draw.Image(x, y, w, h, uri, embed=False))


# ── Title block ───────────────────────────────────────────────────────────────


def draw_title_block(
    d: draw.Drawing, cfg: dict, view_name: str, sheet_h: float = SHEET_H
) -> None:
    tb_y = sheet_h - TITLE_H - MARGIN
    tb_h = TITLE_H
    tb_w = SHEET_W - 2 * MARGIN

    d.append(
        draw.Rectangle(
            MARGIN, tb_y, tb_w, tb_h, fill="white", stroke="#333", stroke_width=1.0
        )
    )

    divs = [400, 200, 140]
    cx = MARGIN
    for dv in divs:
        cx += dv
        d.append(draw.Line(cx, tb_y, cx, tb_y + tb_h, stroke="#333", stroke_width=0.5))

    d.append(
        draw.Text(
            cfg.get("title", "Rack Mount Drawing"),
            FS_HEAD,
            MARGIN + 200,
            tb_y + 18,
            text_anchor="middle",
            dominant_baseline="middle",
            font_family=FONT,
            fill="#1a1a2e",
            font_weight="bold",
        )
    )
    d.append(
        draw.Text(
            f"View: {view_name}  —  velocity.report Sensor Mount",
            FS_LABEL,
            MARGIN + 200,
            tb_y + 40,
            text_anchor="middle",
            font_family=FONT,
            fill="#555",
        )
    )

    d.append(
        draw.Text(
            f"Rev {cfg.get('revision', 'A')}",
            FS_LABEL,
            MARGIN + 400 + 100,
            tb_y + 22,
            text_anchor="middle",
            dominant_baseline="middle",
            font_family=FONT,
            fill="#1a1a2e",
            font_weight="bold",
        )
    )

    notes = [
        "All dims: inches unless noted.",
        '2×4 nominal = 1.5"×3.5" actual.',
        "Qty 2 mounts required.",
    ]
    nx = MARGIN + 400 + 200 + 70
    for i, note in enumerate(notes):
        d.append(
            draw.Text(note, 7, nx, tb_y + 10 + i * 17, font_family=FONT, fill="#333")
        )

    d.append(
        draw.Text(
            "THIRD-ANGLE PROJECTION",
            FS_LABEL - 1,
            SHEET_W - MARGIN - 60,
            tb_y + 22,
            text_anchor="middle",
            font_family=FONT,
            fill="#555",
        )
    )
    d.append(
        draw.Text(
            "SCALE: 1:10 approx.",
            FS_LABEL - 1,
            SHEET_W - MARGIN - 60,
            tb_y + 40,
            text_anchor="middle",
            font_family=FONT,
            fill="#555",
        )
    )

    d.append(
        draw.Rectangle(
            MARGIN,
            MARGIN,
            SHEET_W - 2 * MARGIN,
            sheet_h - 2 * MARGIN,
            fill="none",
            stroke="#333",
            stroke_width=1.5,
        )
    )


def view_label(d: draw.Drawing, text: str, x: float, y: float) -> None:
    d.append(
        draw.Text(
            text,
            FS_LABEL,
            x,
            y,
            text_anchor="middle",
            font_family=FONT,
            fill=DIM_COLOUR,
            font_weight="bold",
        )
    )


# ── Sheet builders ────────────────────────────────────────────────────────────


def build_iso_bom_sheet(cfg: dict, iso_svg: str, out_path: str) -> None:
    """Sheet 1: isometric view + BOM table + title block."""
    d = draw.Drawing(SHEET_W, SHEET_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, SHEET_H, fill="white"))

    vw, vh = 620, 460
    embed_svg_as_image(d, iso_svg, MARGIN, MARGIN + 10, vw, vh)
    view_label(d, "ISOMETRIC VIEW", MARGIN + vw / 2, MARGIN + 10 + vh + 14)

    d.append(
        draw.Line(
            MARGIN + vw + 10,
            MARGIN,
            MARGIN + vw + 10,
            SHEET_H - TITLE_H - MARGIN - 10,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    bom_table(
        d,
        x=MARGIN + vw + 22,
        y=MARGIN + 10,
        items=cfg["bom"],
        title="BILL OF MATERIALS  —  Sensor Mount Subassembly",
    )

    draw_title_block(d, cfg, "ISOMETRIC VIEW")
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


def build_ortho_sheet(
    cfg: dict,
    front_svg: str,
    top_svg: str,
    side_svg: str,
    out_path: str,
) -> None:
    """Sheet 2: third-angle orthographic projection (front + top + side)."""
    d = draw.Drawing(SHEET_W, SHEET_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, SHEET_H, fill="white"))

    draw_w = SHEET_W - 2 * MARGIN
    draw_h = SHEET_H - TITLE_H - 2 * MARGIN
    gap = 14
    lbl = 18

    # Third-angle layout:
    #     [  TOP VIEW  ]
    #     [FRONT] [SIDE]
    top_h = int(draw_h * 0.28)
    bot_h = draw_h - top_h - gap - lbl
    left_w = int(draw_w * 0.58)
    right_w = draw_w - left_w - gap

    # Top view
    embed_svg_as_image(d, top_svg, MARGIN, MARGIN, left_w, top_h)
    view_label(d, "TOP VIEW", MARGIN + left_w / 2, MARGIN + top_h + lbl - 4)

    # Front view
    fy = MARGIN + top_h + lbl + gap
    embed_svg_as_image(d, front_svg, MARGIN, fy, left_w, bot_h)
    view_label(d, "FRONT ELEVATION", MARGIN + left_w / 2, fy + bot_h + lbl - 4)

    # Side view (right of front, same baseline)
    sx = MARGIN + left_w + gap
    embed_svg_as_image(d, side_svg, sx, fy, right_w, bot_h)
    view_label(d, "SIDE ELEVATION", sx + right_w / 2, fy + bot_h + lbl - 4)

    # Divider between front and side
    d.append(
        draw.Line(
            sx - gap // 2,
            fy - gap // 2,
            sx - gap // 2,
            fy + bot_h,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    draw_title_block(d, cfg, "ORTHOGRAPHIC PROJECTION")
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


# ── Combined sheet (iso+BOM top, ortho+dims bottom) ──────────────────────────


def build_combined_sheet(
    cfg: dict,
    iso_svg: str,
    front_svg: str,
    top_svg: str,
    side_svg: str,
    out_path: str,
) -> None:
    """Single combined sheet: iso+BOM on top half, annotated ortho projection below."""
    d = draw.Drawing(SHEET_W, COMBINED_H)
    d.append(draw.Rectangle(0, 0, SHEET_W, COMBINED_H, fill="white"))

    # ── Zone 1: iso view (left) + BOM table (right) ───────────────────────
    ISO_ZONE_H = 510
    vw, vh = 540, 490
    embed_svg_as_image(d, iso_svg, MARGIN, MARGIN + 10, vw, vh)
    view_label(d, "ISOMETRIC VIEW", MARGIN + vw / 2, MARGIN + 10 + vh + 14)

    d.append(
        draw.Line(
            MARGIN + vw + 10,
            MARGIN,
            MARGIN + vw + 10,
            MARGIN + ISO_ZONE_H,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )
    bom_table(
        d,
        x=MARGIN + vw + 22,
        y=MARGIN + 10,
        items=cfg["bom"],
        title="BILL OF MATERIALS  —  Sensor Mount Subassembly",
    )

    # Zone separator
    sep_y = MARGIN + ISO_ZONE_H + 8
    d.append(
        draw.Line(
            MARGIN, sep_y, SHEET_W - MARGIN, sep_y, stroke="#bbb", stroke_width=1.0
        )
    )

    # ── Zone 2: ortho views + dimension annotations ────────────────────────
    # Reserve left margin for vertical dim lines and bottom margin for
    # horizontal dim lines so annotations don't overlap view labels.
    DIM_PAD_LEFT = 58
    DIM_PAD_BTM = 40

    title_y_comb = COMBINED_H - TITLE_H - MARGIN
    ortho_y = sep_y + 14
    ortho_avail_h = title_y_comb - ortho_y - 8
    draw_w_ortho = SHEET_W - 2 * MARGIN - DIM_PAD_LEFT
    draw_h_ortho = ortho_avail_h - DIM_PAD_BTM

    gap = 14
    lbl = 18

    top_h = int(draw_h_ortho * 0.28)
    bot_h = draw_h_ortho - top_h - gap - lbl
    left_w = int(draw_w_ortho * 0.58)
    right_w = draw_w_ortho - left_w - gap

    ox = MARGIN + DIM_PAD_LEFT
    oy = ortho_y

    # Top view
    embed_svg_as_image(d, top_svg, ox, oy, left_w, top_h)
    view_label(d, "TOP VIEW", ox + left_w / 2, oy + top_h + lbl - 4)

    # Front view
    fy = oy + top_h + lbl + gap
    embed_svg_as_image(d, front_svg, ox, fy, left_w, bot_h)
    view_label(d, "FRONT ELEVATION", ox + left_w / 2, fy + bot_h + lbl - 4)

    # Side view
    sx = ox + left_w + gap
    embed_svg_as_image(d, side_svg, sx, fy, right_w, bot_h)
    view_label(d, "SIDE ELEVATION", sx + right_w / 2, fy + bot_h + lbl - 4)

    # Divider between front and side
    d.append(
        draw.Line(
            sx - gap // 2,
            fy - gap // 2,
            sx - gap // 2,
            fy + bot_h,
            stroke="#bbb",
            stroke_width=0.8,
        )
    )

    # ── Dimension annotations ──────────────────────────────────────────────
    lbr = cfg["lumber"]
    cross_in = lbr["crossbar_length_in"]  # 32"
    up_in = lbr["upright_length_in"]  # 24"
    pipe_od = cfg["pipe"]["od_in"]  # 4.0"

    # 1. Crossbar width — horizontal dim below the front-view label
    h_dim_y = fy + bot_h + lbl + 14
    dim_h(d, ox, ox + left_w, h_dim_y, f'{cross_in:.0f}"', ext=9, tick=3)

    # 2. Upright length — vertical dim to the left of the front view
    dim_v(d, ox - 16, fy, fy + bot_h, f'{up_in:.0f}"', ext=10, tick=3)

    # 3. Pipe OD — leader from pipe circle in the top view.
    #    Top view is shallow and wide; the pipe appears as a circle at the
    #    centre (X=0 symmetric, pipe overlaps the upright at centre).
    leader(
        d,
        ox + left_w * 0.50,
        oy + top_h * 0.50,
        ox + left_w * 0.68,
        oy + top_h * 0.26,
        f'\u00d8{pipe_od:.0f}" OD',
        anchor="start",
    )

    # 4. Clamp-hole zone — callout on the side view.
    #    Two pilot holes drilled through the pipe where it overlaps the
    #    upright, approximately 6" and 12" from top of upright.
    leader(
        d,
        sx + right_w * 0.52,
        fy + bot_h * 0.20,
        sx + right_w * 0.72,
        fy + bot_h * 0.12,
        'HOLES: 6" + 12" FROM TOP',
        anchor="start",
    )

    # 5. Pipe overlap — second vertical dim showing 18" clamped zone on front view.
    #    PIPE_OVERLAP = 18" means the pipe extends 18" down from the top of the
    #    upright (= 24" total upright, so 18/24 = 75% of the front elevation height).
    overlap_frac = 18 / up_in  # 18" / 24" = 0.75
    dim_v(d, ox - 34, fy, fy + int(bot_h * overlap_frac), '18"', ext=10, tick=3)

    # 6. Brace callout — leader pointing to the brace area (upper-left of front view).
    leader(
        d,
        ox + left_w * 0.12,
        fy + bot_h * 0.08,
        ox + left_w * 0.04,
        fy - 14,
        f'BRACE 2\u00d7 \u00b7 {lbr["brace_top_edge_in"]:.0f}" \u00b7 {lbr["brace_angle_deg"]:.0f}\u00b0',
        anchor="start",
    )

    # 7. Lumber section callout — side elevation shows the 3.5" depth of the 2×4.
    leader(
        d,
        sx + right_w * 0.35,
        fy + bot_h * 0.42,
        sx + right_w * 0.82,
        fy + bot_h * 0.32,
        f'2\u00d74 ACT {lbr["actual_width_in"]:.1f}"\u00d7{lbr["actual_depth_in"]:.1f}"',
        anchor="start",
    )

    draw_title_block(d, cfg, "ISOMETRIC + ORTHOGRAPHIC PROJECTION", COMBINED_H)
    d.save_svg(out_path)
    print(f"Saved: {out_path}")


# ── Entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build rack-mount SVG sheet drawings from 3D model views"
    )
    parser.add_argument("--config", default="rack.json")
    parser.add_argument("--out-dir", default=None)
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    out_dir = Path(args.out_dir) if args.out_dir else script_dir
    config_path = (
        Path(args.config) if os.path.isabs(args.config) else script_dir / args.config
    )

    with open(config_path) as f:
        cfg = json.load(f)

    # ── Step 1: generate 3D model views ──────────────────────────────────
    print("Building 3D model views…")
    from model import main as model_main  # noqa: PLC0415 (intentional late import)

    model_main(str(config_path), str(out_dir))

    front_3d = str(out_dir / "rack_front.svg")
    side_3d = str(out_dir / "rack_side.svg")
    top_3d = str(out_dir / "rack_top.svg")
    iso_3d = str(out_dir / "rack_isometric.svg")

    # ── Step 2: assemble sheets ───────────────────────────────────────────
    print("Assembling drawing sheets…")
    combined_svg = out_dir / "sheet_combined.svg"
    build_combined_sheet(cfg, iso_3d, front_3d, top_3d, side_3d, str(combined_svg))

    # ── Step 3: rasterise sheets to PNG for web use ───────────────────────
    rsvg = shutil.which("rsvg-convert")
    if rsvg:
        repo_root = script_dir.parent.parent
        img_dirs = [
            repo_root / "public_html" / "src" / "images",
            repo_root / "docs" / "images",
        ]
        pairs = [
            (combined_svg, "rack-drawing-iso-bom.png"),
        ]
        for svg_path, png_name in pairs:
            for img_dir in img_dirs:
                png_path = img_dir / png_name
                subprocess.run(
                    [rsvg, "-w", "1200", str(svg_path), "-o", str(png_path)],
                    check=True,
                )
                print(f"  ✓ {png_path.relative_to(repo_root)}")
    else:
        print("  ⚠ rsvg-convert not found — skipping PNG export")
        print("    Install with: brew install librsvg")

    print("Done.")


if __name__ == "__main__":
    main()
