// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: features.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Revisioned feature proposals over existing annotation-pack evidence.
/// This is an annotation document, NOT a VRLOG observation or display frame.
/// Field numbers are permanent. Zero sample/point indices are valid; absent
/// anchors stay absent. Legacy pack references do not claim retained IDs.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Velocity_Recording_V1_FeatureGeometry: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknown // = 0
  case edge // = 1
  case corner // = 2
  case patch // = 3
  case protrusion // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .edge
    case 2: self = .corner
    case 3: self = .patch
    case 4: self = .protrusion
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .edge: return 1
    case .corner: return 2
    case .patch: return 3
    case .protrusion: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Velocity_Recording_V1_FeatureGeometry] = [
    .unknown,
    .edge,
    .corner,
    .patch,
    .protrusion,
  ]

}

enum Velocity_Recording_V1_FeatureDecision: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0

  /// Accepted as an operator's feature proposal, never physical-reference truth.
  case acceptedProposal // = 1
  case rejected // = 2
  case missing // = 3
  case occluded // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .acceptedProposal
    case 2: self = .rejected
    case 3: self = .missing
    case 4: self = .occluded
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .acceptedProposal: return 1
    case .rejected: return 2
    case .missing: return 3
    case .occluded: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Velocity_Recording_V1_FeatureDecision] = [
    .unspecified,
    .acceptedProposal,
    .rejected,
    .missing,
    .occluded,
  ]

}

struct Velocity_Recording_V1_FeatureSphere: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var xM: Double = 0

  var yM: Double = 0

  var zM: Double = 0

  var radiusM: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Velocity_Recording_V1_FeatureObservation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sampleID: UInt32 {
    get {return _storage._sampleID}
    set {_uniqueStorage()._sampleID = newValue}
  }

  var timestampNs: Int64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  var sourceOrdinal: UInt32 {
    get {return _storage._sourceOrdinal}
    set {_uniqueStorage()._sourceOrdinal = newValue}
  }

  /// Exact indices in this pack sample only. Different features may overlap.
  var pointIndices: [UInt32] {
    get {return _storage._pointIndices}
    set {_uniqueStorage()._pointIndices = newValue}
  }

  var uncertainIndices: [UInt32] {
    get {return _storage._uncertainIndices}
    set {_uniqueStorage()._uncertainIndices = newValue}
  }

  var sphere: Velocity_Recording_V1_FeatureSphere {
    get {return _storage._sphere ?? Velocity_Recording_V1_FeatureSphere()}
    set {_uniqueStorage()._sphere = newValue}
  }
  /// Returns true if `sphere` has been explicitly set.
  var hasSphere: Bool {return _storage._sphere != nil}
  /// Clears the value of `sphere`. Subsequent reads from it will return its default value.
  mutating func clearSphere() {_uniqueStorage()._sphere = nil}

  var decision: Velocity_Recording_V1_FeatureDecision {
    get {return _storage._decision}
    set {_uniqueStorage()._decision = newValue}
  }

  var method: String {
    get {return _storage._method}
    set {_uniqueStorage()._method = newValue}
  }

  var author: String {
    get {return _storage._author}
    set {_uniqueStorage()._author = newValue}
  }

  var membershipRevision: UInt64 {
    get {return _storage._membershipRevision}
    set {_uniqueStorage()._membershipRevision = newValue}
  }

  var membershipDigest: String {
    get {return _storage._membershipDigest}
    set {_uniqueStorage()._membershipDigest = newValue}
  }

  var proposedFromSample: UInt32 {
    get {return _storage._proposedFromSample ?? 0}
    set {_uniqueStorage()._proposedFromSample = newValue}
  }
  /// Returns true if `proposedFromSample` has been explicitly set.
  var hasProposedFromSample: Bool {return _storage._proposedFromSample != nil}
  /// Clears the value of `proposedFromSample`. Subsequent reads from it will return its default value.
  mutating func clearProposedFromSample() {_uniqueStorage()._proposedFromSample = nil}

  var note: String {
    get {return _storage._note}
    set {_uniqueStorage()._note = newValue}
  }

  /// Proposals never claim independent-reference provenance. Preserve whether
  /// an algorithmic suggestion or prediction was visible to the operator.
  var origin: String {
    get {return _storage._origin}
    set {_uniqueStorage()._origin = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Velocity_Recording_V1_FeatureAnchor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Stable metric part frame, not a changing bounding-box origin.
  var partFrameID: String = String()

  var partFrameRevision: UInt64 = 0

  var xM: Double = 0

  var yM: Double = 0

  var zM: Double = 0

  var physicalRevision: UInt64 = 0

  var physicalDigest: String = String()

  var bodyID: String = String()

  var keyframeID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Velocity_Recording_V1_FeatureCandidate: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var featureID: String {
    get {return _storage._featureID}
    set {_uniqueStorage()._featureID = newValue}
  }

  var objectID: String {
    get {return _storage._objectID}
    set {_uniqueStorage()._objectID = newValue}
  }

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var geometry: Velocity_Recording_V1_FeatureGeometry {
    get {return _storage._geometry}
    set {_uniqueStorage()._geometry = newValue}
  }

  var semanticHint: String {
    get {return _storage._semanticHint}
    set {_uniqueStorage()._semanticHint = newValue}
  }

  var partID: String {
    get {return _storage._partID}
    set {_uniqueStorage()._partID = newValue}
  }

  /// Pilot writes "unknown"; it does not assert a rigid/articulated transform.
  var partRelation: String {
    get {return _storage._partRelation}
    set {_uniqueStorage()._partRelation = newValue}
  }

  var anchor: Velocity_Recording_V1_FeatureAnchor {
    get {return _storage._anchor ?? Velocity_Recording_V1_FeatureAnchor()}
    set {_uniqueStorage()._anchor = newValue}
  }
  /// Returns true if `anchor` has been explicitly set.
  var hasAnchor: Bool {return _storage._anchor != nil}
  /// Clears the value of `anchor`. Subsequent reads from it will return its default value.
  mutating func clearAnchor() {_uniqueStorage()._anchor = nil}

  var observations: [Velocity_Recording_V1_FeatureObservation] {
    get {return _storage._observations}
    set {_uniqueStorage()._observations = newValue}
  }

  /// Keep historic evidence when a facet retires. Absent means active for v1.
  /// At most four active facets per logical object; zero is valid abstention.
  var inactive: Bool {
    get {return _storage._inactive}
    set {_uniqueStorage()._inactive = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Velocity_Recording_V1_FeatureAnnotations: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Exact kind: velocity.report/feature-proposals. Never an observation stream.
  var schema: String = String()

  var schemaVersion: UInt32 = 0

  var packDigest: String = String()

  var datasetID: String = String()

  var revision: UInt64 = 0

  var updatedUtc: String = String()

  var author: String = String()

  var features: [Velocity_Recording_V1_FeatureCandidate] = []

  /// Pilot: legacy_pack. No synthetic mapping to 1.x retained point IDs.
  var pointDomain: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Velocity_Recording_V1_FeatureState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var document: Velocity_Recording_V1_FeatureAnnotations {
    get {return _document ?? Velocity_Recording_V1_FeatureAnnotations()}
    set {_document = newValue}
  }
  /// Returns true if `document` has been explicitly set.
  var hasDocument: Bool {return self._document != nil}
  /// Clears the value of `document`. Subsequent reads from it will return its default value.
  mutating func clearDocument() {self._document = nil}

  var digest: String = String()

  var membershipDigest: String = String()

  /// Local writer identity: equal pack bytes in another folder are not this copy.
  var packDirectory: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _document: Velocity_Recording_V1_FeatureAnnotations? = nil
}

struct Velocity_Recording_V1_FeatureEdit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var document: Velocity_Recording_V1_FeatureAnnotations {
    get {return _document ?? Velocity_Recording_V1_FeatureAnnotations()}
    set {_document = newValue}
  }
  /// Returns true if `document` has been explicitly set.
  var hasDocument: Bool {return self._document != nil}
  /// Clears the value of `document`. Subsequent reads from it will return its default value.
  mutating func clearDocument() {self._document = nil}

  var baseDigest: String = String()

  var membershipDigest: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _document: Velocity_Recording_V1_FeatureAnnotations? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "velocity.recording.v1"

extension Velocity_Recording_V1_FeatureGeometry: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FEATURE_GEOMETRY_UNKNOWN\0\u{1}FEATURE_GEOMETRY_EDGE\0\u{1}FEATURE_GEOMETRY_CORNER\0\u{1}FEATURE_GEOMETRY_PATCH\0\u{1}FEATURE_GEOMETRY_PROTRUSION\0")
}

extension Velocity_Recording_V1_FeatureDecision: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FEATURE_DECISION_UNSPECIFIED\0\u{1}FEATURE_DECISION_ACCEPTED_PROPOSAL\0\u{1}FEATURE_DECISION_REJECTED\0\u{1}FEATURE_DECISION_MISSING\0\u{1}FEATURE_DECISION_OCCLUDED\0")
}

extension Velocity_Recording_V1_FeatureSphere: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureSphere"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}x_m\0\u{3}y_m\0\u{3}z_m\0\u{3}radius_m\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.xM) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.yM) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.zM) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.radiusM) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.xM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.xM, fieldNumber: 1)
    }
    if self.yM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.yM, fieldNumber: 2)
    }
    if self.zM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.zM, fieldNumber: 3)
    }
    if self.radiusM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.radiusM, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureSphere, rhs: Velocity_Recording_V1_FeatureSphere) -> Bool {
    if lhs.xM != rhs.xM {return false}
    if lhs.yM != rhs.yM {return false}
    if lhs.zM != rhs.zM {return false}
    if lhs.radiusM != rhs.radiusM {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureObservation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sample_id\0\u{3}timestamp_ns\0\u{3}source_ordinal\0\u{3}point_indices\0\u{3}uncertain_indices\0\u{1}sphere\0\u{1}decision\0\u{1}method\0\u{1}author\0\u{3}membership_revision\0\u{3}membership_digest\0\u{3}proposed_from_sample\0\u{1}note\0\u{1}origin\0")

  fileprivate class _StorageClass {
    var _sampleID: UInt32 = 0
    var _timestampNs: Int64 = 0
    var _sourceOrdinal: UInt32 = 0
    var _pointIndices: [UInt32] = []
    var _uncertainIndices: [UInt32] = []
    var _sphere: Velocity_Recording_V1_FeatureSphere? = nil
    var _decision: Velocity_Recording_V1_FeatureDecision = .unspecified
    var _method: String = String()
    var _author: String = String()
    var _membershipRevision: UInt64 = 0
    var _membershipDigest: String = String()
    var _proposedFromSample: UInt32? = nil
    var _note: String = String()
    var _origin: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _sampleID = source._sampleID
      _timestampNs = source._timestampNs
      _sourceOrdinal = source._sourceOrdinal
      _pointIndices = source._pointIndices
      _uncertainIndices = source._uncertainIndices
      _sphere = source._sphere
      _decision = source._decision
      _method = source._method
      _author = source._author
      _membershipRevision = source._membershipRevision
      _membershipDigest = source._membershipDigest
      _proposedFromSample = source._proposedFromSample
      _note = source._note
      _origin = source._origin
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._sampleID) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._timestampNs) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._sourceOrdinal) }()
        case 4: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._pointIndices) }()
        case 5: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._uncertainIndices) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._sphere) }()
        case 7: try { try decoder.decodeSingularEnumField(value: &_storage._decision) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._method) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._author) }()
        case 10: try { try decoder.decodeSingularUInt64Field(value: &_storage._membershipRevision) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._membershipDigest) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._proposedFromSample) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._note) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._origin) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._sampleID != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._sampleID, fieldNumber: 1)
      }
      if _storage._timestampNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._timestampNs, fieldNumber: 2)
      }
      if _storage._sourceOrdinal != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._sourceOrdinal, fieldNumber: 3)
      }
      if !_storage._pointIndices.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._pointIndices, fieldNumber: 4)
      }
      if !_storage._uncertainIndices.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._uncertainIndices, fieldNumber: 5)
      }
      try { if let v = _storage._sphere {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if _storage._decision != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._decision, fieldNumber: 7)
      }
      if !_storage._method.isEmpty {
        try visitor.visitSingularStringField(value: _storage._method, fieldNumber: 8)
      }
      if !_storage._author.isEmpty {
        try visitor.visitSingularStringField(value: _storage._author, fieldNumber: 9)
      }
      if _storage._membershipRevision != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._membershipRevision, fieldNumber: 10)
      }
      if !_storage._membershipDigest.isEmpty {
        try visitor.visitSingularStringField(value: _storage._membershipDigest, fieldNumber: 11)
      }
      try { if let v = _storage._proposedFromSample {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 12)
      } }()
      if !_storage._note.isEmpty {
        try visitor.visitSingularStringField(value: _storage._note, fieldNumber: 13)
      }
      if !_storage._origin.isEmpty {
        try visitor.visitSingularStringField(value: _storage._origin, fieldNumber: 14)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureObservation, rhs: Velocity_Recording_V1_FeatureObservation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._sampleID != rhs_storage._sampleID {return false}
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._sourceOrdinal != rhs_storage._sourceOrdinal {return false}
        if _storage._pointIndices != rhs_storage._pointIndices {return false}
        if _storage._uncertainIndices != rhs_storage._uncertainIndices {return false}
        if _storage._sphere != rhs_storage._sphere {return false}
        if _storage._decision != rhs_storage._decision {return false}
        if _storage._method != rhs_storage._method {return false}
        if _storage._author != rhs_storage._author {return false}
        if _storage._membershipRevision != rhs_storage._membershipRevision {return false}
        if _storage._membershipDigest != rhs_storage._membershipDigest {return false}
        if _storage._proposedFromSample != rhs_storage._proposedFromSample {return false}
        if _storage._note != rhs_storage._note {return false}
        if _storage._origin != rhs_storage._origin {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureAnchor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureAnchor"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}part_frame_id\0\u{3}part_frame_revision\0\u{3}x_m\0\u{3}y_m\0\u{3}z_m\0\u{3}physical_revision\0\u{3}physical_digest\0\u{3}body_id\0\u{3}keyframe_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.partFrameID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.partFrameRevision) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.xM) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.yM) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.zM) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.physicalRevision) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.physicalDigest) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.bodyID) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.keyframeID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.partFrameID.isEmpty {
      try visitor.visitSingularStringField(value: self.partFrameID, fieldNumber: 1)
    }
    if self.partFrameRevision != 0 {
      try visitor.visitSingularUInt64Field(value: self.partFrameRevision, fieldNumber: 2)
    }
    if self.xM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.xM, fieldNumber: 3)
    }
    if self.yM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.yM, fieldNumber: 4)
    }
    if self.zM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.zM, fieldNumber: 5)
    }
    if self.physicalRevision != 0 {
      try visitor.visitSingularUInt64Field(value: self.physicalRevision, fieldNumber: 6)
    }
    if !self.physicalDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.physicalDigest, fieldNumber: 7)
    }
    if !self.bodyID.isEmpty {
      try visitor.visitSingularStringField(value: self.bodyID, fieldNumber: 8)
    }
    if !self.keyframeID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyframeID, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureAnchor, rhs: Velocity_Recording_V1_FeatureAnchor) -> Bool {
    if lhs.partFrameID != rhs.partFrameID {return false}
    if lhs.partFrameRevision != rhs.partFrameRevision {return false}
    if lhs.xM != rhs.xM {return false}
    if lhs.yM != rhs.yM {return false}
    if lhs.zM != rhs.zM {return false}
    if lhs.physicalRevision != rhs.physicalRevision {return false}
    if lhs.physicalDigest != rhs.physicalDigest {return false}
    if lhs.bodyID != rhs.bodyID {return false}
    if lhs.keyframeID != rhs.keyframeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureCandidate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureCandidate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}feature_id\0\u{3}object_id\0\u{1}name\0\u{1}geometry\0\u{3}semantic_hint\0\u{3}part_id\0\u{3}part_relation\0\u{1}anchor\0\u{1}observations\0\u{1}inactive\0")

  fileprivate class _StorageClass {
    var _featureID: String = String()
    var _objectID: String = String()
    var _name: String = String()
    var _geometry: Velocity_Recording_V1_FeatureGeometry = .unknown
    var _semanticHint: String = String()
    var _partID: String = String()
    var _partRelation: String = String()
    var _anchor: Velocity_Recording_V1_FeatureAnchor? = nil
    var _observations: [Velocity_Recording_V1_FeatureObservation] = []
    var _inactive: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _featureID = source._featureID
      _objectID = source._objectID
      _name = source._name
      _geometry = source._geometry
      _semanticHint = source._semanticHint
      _partID = source._partID
      _partRelation = source._partRelation
      _anchor = source._anchor
      _observations = source._observations
      _inactive = source._inactive
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._featureID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._objectID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 4: try { try decoder.decodeSingularEnumField(value: &_storage._geometry) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._semanticHint) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._partID) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._partRelation) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._anchor) }()
        case 9: try { try decoder.decodeRepeatedMessageField(value: &_storage._observations) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._inactive) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._featureID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._featureID, fieldNumber: 1)
      }
      if !_storage._objectID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._objectID, fieldNumber: 2)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 3)
      }
      if _storage._geometry != .unknown {
        try visitor.visitSingularEnumField(value: _storage._geometry, fieldNumber: 4)
      }
      if !_storage._semanticHint.isEmpty {
        try visitor.visitSingularStringField(value: _storage._semanticHint, fieldNumber: 5)
      }
      if !_storage._partID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._partID, fieldNumber: 6)
      }
      if !_storage._partRelation.isEmpty {
        try visitor.visitSingularStringField(value: _storage._partRelation, fieldNumber: 7)
      }
      try { if let v = _storage._anchor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      if !_storage._observations.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._observations, fieldNumber: 9)
      }
      if _storage._inactive != false {
        try visitor.visitSingularBoolField(value: _storage._inactive, fieldNumber: 10)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureCandidate, rhs: Velocity_Recording_V1_FeatureCandidate) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._featureID != rhs_storage._featureID {return false}
        if _storage._objectID != rhs_storage._objectID {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._geometry != rhs_storage._geometry {return false}
        if _storage._semanticHint != rhs_storage._semanticHint {return false}
        if _storage._partID != rhs_storage._partID {return false}
        if _storage._partRelation != rhs_storage._partRelation {return false}
        if _storage._anchor != rhs_storage._anchor {return false}
        if _storage._observations != rhs_storage._observations {return false}
        if _storage._inactive != rhs_storage._inactive {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureAnnotations: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureAnnotations"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}schema\0\u{3}schema_version\0\u{3}pack_digest\0\u{3}dataset_id\0\u{1}revision\0\u{3}updated_utc\0\u{1}author\0\u{1}features\0\u{3}point_domain\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.schema) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.schemaVersion) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.packDigest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.datasetID) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.revision) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.updatedUtc) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.features) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.pointDomain) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.schema.isEmpty {
      try visitor.visitSingularStringField(value: self.schema, fieldNumber: 1)
    }
    if self.schemaVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.schemaVersion, fieldNumber: 2)
    }
    if !self.packDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.packDigest, fieldNumber: 3)
    }
    if !self.datasetID.isEmpty {
      try visitor.visitSingularStringField(value: self.datasetID, fieldNumber: 4)
    }
    if self.revision != 0 {
      try visitor.visitSingularUInt64Field(value: self.revision, fieldNumber: 5)
    }
    if !self.updatedUtc.isEmpty {
      try visitor.visitSingularStringField(value: self.updatedUtc, fieldNumber: 6)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 7)
    }
    if !self.features.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.features, fieldNumber: 8)
    }
    if !self.pointDomain.isEmpty {
      try visitor.visitSingularStringField(value: self.pointDomain, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureAnnotations, rhs: Velocity_Recording_V1_FeatureAnnotations) -> Bool {
    if lhs.schema != rhs.schema {return false}
    if lhs.schemaVersion != rhs.schemaVersion {return false}
    if lhs.packDigest != rhs.packDigest {return false}
    if lhs.datasetID != rhs.datasetID {return false}
    if lhs.revision != rhs.revision {return false}
    if lhs.updatedUtc != rhs.updatedUtc {return false}
    if lhs.author != rhs.author {return false}
    if lhs.features != rhs.features {return false}
    if lhs.pointDomain != rhs.pointDomain {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureState"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}document\0\u{1}digest\0\u{3}membership_digest\0\u{3}pack_directory\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._document) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.digest) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.membershipDigest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.packDirectory) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._document {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.digest.isEmpty {
      try visitor.visitSingularStringField(value: self.digest, fieldNumber: 2)
    }
    if !self.membershipDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.membershipDigest, fieldNumber: 3)
    }
    if !self.packDirectory.isEmpty {
      try visitor.visitSingularStringField(value: self.packDirectory, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureState, rhs: Velocity_Recording_V1_FeatureState) -> Bool {
    if lhs._document != rhs._document {return false}
    if lhs.digest != rhs.digest {return false}
    if lhs.membershipDigest != rhs.membershipDigest {return false}
    if lhs.packDirectory != rhs.packDirectory {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureEdit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureEdit"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}document\0\u{3}base_digest\0\u{3}membership_digest\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._document) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.baseDigest) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.membershipDigest) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._document {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.baseDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.baseDigest, fieldNumber: 2)
    }
    if !self.membershipDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.membershipDigest, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureEdit, rhs: Velocity_Recording_V1_FeatureEdit) -> Bool {
    if lhs._document != rhs._document {return false}
    if lhs.baseDigest != rhs.baseDigest {return false}
    if lhs.membershipDigest != rhs.membershipDigest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
