// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: features.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Revisioned feature proposals over existing annotation-pack evidence.
/// This is an annotation document, NOT a VRLOG observation or display frame.
/// Field numbers are permanent. Zero sample/point indices are valid; absent
/// anchors stay absent. Legacy pack references do not claim retained IDs.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Velocity_Recording_V1_FeatureGeometry: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknown // = 0
  case edge // = 1
  case corner // = 2
  case patch // = 3
  case protrusion // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .edge
    case 2: self = .corner
    case 3: self = .patch
    case 4: self = .protrusion
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .edge: return 1
    case .corner: return 2
    case .patch: return 3
    case .protrusion: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Velocity_Recording_V1_FeatureGeometry] = [
    .unknown,
    .edge,
    .corner,
    .patch,
    .protrusion,
  ]

}

enum Velocity_Recording_V1_FeatureDecision: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0

  /// Accepted as an operator's feature proposal, never physical-reference truth.
  case acceptedProposal // = 1
  case rejected // = 2
  case missing // = 3
  case occluded // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .acceptedProposal
    case 2: self = .rejected
    case 3: self = .missing
    case 4: self = .occluded
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .acceptedProposal: return 1
    case .rejected: return 2
    case .missing: return 3
    case .occluded: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Velocity_Recording_V1_FeatureDecision] = [
    .unspecified,
    .acceptedProposal,
    .rejected,
    .missing,
    .occluded,
  ]

}

struct Velocity_Recording_V1_FeatureSphere: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var xM: Double = 0

  var yM: Double = 0

  var zM: Double = 0

  var radiusM: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Velocity_Recording_V1_FeatureObservation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sampleID: UInt32 {
    get {return _storage._sampleID}
    set {_uniqueStorage()._sampleID = newValue}
  }

  var timestampNs: Int64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  var sourceOrdinal: UInt32 {
    get {return _storage._sourceOrdinal}
    set {_uniqueStorage()._sourceOrdinal = newValue}
  }

  /// Exact indices in this pack sample only. Different features may overlap.
  var pointIndices: [UInt32] {
    get {return _storage._pointIndices}
    set {_uniqueStorage()._pointIndices = newValue}
  }

  var uncertainIndices: [UInt32] {
    get {return _storage._uncertainIndices}
    set {_uniqueStorage()._uncertainIndices = newValue}
  }

  var sphere: Velocity_Recording_V1_FeatureSphere {
    get {return _storage._sphere ?? Velocity_Recording_V1_FeatureSphere()}
    set {_uniqueStorage()._sphere = newValue}
  }
  /// Returns true if `sphere` has been explicitly set.
  var hasSphere: Bool {return _storage._sphere != nil}
  /// Clears the value of `sphere`. Subsequent reads from it will return its default value.
  mutating func clearSphere() {_uniqueStorage()._sphere = nil}

  var decision: Velocity_Recording_V1_FeatureDecision {
    get {return _storage._decision}
    set {_uniqueStorage()._decision = newValue}
  }

  var method: String {
    get {return _storage._method}
    set {_uniqueStorage()._method = newValue}
  }

  var author: String {
    get {return _storage._author}
    set {_uniqueStorage()._author = newValue}
  }

  var membershipRevision: UInt64 {
    get {return _storage._membershipRevision}
    set {_uniqueStorage()._membershipRevision = newValue}
  }

  var membershipDigest: String {
    get {return _storage._membershipDigest}
    set {_uniqueStorage()._membershipDigest = newValue}
  }

  var proposedFromSample: UInt32 {
    get {return _storage._proposedFromSample ?? 0}
    set {_uniqueStorage()._proposedFromSample = newValue}
  }
  /// Returns true if `proposedFromSample` has been explicitly set.
  var hasProposedFromSample: Bool {return _storage._proposedFromSample != nil}
  /// Clears the value of `proposedFromSample`. Subsequent reads from it will return its default value.
  mutating func clearProposedFromSample() {_uniqueStorage()._proposedFromSample = nil}

  var note: String {
    get {return _storage._note}
    set {_uniqueStorage()._note = newValue}
  }

  /// Proposals never claim independent-reference provenance. Preserve whether
  /// an algorithmic suggestion or prediction was visible to the operator.
  var origin: String {
    get {return _storage._origin}
    set {_uniqueStorage()._origin = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Velocity_Recording_V1_FeatureAnchor: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Stable metric part frame, not a changing bounding-box origin.
  var partFrameID: String {
    get {return _storage._partFrameID}
    set {_uniqueStorage()._partFrameID = newValue}
  }

  var partFrameRevision: UInt64 {
    get {return _storage._partFrameRevision}
    set {_uniqueStorage()._partFrameRevision = newValue}
  }

  var xM: Double {
    get {return _storage._xM}
    set {_uniqueStorage()._xM = newValue}
  }

  var yM: Double {
    get {return _storage._yM}
    set {_uniqueStorage()._yM = newValue}
  }

  var zM: Double {
    get {return _storage._zM}
    set {_uniqueStorage()._zM = newValue}
  }

  var physicalRevision: UInt64 {
    get {return _storage._physicalRevision}
    set {_uniqueStorage()._physicalRevision = newValue}
  }

  var physicalDigest: String {
    get {return _storage._physicalDigest}
    set {_uniqueStorage()._physicalDigest = newValue}
  }

  var bodyID: String {
    get {return _storage._bodyID}
    set {_uniqueStorage()._bodyID = newValue}
  }

  var keyframeID: String {
    get {return _storage._keyframeID}
    set {_uniqueStorage()._keyframeID = newValue}
  }

  /// Pilot registration is horizontal only. Z remains unresolved, never zero height.
  var coordinateDomain: String {
    get {return _storage._coordinateDomain}
    set {_uniqueStorage()._coordinateDomain = newValue}
  }

  var sourceSample: UInt32 {
    get {return _storage._sourceSample}
    set {_uniqueStorage()._sourceSample = newValue}
  }

  var sourcePointIndex: UInt32 {
    get {return _storage._sourcePointIndex ?? 0}
    set {_uniqueStorage()._sourcePointIndex = newValue}
  }
  /// Returns true if `sourcePointIndex` has been explicitly set.
  var hasSourcePointIndex: Bool {return _storage._sourcePointIndex != nil}
  /// Clears the value of `sourcePointIndex`. Subsequent reads from it will return its default value.
  mutating func clearSourcePointIndex() {_uniqueStorage()._sourcePointIndex = nil}

  var boundM: Double {
    get {return _storage._boundM}
    set {_uniqueStorage()._boundM = newValue}
  }

  var returnBoundM: Double {
    get {return _storage._returnBoundM}
    set {_uniqueStorage()._returnBoundM = newValue}
  }

  /// reference_seeded_proposal or tracker_seeded_proposal; never truth
  var origin: String {
    get {return _storage._origin}
    set {_uniqueStorage()._origin = newValue}
  }

  /// manual_named_return_v1
  var method: String {
    get {return _storage._method}
    set {_uniqueStorage()._method = newValue}
  }

  /// the repeatable physical spot, not visible centroid
  var identityNote: String {
    get {return _storage._identityNote}
    set {_uniqueStorage()._identityNote = newValue}
  }

  /// A horizontal line relation constrains only its normal offset and axial
  /// orientation. Tangential position stays unresolved. No point coordinate
  /// is implied: x_m/y_m/z_m stay zero and source_point_index stays absent.
  var line: Velocity_Recording_V1_FeatureLineConstraint {
    get {return _storage._line ?? Velocity_Recording_V1_FeatureLineConstraint()}
    set {_uniqueStorage()._line = newValue}
  }
  /// Returns true if `line` has been explicitly set.
  var hasLine: Bool {return _storage._line != nil}
  /// Clears the value of `line`. Subsequent reads from it will return its default value.
  mutating func clearLine() {_uniqueStorage()._line = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Velocity_Recording_V1_FeatureLineConstraint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unit normal in the pinned body's XY frame: n dot p = offset_m.
  var normalX: Double = 0

  var normalY: Double = 0

  var offsetM: Double = 0

  /// Conservative angular bound, including the source pose and return bounds.
  var normalBoundRad: Double = 0

  /// Operator-chosen returns define the segment direction, never persistent
  /// physical endpoints. Optional presence preserves valid point index zero.
  var sourceStartIndex: UInt32 {
    get {return _sourceStartIndex ?? 0}
    set {_sourceStartIndex = newValue}
  }
  /// Returns true if `sourceStartIndex` has been explicitly set.
  var hasSourceStartIndex: Bool {return self._sourceStartIndex != nil}
  /// Clears the value of `sourceStartIndex`. Subsequent reads from it will return its default value.
  mutating func clearSourceStartIndex() {self._sourceStartIndex = nil}

  var sourceEndIndex: UInt32 {
    get {return _sourceEndIndex ?? 0}
    set {_sourceEndIndex = newValue}
  }
  /// Returns true if `sourceEndIndex` has been explicitly set.
  var hasSourceEndIndex: Bool {return self._sourceEndIndex != nil}
  /// Clears the value of `sourceEndIndex`. Subsequent reads from it will return its default value.
  mutating func clearSourceEndIndex() {self._sourceEndIndex = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _sourceStartIndex: UInt32? = nil
  fileprivate var _sourceEndIndex: UInt32? = nil
}

struct Velocity_Recording_V1_FeatureCandidate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var featureID: String = String()

  var objectID: String = String()

  var name: String = String()

  var geometry: Velocity_Recording_V1_FeatureGeometry = .unknown

  var semanticHint: String = String()

  var partID: String = String()

  /// unknown, or rigid_proposal under an explicitly pinned body registration.
  /// A proposal never asserts an independently reviewed rigid transform.
  var partRelation: String = String()

  var anchor: Velocity_Recording_V1_FeatureAnchor {
    get {return _anchor ?? Velocity_Recording_V1_FeatureAnchor()}
    set {_anchor = newValue}
  }
  /// Returns true if `anchor` has been explicitly set.
  var hasAnchor: Bool {return self._anchor != nil}
  /// Clears the value of `anchor`. Subsequent reads from it will return its default value.
  mutating func clearAnchor() {self._anchor = nil}

  var observations: [Velocity_Recording_V1_FeatureObservation] = []

  /// Keep historic evidence when a facet retires. Absent means active for v1.
  /// At most four active facets per logical object; zero is valid abstention.
  var inactive: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _anchor: Velocity_Recording_V1_FeatureAnchor? = nil
}

struct Velocity_Recording_V1_FeatureAnnotations: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Exact kind: velocity.report/feature-proposals. Never an observation stream.
  var schema: String = String()

  var schemaVersion: UInt32 = 0

  var packDigest: String = String()

  var datasetID: String = String()

  var revision: UInt64 = 0

  var updatedUtc: String = String()

  var author: String = String()

  var features: [Velocity_Recording_V1_FeatureCandidate] = []

  /// Pilot: legacy_pack. No synthetic mapping to 1.x retained point IDs.
  var pointDomain: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Velocity_Recording_V1_FeatureState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var document: Velocity_Recording_V1_FeatureAnnotations {
    get {return _document ?? Velocity_Recording_V1_FeatureAnnotations()}
    set {_document = newValue}
  }
  /// Returns true if `document` has been explicitly set.
  var hasDocument: Bool {return self._document != nil}
  /// Clears the value of `document`. Subsequent reads from it will return its default value.
  mutating func clearDocument() {self._document = nil}

  var digest: String = String()

  var membershipDigest: String = String()

  /// Local writer identity: equal pack bytes in another folder are not this copy.
  var packDirectory: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _document: Velocity_Recording_V1_FeatureAnnotations? = nil
}

struct Velocity_Recording_V1_FeatureEdit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var document: Velocity_Recording_V1_FeatureAnnotations {
    get {return _document ?? Velocity_Recording_V1_FeatureAnnotations()}
    set {_document = newValue}
  }
  /// Returns true if `document` has been explicitly set.
  var hasDocument: Bool {return self._document != nil}
  /// Clears the value of `document`. Subsequent reads from it will return its default value.
  mutating func clearDocument() {self._document = nil}

  var baseDigest: String = String()

  var membershipDigest: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _document: Velocity_Recording_V1_FeatureAnnotations? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "velocity.recording.v1"

extension Velocity_Recording_V1_FeatureGeometry: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FEATURE_GEOMETRY_UNKNOWN\0\u{1}FEATURE_GEOMETRY_EDGE\0\u{1}FEATURE_GEOMETRY_CORNER\0\u{1}FEATURE_GEOMETRY_PATCH\0\u{1}FEATURE_GEOMETRY_PROTRUSION\0")
}

extension Velocity_Recording_V1_FeatureDecision: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FEATURE_DECISION_UNSPECIFIED\0\u{1}FEATURE_DECISION_ACCEPTED_PROPOSAL\0\u{1}FEATURE_DECISION_REJECTED\0\u{1}FEATURE_DECISION_MISSING\0\u{1}FEATURE_DECISION_OCCLUDED\0")
}

extension Velocity_Recording_V1_FeatureSphere: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureSphere"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}x_m\0\u{3}y_m\0\u{3}z_m\0\u{3}radius_m\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.xM) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.yM) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.zM) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.radiusM) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.xM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.xM, fieldNumber: 1)
    }
    if self.yM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.yM, fieldNumber: 2)
    }
    if self.zM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.zM, fieldNumber: 3)
    }
    if self.radiusM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.radiusM, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureSphere, rhs: Velocity_Recording_V1_FeatureSphere) -> Bool {
    if lhs.xM != rhs.xM {return false}
    if lhs.yM != rhs.yM {return false}
    if lhs.zM != rhs.zM {return false}
    if lhs.radiusM != rhs.radiusM {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureObservation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sample_id\0\u{3}timestamp_ns\0\u{3}source_ordinal\0\u{3}point_indices\0\u{3}uncertain_indices\0\u{1}sphere\0\u{1}decision\0\u{1}method\0\u{1}author\0\u{3}membership_revision\0\u{3}membership_digest\0\u{3}proposed_from_sample\0\u{1}note\0\u{1}origin\0")

  fileprivate class _StorageClass {
    var _sampleID: UInt32 = 0
    var _timestampNs: Int64 = 0
    var _sourceOrdinal: UInt32 = 0
    var _pointIndices: [UInt32] = []
    var _uncertainIndices: [UInt32] = []
    var _sphere: Velocity_Recording_V1_FeatureSphere? = nil
    var _decision: Velocity_Recording_V1_FeatureDecision = .unspecified
    var _method: String = String()
    var _author: String = String()
    var _membershipRevision: UInt64 = 0
    var _membershipDigest: String = String()
    var _proposedFromSample: UInt32? = nil
    var _note: String = String()
    var _origin: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _sampleID = source._sampleID
      _timestampNs = source._timestampNs
      _sourceOrdinal = source._sourceOrdinal
      _pointIndices = source._pointIndices
      _uncertainIndices = source._uncertainIndices
      _sphere = source._sphere
      _decision = source._decision
      _method = source._method
      _author = source._author
      _membershipRevision = source._membershipRevision
      _membershipDigest = source._membershipDigest
      _proposedFromSample = source._proposedFromSample
      _note = source._note
      _origin = source._origin
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._sampleID) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._timestampNs) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._sourceOrdinal) }()
        case 4: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._pointIndices) }()
        case 5: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._uncertainIndices) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._sphere) }()
        case 7: try { try decoder.decodeSingularEnumField(value: &_storage._decision) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._method) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._author) }()
        case 10: try { try decoder.decodeSingularUInt64Field(value: &_storage._membershipRevision) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._membershipDigest) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._proposedFromSample) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._note) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._origin) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._sampleID != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._sampleID, fieldNumber: 1)
      }
      if _storage._timestampNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._timestampNs, fieldNumber: 2)
      }
      if _storage._sourceOrdinal != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._sourceOrdinal, fieldNumber: 3)
      }
      if !_storage._pointIndices.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._pointIndices, fieldNumber: 4)
      }
      if !_storage._uncertainIndices.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._uncertainIndices, fieldNumber: 5)
      }
      try { if let v = _storage._sphere {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if _storage._decision != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._decision, fieldNumber: 7)
      }
      if !_storage._method.isEmpty {
        try visitor.visitSingularStringField(value: _storage._method, fieldNumber: 8)
      }
      if !_storage._author.isEmpty {
        try visitor.visitSingularStringField(value: _storage._author, fieldNumber: 9)
      }
      if _storage._membershipRevision != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._membershipRevision, fieldNumber: 10)
      }
      if !_storage._membershipDigest.isEmpty {
        try visitor.visitSingularStringField(value: _storage._membershipDigest, fieldNumber: 11)
      }
      try { if let v = _storage._proposedFromSample {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 12)
      } }()
      if !_storage._note.isEmpty {
        try visitor.visitSingularStringField(value: _storage._note, fieldNumber: 13)
      }
      if !_storage._origin.isEmpty {
        try visitor.visitSingularStringField(value: _storage._origin, fieldNumber: 14)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureObservation, rhs: Velocity_Recording_V1_FeatureObservation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._sampleID != rhs_storage._sampleID {return false}
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._sourceOrdinal != rhs_storage._sourceOrdinal {return false}
        if _storage._pointIndices != rhs_storage._pointIndices {return false}
        if _storage._uncertainIndices != rhs_storage._uncertainIndices {return false}
        if _storage._sphere != rhs_storage._sphere {return false}
        if _storage._decision != rhs_storage._decision {return false}
        if _storage._method != rhs_storage._method {return false}
        if _storage._author != rhs_storage._author {return false}
        if _storage._membershipRevision != rhs_storage._membershipRevision {return false}
        if _storage._membershipDigest != rhs_storage._membershipDigest {return false}
        if _storage._proposedFromSample != rhs_storage._proposedFromSample {return false}
        if _storage._note != rhs_storage._note {return false}
        if _storage._origin != rhs_storage._origin {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureAnchor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureAnchor"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}part_frame_id\0\u{3}part_frame_revision\0\u{3}x_m\0\u{3}y_m\0\u{3}z_m\0\u{3}physical_revision\0\u{3}physical_digest\0\u{3}body_id\0\u{3}keyframe_id\0\u{3}coordinate_domain\0\u{3}source_sample\0\u{3}source_point_index\0\u{3}bound_m\0\u{3}return_bound_m\0\u{1}origin\0\u{1}method\0\u{3}identity_note\0\u{1}line\0")

  fileprivate class _StorageClass {
    var _partFrameID: String = String()
    var _partFrameRevision: UInt64 = 0
    var _xM: Double = 0
    var _yM: Double = 0
    var _zM: Double = 0
    var _physicalRevision: UInt64 = 0
    var _physicalDigest: String = String()
    var _bodyID: String = String()
    var _keyframeID: String = String()
    var _coordinateDomain: String = String()
    var _sourceSample: UInt32 = 0
    var _sourcePointIndex: UInt32? = nil
    var _boundM: Double = 0
    var _returnBoundM: Double = 0
    var _origin: String = String()
    var _method: String = String()
    var _identityNote: String = String()
    var _line: Velocity_Recording_V1_FeatureLineConstraint? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _partFrameID = source._partFrameID
      _partFrameRevision = source._partFrameRevision
      _xM = source._xM
      _yM = source._yM
      _zM = source._zM
      _physicalRevision = source._physicalRevision
      _physicalDigest = source._physicalDigest
      _bodyID = source._bodyID
      _keyframeID = source._keyframeID
      _coordinateDomain = source._coordinateDomain
      _sourceSample = source._sourceSample
      _sourcePointIndex = source._sourcePointIndex
      _boundM = source._boundM
      _returnBoundM = source._returnBoundM
      _origin = source._origin
      _method = source._method
      _identityNote = source._identityNote
      _line = source._line
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._partFrameID) }()
        case 2: try { try decoder.decodeSingularUInt64Field(value: &_storage._partFrameRevision) }()
        case 3: try { try decoder.decodeSingularDoubleField(value: &_storage._xM) }()
        case 4: try { try decoder.decodeSingularDoubleField(value: &_storage._yM) }()
        case 5: try { try decoder.decodeSingularDoubleField(value: &_storage._zM) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._physicalRevision) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._physicalDigest) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._bodyID) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._keyframeID) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._coordinateDomain) }()
        case 11: try { try decoder.decodeSingularUInt32Field(value: &_storage._sourceSample) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._sourcePointIndex) }()
        case 13: try { try decoder.decodeSingularDoubleField(value: &_storage._boundM) }()
        case 14: try { try decoder.decodeSingularDoubleField(value: &_storage._returnBoundM) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._origin) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._method) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._identityNote) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._line) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._partFrameID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._partFrameID, fieldNumber: 1)
      }
      if _storage._partFrameRevision != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._partFrameRevision, fieldNumber: 2)
      }
      if _storage._xM.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._xM, fieldNumber: 3)
      }
      if _storage._yM.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._yM, fieldNumber: 4)
      }
      if _storage._zM.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._zM, fieldNumber: 5)
      }
      if _storage._physicalRevision != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._physicalRevision, fieldNumber: 6)
      }
      if !_storage._physicalDigest.isEmpty {
        try visitor.visitSingularStringField(value: _storage._physicalDigest, fieldNumber: 7)
      }
      if !_storage._bodyID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bodyID, fieldNumber: 8)
      }
      if !_storage._keyframeID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._keyframeID, fieldNumber: 9)
      }
      if !_storage._coordinateDomain.isEmpty {
        try visitor.visitSingularStringField(value: _storage._coordinateDomain, fieldNumber: 10)
      }
      if _storage._sourceSample != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._sourceSample, fieldNumber: 11)
      }
      try { if let v = _storage._sourcePointIndex {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 12)
      } }()
      if _storage._boundM.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._boundM, fieldNumber: 13)
      }
      if _storage._returnBoundM.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._returnBoundM, fieldNumber: 14)
      }
      if !_storage._origin.isEmpty {
        try visitor.visitSingularStringField(value: _storage._origin, fieldNumber: 15)
      }
      if !_storage._method.isEmpty {
        try visitor.visitSingularStringField(value: _storage._method, fieldNumber: 16)
      }
      if !_storage._identityNote.isEmpty {
        try visitor.visitSingularStringField(value: _storage._identityNote, fieldNumber: 17)
      }
      try { if let v = _storage._line {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureAnchor, rhs: Velocity_Recording_V1_FeatureAnchor) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._partFrameID != rhs_storage._partFrameID {return false}
        if _storage._partFrameRevision != rhs_storage._partFrameRevision {return false}
        if _storage._xM != rhs_storage._xM {return false}
        if _storage._yM != rhs_storage._yM {return false}
        if _storage._zM != rhs_storage._zM {return false}
        if _storage._physicalRevision != rhs_storage._physicalRevision {return false}
        if _storage._physicalDigest != rhs_storage._physicalDigest {return false}
        if _storage._bodyID != rhs_storage._bodyID {return false}
        if _storage._keyframeID != rhs_storage._keyframeID {return false}
        if _storage._coordinateDomain != rhs_storage._coordinateDomain {return false}
        if _storage._sourceSample != rhs_storage._sourceSample {return false}
        if _storage._sourcePointIndex != rhs_storage._sourcePointIndex {return false}
        if _storage._boundM != rhs_storage._boundM {return false}
        if _storage._returnBoundM != rhs_storage._returnBoundM {return false}
        if _storage._origin != rhs_storage._origin {return false}
        if _storage._method != rhs_storage._method {return false}
        if _storage._identityNote != rhs_storage._identityNote {return false}
        if _storage._line != rhs_storage._line {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureLineConstraint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureLineConstraint"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}normal_x\0\u{3}normal_y\0\u{3}offset_m\0\u{3}normal_bound_rad\0\u{3}source_start_index\0\u{3}source_end_index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.normalX) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.normalY) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.offsetM) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.normalBoundRad) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._sourceStartIndex) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._sourceEndIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.normalX.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.normalX, fieldNumber: 1)
    }
    if self.normalY.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.normalY, fieldNumber: 2)
    }
    if self.offsetM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.offsetM, fieldNumber: 3)
    }
    if self.normalBoundRad.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.normalBoundRad, fieldNumber: 4)
    }
    try { if let v = self._sourceStartIndex {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._sourceEndIndex {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureLineConstraint, rhs: Velocity_Recording_V1_FeatureLineConstraint) -> Bool {
    if lhs.normalX != rhs.normalX {return false}
    if lhs.normalY != rhs.normalY {return false}
    if lhs.offsetM != rhs.offsetM {return false}
    if lhs.normalBoundRad != rhs.normalBoundRad {return false}
    if lhs._sourceStartIndex != rhs._sourceStartIndex {return false}
    if lhs._sourceEndIndex != rhs._sourceEndIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureCandidate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureCandidate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}feature_id\0\u{3}object_id\0\u{1}name\0\u{1}geometry\0\u{3}semantic_hint\0\u{3}part_id\0\u{3}part_relation\0\u{1}anchor\0\u{1}observations\0\u{1}inactive\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.featureID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.objectID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.geometry) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.semanticHint) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.partID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.partRelation) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._anchor) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.observations) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.inactive) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.featureID.isEmpty {
      try visitor.visitSingularStringField(value: self.featureID, fieldNumber: 1)
    }
    if !self.objectID.isEmpty {
      try visitor.visitSingularStringField(value: self.objectID, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    if self.geometry != .unknown {
      try visitor.visitSingularEnumField(value: self.geometry, fieldNumber: 4)
    }
    if !self.semanticHint.isEmpty {
      try visitor.visitSingularStringField(value: self.semanticHint, fieldNumber: 5)
    }
    if !self.partID.isEmpty {
      try visitor.visitSingularStringField(value: self.partID, fieldNumber: 6)
    }
    if !self.partRelation.isEmpty {
      try visitor.visitSingularStringField(value: self.partRelation, fieldNumber: 7)
    }
    try { if let v = self._anchor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if !self.observations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.observations, fieldNumber: 9)
    }
    if self.inactive != false {
      try visitor.visitSingularBoolField(value: self.inactive, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureCandidate, rhs: Velocity_Recording_V1_FeatureCandidate) -> Bool {
    if lhs.featureID != rhs.featureID {return false}
    if lhs.objectID != rhs.objectID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.geometry != rhs.geometry {return false}
    if lhs.semanticHint != rhs.semanticHint {return false}
    if lhs.partID != rhs.partID {return false}
    if lhs.partRelation != rhs.partRelation {return false}
    if lhs._anchor != rhs._anchor {return false}
    if lhs.observations != rhs.observations {return false}
    if lhs.inactive != rhs.inactive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureAnnotations: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureAnnotations"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}schema\0\u{3}schema_version\0\u{3}pack_digest\0\u{3}dataset_id\0\u{1}revision\0\u{3}updated_utc\0\u{1}author\0\u{1}features\0\u{3}point_domain\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.schema) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.schemaVersion) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.packDigest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.datasetID) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.revision) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.updatedUtc) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.features) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.pointDomain) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.schema.isEmpty {
      try visitor.visitSingularStringField(value: self.schema, fieldNumber: 1)
    }
    if self.schemaVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.schemaVersion, fieldNumber: 2)
    }
    if !self.packDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.packDigest, fieldNumber: 3)
    }
    if !self.datasetID.isEmpty {
      try visitor.visitSingularStringField(value: self.datasetID, fieldNumber: 4)
    }
    if self.revision != 0 {
      try visitor.visitSingularUInt64Field(value: self.revision, fieldNumber: 5)
    }
    if !self.updatedUtc.isEmpty {
      try visitor.visitSingularStringField(value: self.updatedUtc, fieldNumber: 6)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 7)
    }
    if !self.features.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.features, fieldNumber: 8)
    }
    if !self.pointDomain.isEmpty {
      try visitor.visitSingularStringField(value: self.pointDomain, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureAnnotations, rhs: Velocity_Recording_V1_FeatureAnnotations) -> Bool {
    if lhs.schema != rhs.schema {return false}
    if lhs.schemaVersion != rhs.schemaVersion {return false}
    if lhs.packDigest != rhs.packDigest {return false}
    if lhs.datasetID != rhs.datasetID {return false}
    if lhs.revision != rhs.revision {return false}
    if lhs.updatedUtc != rhs.updatedUtc {return false}
    if lhs.author != rhs.author {return false}
    if lhs.features != rhs.features {return false}
    if lhs.pointDomain != rhs.pointDomain {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureState"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}document\0\u{1}digest\0\u{3}membership_digest\0\u{3}pack_directory\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._document) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.digest) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.membershipDigest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.packDirectory) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._document {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.digest.isEmpty {
      try visitor.visitSingularStringField(value: self.digest, fieldNumber: 2)
    }
    if !self.membershipDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.membershipDigest, fieldNumber: 3)
    }
    if !self.packDirectory.isEmpty {
      try visitor.visitSingularStringField(value: self.packDirectory, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureState, rhs: Velocity_Recording_V1_FeatureState) -> Bool {
    if lhs._document != rhs._document {return false}
    if lhs.digest != rhs.digest {return false}
    if lhs.membershipDigest != rhs.membershipDigest {return false}
    if lhs.packDirectory != rhs.packDirectory {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Velocity_Recording_V1_FeatureEdit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureEdit"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}document\0\u{3}base_digest\0\u{3}membership_digest\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._document) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.baseDigest) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.membershipDigest) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._document {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.baseDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.baseDigest, fieldNumber: 2)
    }
    if !self.membershipDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.membershipDigest, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Velocity_Recording_V1_FeatureEdit, rhs: Velocity_Recording_V1_FeatureEdit) -> Bool {
    if lhs._document != rhs._document {return false}
    if lhs.baseDigest != rhs.baseDigest {return false}
    if lhs.membershipDigest != rhs.membershipDigest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
