/**
 * Derive public_html/scene-sites.json from what the exports and the archive
 * index already know.
 *
 * A scene's position used to be typed in twice: once against a mark in
 * tools/s2-archive/map-marks.json and again against a scene id here. The two
 * copies had no link, so correcting a mark left the map showing the old place.
 *
 * They are joined by the clock instead. A scene export's header carries the
 * wall time its recording starts at, and the archive index carries the same for
 * every site, so a scene belongs to the site whose static period it opens in.
 * Everything a scene needs then follows from the site, and the only file left
 * to edit by hand is the position itself.
 */

/** Tolerance for the clock join, in seconds.
 *
 * An export usually starts a little after the site does — a scene may skip the
 * opening frames while the background model converges — so the window is wide
 * enough for that but far narrower than the gap between two sites, which is a
 * drive of several minutes.
 */
export const JOIN_TOLERANCE_SECONDS = 600;

const MINUTE = 60;

/** Wall-clock start of a scene, from its part header's nanosecond timestamp. */
export function sceneStartMs(header) {
  // start_ns is a string because it does not fit a double without loss.
  return Number(BigInt(header.start_ns) / 1000000n);
}

/**
 * The archive site a scene was recorded at, or null when it was not recorded
 * on the archive volume at all.
 */
export function matchSite(scene, index, tolerance = JOIN_TOLERANCE_SECONDS) {
  let best = null;
  let bestGap = Infinity;
  for (const site of index) {
    const gap = Math.abs(Date.parse(site.start) - scene.startMs) / 1000;
    if (gap < bestGap) {
      best = site;
      bestGap = gap;
    }
  }
  return bestGap <= tolerance ? { site: best, gapSeconds: bestGap } : null;
}

function derivedSummary(scene) {
  const minutes = Math.round(scene.durationSec / MINUTE);
  return `${minutes} minutes of a static roadside recording.`;
}

function derivedNote(site) {
  return (
    `Read from the field map (${site.where}), matched to this recording by the ` +
    "clock rather than by hand. Neighbourhood-level: the one scene with an " +
    "independent check was about 450 m out. Replace with a survey."
  );
}

const UNLOCATED_NOTE =
  "Not yet located. The recording is joined to an archive site, but that " +
  "site's field mark could not be read; give the mark a position and this " +
  "scene inherits it.";

const UNJOINED_NOTE =
  "Not surveyed. The recording is sensor-local, so the scene plays without a " +
  "position; it cannot be placed on the map until one is measured.";

/**
 * Compose the scene-sites document.
 *
 * `overrides` carries only what cannot be derived: a human title, a summary
 * worth writing out, and a position for a scene the archive index does not
 * cover or whose derived position is known to be wrong. An override always
 * wins, so a surveyed fix is never overwritten by a map reading.
 */
export function buildSceneSites({ scenes, index, overrides = {} }) {
  // Chronological, so the list reads as the campaign ran rather than as an
  // accident of naming: the ids are capture prefixes, which sort meaninglessly.
  const sites = scenes
    .slice()
    .sort((a, b) => a.startMs - b.startMs || a.id.localeCompare(b.id))
    .map((scene) => {
      const over = overrides[scene.id] ?? {};
      const joined = matchSite(scene, index);
      const site = joined?.site ?? null;

      let position = null;
      let note = UNJOINED_NOTE;
      let source = null;
      if (over.position) {
        position = {
          lat: over.position.lat,
          lon: over.position.lon,
          source: over.position.source ?? "operator",
        };
        note =
          over.position_note ??
          "Hand-entered. The S2 tokens re-derive from it.";
        source = "override";
      } else if (site && site.lat !== null && site.lon !== null) {
        position = { lat: site.lat, lon: site.lon, source: "operator" };
        note = derivedNote(site);
        source = "archive-index";
      } else if (site) {
        note = UNLOCATED_NOTE;
        source = "archive-index";
      }

      // A capture prefix names the deployment, not a place. Once a scene is
      // joined to a site the place is known, so prefer it: "Bush Street near
      // Kearny" over "s2-sf-6". The prefix is the last resort, for a site whose
      // field mark could not be read at all.
      const title = over.title ?? site?.where ?? scene.title ?? scene.id;

      return {
        id: scene.id,
        title,
        page: `/scenes/${scene.id}/`,
        summary: over.summary ?? derivedSummary(scene),
        archive_site: site ? site.site : null,
        position,
        position_note: note,
        position_source: source,
      };
    });

  return {
    comment: [
      "Generated by tools/s2-hilbert/generate-scene-map.mjs. Do not edit.",
      "",
      "Each scene is joined to an archive site by the wall clock in its export",
      "header, and takes that site's position. Correct a position in",
      "tools/s2-archive/map-marks.json and rebuild; the marker, the cell and the",
      "token all move together.",
      "",
      "public_html/scene-overrides.json holds what cannot be derived: a human",
      "title, a written summary, and a position for a scene the archive does not",
      "cover or whose map reading is known to be wrong. An override always wins,",
      "so a survey is never overwritten by a reading off the paper map.",
    ],
    sites,
  };
}

/**
 * Every recorded site, as map entries.
 *
 * The map exists to show where the sensor has been, which is a larger set than
 * where a scene has been published: 23 sites were recorded and a handful are
 * published. A site already covered by a published scene is left to that scene,
 * so nothing is drawn twice; the rest come through unpublished, with no page to
 * link to and no summary claiming a recording anyone can watch.
 */
export function unpublishedSites({ index, scenes }) {
  const claimed = new Set(scenes.map((s) => s.archive_site).filter(Boolean));
  return index
    .filter((site) => !claimed.has(site.site))
    .filter((site) => site.lat !== null && site.lon !== null)
    .map((site) => ({
      id: `site-${site.site}`,
      title: site.where ?? site.site,
      page: null,
      summary: `${site.minutes.toFixed(0)} minutes recorded on ${site.day}, not yet published.`,
      archive_site: site.site,
      published: false,
      position: { lat: site.lat, lon: site.lon, source: "operator" },
      position_note: `Read from the field map (${site.where}). Neighbourhood-level; replace with a survey.`,
      position_source: "archive-index",
    }));
}
