package l5tracks

import (
	"fmt"
	"math"
	"math/rand"
	"strconv"
	"strings"
	"testing"
)

// Occlusion-continuity scenarios with known ground truth, for vehicles,
// two-wheelers and pedestrians (state-estimation plan Sections 16.3 and
// 16.6; the Sprint 0.5.2.2 acceptance list). Each scene is generated by
// continuity_scene_test.go: a sensor at the origin, the road user in a lane
// 12 m out and, where needed, a stationary occluder in a lane 6 m out whose
// shadow is sized to hide the road user for a stated time.
//
// Every scene runs with DefaultOcclusionContinuity, and a correct L6 labels
// each confirmed track, as the pipeline would. The assertions are about
// physics and bookkeeping, never hand-computed positions:
//
//   - support per instant agrees with why the generator produced no cluster,
//     and in particular an occlusion is never claimed where there was none;
//   - each history point carries the support its instant was recorded with;
//   - identity is preserved where the scene says it must be, and otherwise
//     lapses with a recorded reason before any new identity begins, never by
//     handing the road user to another body's track;
//   - a hypothesis never outlives its bound: after departure, turning away
//     unseen or leaving coverage, the track expires within one frame of it;
//   - the truth lies inside the track's 99% position ellipse at the stated
//     coast horizons of 0.5 s and 1 s.
//
// The shipped tracker is run over the same scenes and its identity outcome
// logged beside the option's, so the difference is on record. It is not
// asserted: association work in flight elsewhere may legitimately move it.

// roadUser is one class's body and motion.
type roadUser struct {
	class                 string // the L6 label
	motion                MotionClass
	length, width, height float64
	speed                 float64 // cruising speed, m/s
	points                float64 // returns wholly visible at 10 m
	hideSecs              float64 // full-occlusion time the occluder is sized for
	decel                 float64 // hidden-stop deceleration, m/s²
	stopSpeed             float64 // speed approaching a hidden stop
}

const (
	laneY     = 12.0 // the road user's lane
	occluderY = 6.0  // the occluder's lane
	leadSecs  = 2.5  // wholly visible travel before the occluder
)

var (
	carBody        = roadUser{class: "car", motion: MotionRigidVehicle, length: 4.5, width: 1.8, height: 1.5, speed: 10, points: 150, hideSecs: 1.0, decel: 3, stopSpeed: 6}
	cyclistBody    = roadUser{class: "cyclist", motion: MotionTwoWheeler, length: 1.8, width: 0.6, height: 1.7, speed: 5, points: 50, hideSecs: 1.5, decel: 2.5, stopSpeed: 5}
	pedestrianBody = roadUser{class: "pedestrian", motion: MotionPedestrian, length: 0.6, width: 0.5, height: 1.7, speed: 1.4, points: 30, hideSecs: 2.0, decel: 2, stopSpeed: 1.4}
	roadUsers      = []roadUser{carBody, cyclistBody, pedestrianBody}
)

// distractorFor is a body of a different class whose extent the
// reacquisition guard can tell apart from the road user's.
func distractorFor(u roadUser) roadUser {
	switch u.class {
	case carBody.class:
		return pedestrianBody
	case cyclistBody.class:
		return carBody
	default:
		return cyclistBody
	}
}

// occluderLength sizes a stationary occluder at occluderY so that a body of
// length l at speed v in laneY is wholly hidden for about hide seconds: the
// shadow at laneY is laneY/occluderY = 2 times the occluder's length.
func occluderLength(u roadUser, v, hide float64) float64 {
	return (v*hide + u.length) / 2
}

func (u roadUser) body(name string, path func(float64) bodyPose) *sceneBody {
	return &sceneBody{name: name, label: u.class, length: u.length, width: u.width, height: u.height, points: u.points, path: path}
}

func occluderBody(length float64) *sceneBody {
	return &sceneBody{name: "van", label: "truck", length: length, width: 2, height: 2.5, points: 400, path: stationary(0, occluderY, 0)}
}

// startX puts a body leadSecs of travel before the leading edge of the
// shadow of an occluder of the given length.
func startX(u roadUser, v, occluder float64) float64 {
	return -occluder - u.length/2 - leadSecs*v
}

// hiddenAt is when a body at speed v, starting at x0, is first wholly inside
// the shadow of an occluder of the given length.
func hiddenAt(u roadUser, v, x0, occ float64) float64 {
	return (-occ + u.length/2 - x0) / v
}

func sceneOf(seed int64, bodies ...*sceneBody) *scene {
	return &scene{bodies: bodies, rng: rand.New(rand.NewSource(seed))}
}

// identityRule is what a scenario requires of the road user's identity.
type identityRule int

const (
	// identityPreserved: one track follows the road user throughout.
	identityPreserved identityRule = iota
	// identityLapses: the first track expires, with its reason, and the road
	// user is seen again only under a new identity.
	identityLapses
	// identityPhysics: the outcome depends on how far the hidden manoeuvre
	// takes the road user from the prediction; either is acceptable, but it
	// must be one or the other cleanly.
	identityPhysics
)

// scenarioCase builds one scene for one road user.
type scenarioCase struct {
	name     string
	identity identityRule
	// coverage asserts the 99% ellipse at the stated horizons: scenes in
	// which the road user is still where CV physics can follow it then.
	coverage bool
	build    func(u roadUser) (sc *scene, distractor string, duration float64)
}

// Coast horizons at which the truth must lie inside the 99% ellipse.
var coverageHorizonsSecs = []float32{0.5, 1.0}

var scenarioCases = []scenarioCase{
	{"full_occlusion", identityPreserved, true, func(u roadUser) (*scene, string, float64) {
		occ := occluderLength(u, u.speed, u.hideSecs)
		x0 := startX(u, u.speed, occ)
		return sceneOf(1, occluderBody(occ), u.body("target", kinematicPath(x0, laneY, 0, u.speed, nil))),
			"", (2*occ+u.length-x0)/u.speed + 2.5
	}},
	{"hidden_stop", identityPhysics, true, func(u roadUser) (*scene, string, float64) {
		// Brakes to a stop once wholly hidden, waits a second, drives on.
		v := u.stopSpeed
		occ := occluderLength(u, u.speed, u.hideSecs)
		x0 := startX(u, v, occ)
		brake := hiddenAt(u, v, x0, occ)
		stopFor := 1.0
		path := kinematicPath(x0, laneY, 0, v, []segment{
			{duration: brake}, {duration: v / u.decel, accel: -u.decel}, {duration: stopFor},
			{duration: v / u.decel, accel: u.decel},
		})
		return sceneOf(2, occluderBody(occ), u.body("target", path)), "", brake + 2*v/u.decel + stopFor + (2*occ+u.length)/v + 2
	}},
	{"turn_during_occlusion", identityPhysics, true, func(u roadUser) (*scene, string, float64) {
		// Once wholly hidden, turns 60 degrees away from the sensor over one
		// second and carries on, deeper into the shadow; a pedestrian stops,
		// turns 90 degrees in place and walks on.
		occ := occluderLength(u, u.speed, u.hideSecs)
		x0 := startX(u, u.speed, occ)
		turn := hiddenAt(u, u.speed, x0, occ)
		segs := []segment{{duration: turn}, {duration: 1, yawRate: math.Pi / 3}}
		if u.motion == MotionPedestrian {
			segs = []segment{{duration: turn}, {duration: 0.35, accel: -4}, {duration: 1, yawRate: math.Pi / 2}, {duration: 0.35, accel: 4}}
		}
		return sceneOf(3, occluderBody(occ), u.body("target", kinematicPath(x0, laneY, 0, u.speed, segs))), "", turn + 6
	}},
	{"sparse_returns", identityPreserved, false, func(u roadUser) (*scene, string, float64) {
		// No occluder: returns held near the cluster minimum at every range,
		// so sparseness is not confounded with range fall-off, and a quarter
		// of frames lost below it.
		b := u.body("target", kinematicPath(-u.speed*4, laneY, 0, u.speed, nil))
		b.points, b.fixedPoints = 7, true
		b.dropout = 0.25
		return sceneOf(4, b), "", 8
	}},
	{"re_entry", identityLapses, false, func(u roadUser) (*scene, string, float64) {
		// Leaves the sensor's 20 m coverage, turns back, and re-enters about
		// four seconds later.
		out := 2.0 + 16.0/u.speed
		path := kinematicPath(0, laneY, 0, u.speed, []segment{{duration: out}, {duration: 0.5, yawRate: 2 * math.Pi}})
		sc := sceneOf(5, u.body("target", path))
		sc.maxRange = 20
		return sc, "", 2 * out
	}},
	{"distractor", identityPreserved, true, func(u roadUser) (*scene, string, float64) {
		// While the road user is hidden, a body of another class appears
		// beside the lane just outside the shadow's far edge, near where the
		// road user's prediction will be when it re-emerges. The shadow edge
		// is cast by the occluder's near face, one metre nearer than its
		// centre line.
		occ := occluderLength(u, u.speed, u.hideSecs)
		x0 := startX(u, u.speed, occ)
		hide := hiddenAt(u, u.speed, x0, occ)
		d := distractorFor(u)
		appear := hide + 0.4*u.hideSecs
		dy := laneY + u.width/2 + d.width/2 + 0.3
		dx := occ/2*dy/(occluderY-1) + d.length/2 + 0.2
		distractor := d.body("distractor", presentBetween(stationary(dx, dy, 0), appear, math.Inf(1)))
		return sceneOf(6, occluderBody(occ), u.body("target", kinematicPath(x0, laneY, 0, u.speed, nil)), distractor),
			"distractor", (2*occ+u.length-x0)/u.speed + 2.5
	}},
	{"departure", identityPreserved, false, func(u roadUser) (*scene, string, float64) {
		// Seen for three seconds, then gone with nothing in front of it: into
		// a driveway, or simply no longer there.
		return sceneOf(7, u.body("target", presentBetween(kinematicPath(-u.speed*1.5, laneY, 0, u.speed, nil), 0, 3))), "", 7
	}},
}

// scenarioConfig is the tracker a scene runs with: the given base, and the
// scene's coverage when it has one.
func scenarioConfig(base TrackerConfig, sc *scene) TrackerConfig {
	if sc.maxRange > 0 {
		base.OcclusionContinuity.Coverage.MaxRangeMetres = float32(sc.maxRange)
	}
	return base
}

func optionConfig() TrackerConfig {
	cfg := DefaultTrackerConfig()
	cfg.OcclusionContinuity = DefaultOcclusionContinuity()
	return cfg
}

// scenarioProblems runs a scenario's checks and returns every problem found.
func scenarioProblems(c scenarioCase, u roadUser, r sceneRun) []string {
	problems := append(r.checkSupportAgreesWithTruth(), r.checkHistoryCarriesSupport()...)
	problems = append(problems, r.checkIdentity(c.identity)...)
	problems = append(problems, r.checkNoFalsePersistence()...)
	if c.coverage {
		problems = append(problems, r.checkCoverage()...)
	}
	switch c.name {
	case "sparse_returns":
		problems = append(problems, r.checkSparseReturns()...)
	case "re_entry":
		problems = append(problems, r.checkFirstExpiry(ExpiryOutOfFOV)...)
	case "departure":
		problems = append(problems, r.checkFirstExpiry(ExpiryMissedUnknown)...)
	case "full_occlusion", "distractor":
		problems = append(problems, r.checkReacquiredAfterOcclusion(u)...)
	}
	return problems
}

func scenarioCaseNamed(t *testing.T, name string) scenarioCase {
	t.Helper()
	for _, c := range scenarioCases {
		if c.name == name {
			return c
		}
	}
	t.Fatalf("no scenario %q", name)
	return scenarioCase{}
}

func TestOcclusionContinuityScenarios(t *testing.T) {
	for _, c := range scenarioCases {
		for _, u := range roadUsers {
			c, u := c, u
			t.Run(c.name+"/"+u.class, func(t *testing.T) {
				sc, distractor, duration := c.build(u)
				r := runScene(t, scenarioConfig(optionConfig(), sc), sc, "target", distractor, duration, true)

				shippedScene, _, _ := c.build(u)
				shipped := runScene(t, DefaultTrackerConfig(), shippedScene, "target", distractor, duration, true)
				t.Logf("identities: option %d, shipped %d; mixed with another body: option %v, shipped %v",
					len(r.identities), len(shipped.identities), r.mixedWithOthers(), shipped.mixedWithOthers())
				r.logErrorByCoastAge(t)

				if problems := scenarioProblems(c, u, r); len(problems) > 0 {
					r.logSamples(t)
					for _, p := range problems {
						t.Error(p)
					}
				}
			})
		}
	}
}

// The checks must be able to fail. The shipped tracker loses the cyclist's
// identity to its miss budget behind an occluder and never explains the
// absence; with explanation off the option cannot recognise the occlusion;
// and the shipped tracker hands the re-emerging car to the pedestrian
// distractor's track. Each must be caught.
func TestOcclusionScenarioChecksCanFail(t *testing.T) {
	full := scenarioCaseNamed(t, "full_occlusion")
	cases := []struct {
		name string
		cfg  TrackerConfig
		c    scenarioCase
		u    roadUser
		want []string
	}{
		{"shipped tracker", DefaultTrackerConfig(), full, cyclistBody,
			[]string{"identity not preserved", "occlusion recognised on 0 of"}},
		{"explanation off", continuityConfig(func(c *OcclusionContinuityConfig) {
			*c = DefaultOcclusionContinuity()
			c.ExplainAbsence, c.ClassCoastBounds = false, false
		}), full, pedestrianBody, []string{"occlusion recognised on 0 of"}},
		{"shipped distractor", DefaultTrackerConfig(), scenarioCaseNamed(t, "distractor"), carBody,
			[]string{"went to a track that also took another body's"}},
	}
	for _, tc := range cases {
		sc, distractor, duration := tc.c.build(tc.u)
		r := runScene(t, scenarioConfig(tc.cfg, sc), sc, "target", distractor, duration, true)
		problems := strings.Join(scenarioProblems(tc.c, tc.u, r), "\n")
		for _, w := range tc.want {
			if !strings.Contains(problems, w) {
				t.Errorf("%s: the checks did not report %q; they reported:\n%s", tc.name, w, problems)
			}
		}
	}
}

// Without a class the tracker falls back to unknown's allowances, which are
// shorter: an unclassified pedestrian behind the same occluder is let go at
// two seconds and seen again under a new identity, where a classified one is
// held for its class's four.
func TestUnclassifiedRoadUsersGetTheUnknownAllowance(t *testing.T) {
	c := scenarioCaseNamed(t, "full_occlusion")
	sc, _, duration := c.build(pedestrianBody)
	r := runScene(t, optionConfig(), sc, "target", "", duration, false)
	first := r.tracks[r.identities[0]]
	unknown := DefaultOcclusionContinuity().Policies[MotionUnknown]
	if first.ExpiryReason != ExpiryOccludedInferred || first.CoastAgeSecs < unknown.ExplainedSecs ||
		first.CoastAgeSecs > unknown.ExplainedSecs+sceneFramePeriod+1e-3 {
		r.logSamples(t)
		t.Fatalf("unclassified pedestrian: reason %s at %.2f s, want occluded_inferred at unknown's %.1f s",
			first.ExpiryReason, first.CoastAgeSecs, unknown.ExplainedSecs)
	}
	if len(r.identities) != 2 {
		t.Fatalf("%d identities; the pedestrian should re-emerge under a new one", len(r.identities))
	}
	if problems := append(r.checkSupportAgreesWithTruth(), r.checkNoFalsePersistence()...); len(problems) > 0 {
		t.Fatal(strings.Join(problems, "\n"))
	}

	dep := scenarioCaseNamed(t, "departure")
	sc, _, duration = dep.build(carBody)
	r = runScene(t, optionConfig(), sc, "target", "", duration, false)
	first = r.tracks[r.identities[0]]
	if first.ExpiryReason != ExpiryMissedUnknown || first.CoastAgeSecs > unknown.UnexplainedSecs+sceneFramePeriod+1e-3 {
		t.Fatalf("unclassified departure: reason %s at %.2f s, want missed_unknown by %.1f s",
			first.ExpiryReason, first.CoastAgeSecs, unknown.UnexplainedSecs)
	}
}

// mixedWithOthers reports whether the road user's clusters ever went to a
// track that also took another body's.
func (r sceneRun) mixedWithOthers() bool {
	for _, id := range r.identities {
		if r.othersTo[id] {
			return true
		}
	}
	return false
}

// coasting reports whether a sample's following track was live and
// unobserved: the instants at which support is a claim about an absence.
func (s targetSample) coasting() bool {
	return s.trackID != "" && s.state != TrackDeleted && s.support.isAbsence()
}

// checkSupportAgreesWithTruth compares each unobserved instant's support
// with the generator's reason for producing no cluster. An occlusion must
// never be claimed where there was none: a false claim buys a longer
// allowance for a hypothesis nothing supports. A real occlusion must be
// recognised on most instants; the first instant or two at the shadow's
// edge may not yet be half covered.
func (r sceneRun) checkSupportAgreesWithTruth() (problems []string) {
	var hidden, recognised int
	for _, s := range r.samples {
		if s.trackID != "" && s.state != TrackDeleted && s.exist != existenceFor(s.support) {
			problems = append(problems, fmt.Sprintf("t=%.1f: existence %s does not follow support %s", s.t, s.exist, s.support))
		}
		if !s.coasting() {
			continue
		}
		switch s.why {
		case whySparse, whyAbsent, whyOutOfRange:
			if s.support == SupportOccludedInferred {
				problems = append(problems, fmt.Sprintf("t=%.1f: occlusion claimed while the road user was %s", s.t, s.why))
			}
		case whyOccluded:
			hidden++
			if s.support == SupportOccludedInferred {
				recognised++
			}
			if s.support == SupportOutOfFOV {
				problems = append(problems, fmt.Sprintf("t=%.1f: an occluded road user inside coverage read as out_of_fov", s.t))
			}
		}
		if s.why == whyOutOfRange && s.support != SupportOutOfFOV && s.support != SupportMissedUnknown {
			problems = append(problems, fmt.Sprintf("t=%.1f: a road user out of coverage read as %s", s.t, s.support))
		}
	}
	if hidden > 0 && float64(recognised) < 0.8*float64(hidden) {
		problems = append(problems, fmt.Sprintf("occlusion recognised on %d of %d hidden instants, want at least 80%%", recognised, hidden))
	}
	return problems
}

// checkHistoryCarriesSupport checks every history point of every track that
// followed the road user against the support recorded at that instant.
func (r sceneRun) checkHistoryCarriesSupport() (problems []string) {
	for _, id := range r.identities {
		at := map[int64]ObservationSupport{}
		for _, s := range r.samples {
			if s.trackID == id {
				at[tdAt(1+s.t).UnixNano()] = s.support
			}
		}
		for _, p := range r.tracks[id].History {
			want, seen := at[p.Timestamp]
			if !seen {
				continue // before the road user's cluster first reached this track
			}
			if p.Support != want {
				problems = append(problems, fmt.Sprintf("track %s history at %d: support %s, recorded %s", id, p.Timestamp, p.Support, want))
			}
		}
	}
	return problems
}

// checkIdentity applies the scenario's identity rule, and in every case
// forbids handing the road user to another body's track.
func (r sceneRun) checkIdentity(rule identityRule) (problems []string) {
	if len(r.identities) == 0 {
		return []string{"the road user was never tracked"}
	}
	if r.mixedWithOthers() {
		problems = append(problems, "the road user's clusters went to a track that also took another body's")
	}
	switch rule {
	case identityPreserved:
		if len(r.identities) != 1 {
			problems = append(problems, fmt.Sprintf("identity not preserved: %d tracks followed the road user", len(r.identities)))
		}
	case identityLapses:
		if len(r.identities) < 2 {
			problems = append(problems, fmt.Sprintf("identity did not lapse: %d track followed the road user", len(r.identities)))
		}
	}
	// Wherever identity changed, the earlier track had expired, with its
	// reason, before the later one first took the road user: a lapse, not a
	// swap.
	for i := 1; i < len(r.identities); i++ {
		prev := r.tracks[r.identities[i-1]]
		if prev.TrackState != TrackDeleted || prev.ExpiryReason == ExpiryNone {
			problems = append(problems, fmt.Sprintf("identity %d began while identity %d was still live (%s)", i+1, i, prev.TrackState))
			continue
		}
		for _, s := range r.samples {
			if s.trackID == r.identities[i] && tdAt(1+s.t).UnixNano() < prev.EndUnixNanos {
				problems = append(problems, fmt.Sprintf("identity %d took the road user at t=%.1f, before identity %d expired", i+1, s.t, i))
				break
			}
		}
	}
	return problems
}

// checkNoFalsePersistence: predicted existence is a hypothesis, and at no
// instant may one be live beyond the allowance that instant's support and
// its class give it. The allowance changes with the explanation, so a track
// explained for two seconds whose occluder no longer covers it has already
// outlived the unexplained allowance, and must expire on that instant. Every
// expired track must also name the absence that ended it.
func (r sceneRun) checkNoFalsePersistence() (problems []string) {
	for _, s := range r.samples {
		if !s.coasting() {
			continue
		}
		probe := *r.tracks[s.trackID]
		probe.TrackState = s.state
		if bound, _ := r.tk.classCoastBound(&probe, s.support); s.coast >= bound+1e-3 {
			problems = append(problems, fmt.Sprintf("t=%.1f: a %s hypothesis live at %.2f s against its %.2f s allowance", s.t, s.support, s.coast, bound))
		}
	}
	for _, id := range r.identities {
		track := r.tracks[id]
		if track.TrackState == TrackDeleted && track.ExpiryReason != expiryReasonFor(track.LastSupport) {
			problems = append(problems, fmt.Sprintf("track %s expired as %s after a %s instant", id, track.ExpiryReason, track.LastSupport))
		}
	}
	return problems
}

// checkCoverage asserts the truth inside the 99% ellipse at each stated coast
// horizon the first identity reached while coasting.
func (r sceneRun) checkCoverage() (problems []string) {
	for _, h := range coverageHorizonsSecs {
		for _, s := range r.samples {
			if s.trackID != r.identities[0] || !s.coasting() || s.coast < h-1e-3 {
				continue
			}
			if s.d2 > chi2TwoDOF99 {
				problems = append(problems, fmt.Sprintf("at a %.1f s coast the truth is outside the 99%% ellipse: d²=%.2f, error %.2f m", h, s.d2, s.err))
			}
			break
		}
	}
	return problems
}

// checkSparseReturns: returns lost at the cluster minimum are unexplained
// misses, and brief ones do not end the hypothesis.
func (r sceneRun) checkSparseReturns() (problems []string) {
	missed := 0
	for _, s := range r.samples {
		if s.coasting() && s.support == SupportMissedUnknown {
			missed++
		}
	}
	if missed == 0 {
		problems = append(problems, "the scene lost no returns below the cluster minimum; it does not exercise sparse returns")
	}
	if track := r.tracks[r.identities[0]]; track.TrackState == TrackDeleted {
		problems = append(problems, fmt.Sprintf("brief sparse misses expired the track (%s)", track.ExpiryReason))
	}
	return problems
}

// checkFirstExpiry: the first identity ended for the stated reason.
func (r sceneRun) checkFirstExpiry(want ExpiryReason) (problems []string) {
	if track := r.tracks[r.identities[0]]; track.TrackState != TrackDeleted || track.ExpiryReason != want {
		problems = append(problems, fmt.Sprintf("first identity: %s, reason %q; want expired as %s", track.TrackState, track.ExpiryReason, want))
	}
	return problems
}

// checkReacquiredAfterOcclusion: the preserved identity closed an unobserved
// interval at least as long as the occluder was sized to hide the road user.
func (r sceneRun) checkReacquiredAfterOcclusion(u roadUser) (problems []string) {
	if track := r.tracks[r.identities[0]]; track.MaxCoastAgeSecs < float32(u.hideSecs)-sceneFramePeriod {
		problems = append(problems, fmt.Sprintf("longest closed coast %.2f s, want at least the %.1f s the occluder hides", track.MaxCoastAgeSecs, u.hideSecs))
	}
	return problems
}

// logErrorByCoastAge records prediction error and ellipse distance against
// coast age for the first identity, and the first horizon at which the truth
// left the 99% ellipse, if it did.
func (r sceneRun) logErrorByCoastAge(t *testing.T) {
	t.Helper()
	var line string
	escaped := float32(-1)
	for _, s := range r.samples {
		if s.trackID != r.identities[0] || !s.coasting() {
			continue
		}
		if int(math.Round(float64(s.coast)*10))%5 == 0 {
			line += " " + formatCoast(s)
		}
		if escaped < 0 && s.d2 > chi2TwoDOF99 {
			escaped = s.coast
		}
	}
	if line == "" {
		return
	}
	if escaped >= 0 {
		t.Logf("error by coast age:%s; left the 99%% ellipse at %.1f s", line, escaped)
		return
	}
	t.Logf("error by coast age:%s; inside the 99%% ellipse throughout", line)
}

func formatCoast(s targetSample) string {
	return "[" + trimFloat(float64(s.coast)) + "s " + trimFloat(s.err) + "m d²" + trimFloat(s.d2) + "]"
}

func trimFloat(v float64) string {
	return strconv.FormatFloat(math.Round(v*100)/100, 'f', -1, 64)
}
