//
//  PackFolderAccess.swift
//  VelocityVisualiser
//
//  Remembers which folders the operator has let this app read and write, so
//  a pack the server has just generated can be opened without asking again.
//
//  The app is sandboxed. It may touch a file only if the operator chose it in
//  an open panel, or chose a folder above it. A pack generated by the server
//  is neither: its path arrives in an HTTP response, and the sandbox has no
//  idea the operator wanted it. Opening it fails with "Operation not
//  permitted" even though the file is there and readable from a shell.
//
//  Saving has the same shape and a worse failure. SidecarStore writes
//  annotations.json, a lock file and a revisions directory inside the pack,
//  so a read-only grant opens the pack and then loses the first save.
//
//  The remedy the sandbox offers is a security-scoped bookmark: ask for the
//  packs folder once, keep the bookmark, and resolve it on later launches.
//  Several folders can be remembered, because packs will not always live
//  under one root.
//

import Foundation

/// Turns a folder grant into bytes and back, and brackets its use.
///
/// A seam rather than direct calls because creating a security-scoped
/// bookmark needs both the sandbox entitlement and a real operator grant,
/// neither of which a unit test has. Tests substitute plain paths and
/// exercise everything around the bookmark instead.
protocol FolderBookmarking {
    func makeBookmark(for folder: URL) throws -> Data
    func resolve(_ bookmark: Data) throws -> (url: URL, isStale: Bool)
    /// Returns false when access could not be started.
    func startAccess(_ url: URL) -> Bool
    func stopAccess(_ url: URL)
}

/// Where the bookmarks are kept between launches.
protocol FolderBookmarkStorage {
    func load() -> [Data]
    func save(_ bookmarks: [Data])
}

struct SecurityScopedBookmarking: FolderBookmarking {
    func makeBookmark(for folder: URL) throws -> Data {
        try folder.bookmarkData(
            options: .withSecurityScope, includingResourceValuesForKeys: nil, relativeTo: nil)
    }

    func resolve(_ bookmark: Data) throws -> (url: URL, isStale: Bool) {
        var stale = false
        let url = try URL(
            resolvingBookmarkData: bookmark, options: .withSecurityScope, relativeTo: nil,
            bookmarkDataIsStale: &stale)
        return (url, stale)
    }

    func startAccess(_ url: URL) -> Bool { url.startAccessingSecurityScopedResource() }
    func stopAccess(_ url: URL) { url.stopAccessingSecurityScopedResource() }
}

struct UserDefaultsBookmarkStorage: FolderBookmarkStorage {
    static let key = "annotation.packFolderBookmarks"
    let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) { self.defaults = defaults }

    func load() -> [Data] { defaults.array(forKey: Self.key) as? [Data] ?? [] }
    func save(_ bookmarks: [Data]) { defaults.set(bookmarks, forKey: Self.key) }
}

/// An open grant on a remembered folder. Access ends when `end()` is called.
///
/// Deliberately not ended in `deinit`: the session that uses the grant
/// outlives any one reference to it, and an access that stopped whenever a
/// copy happened to be released would fail saves at unpredictable moments.
final class PackFolderGrant {
    let folder: URL
    private let bookmarking: FolderBookmarking
    private var isOpen = true

    fileprivate init(folder: URL, bookmarking: FolderBookmarking) {
        self.folder = folder
        self.bookmarking = bookmarking
    }

    func end() {
        guard isOpen else { return }
        isOpen = false
        bookmarking.stopAccess(folder)
    }
}

final class PackFolderAccess {
    private let bookmarking: FolderBookmarking
    private let storage: FolderBookmarkStorage

    init(
        bookmarking: FolderBookmarking = SecurityScopedBookmarking(),
        storage: FolderBookmarkStorage = UserDefaultsBookmarkStorage()
    ) {
        self.bookmarking = bookmarking
        self.storage = storage
    }

    /// Starts access to the remembered folder containing `pack`, if there is
    /// one. Returns nil when no remembered folder covers it, which is the
    /// caller's cue to ask the operator.
    ///
    /// Bookmarks that no longer resolve are dropped as they are found: the
    /// folder was deleted or the volume is gone, and keeping the bookmark
    /// would only fail the same way on every later launch. A stale bookmark
    /// that still resolves is refreshed in place.
    func beginAccess(for pack: URL) -> PackFolderGrant? {
        var kept: [Data] = []
        var grant: PackFolderGrant?
        var changed = false

        for bookmark in storage.load() {
            guard let resolved = try? bookmarking.resolve(bookmark) else {
                changed = true
                continue
            }
            var current = bookmark
            if resolved.isStale, let fresh = try? bookmarking.makeBookmark(for: resolved.url) {
                current = fresh
                changed = true
            }
            kept.append(current)

            if grant == nil, Self.folder(resolved.url, contains: pack),
                bookmarking.startAccess(resolved.url)
            {
                grant = PackFolderGrant(folder: resolved.url, bookmarking: bookmarking)
            }
        }

        if changed { storage.save(kept) }
        return grant
    }

    /// Remembers `folder` for later launches. Remembering a folder that is
    /// already covered by one on the list is a no-op rather than a duplicate.
    func remember(_ folder: URL) throws {
        let existing = storage.load()
        for bookmark in existing {
            if let resolved = try? bookmarking.resolve(bookmark),
                Self.folder(resolved.url, contains: folder)
            {
                return
            }
        }
        storage.save(existing + [try bookmarking.makeBookmark(for: folder)])
    }

    /// True when `candidate` is `folder` itself or lies beneath it.
    ///
    /// Compared by path component after resolving symlinks on both sides, not
    /// by string prefix: "/data/packs-old/x" begins with "/data/packs" and is
    /// not inside it. Symlinks are resolved because the server reports the
    /// canonical path (on macOS a temporary directory under /var arrives as
    /// /private/var) while the operator may have granted the uncanonical one.
    static func folder(_ folder: URL, contains candidate: URL) -> Bool {
        let root = folder.resolvingSymlinksInPath().standardizedFileURL.pathComponents
        let path = candidate.resolvingSymlinksInPath().standardizedFileURL.pathComponents
        guard path.count >= root.count else { return false }
        return Array(path.prefix(root.count)) == root
    }
}
