// BuildInfo.swift
// Auto-generated by make build-mac. Do not edit manually.

enum BuildInfo {
    static let gitSHA = "55a1d962ef3336791c89a597e6ae7f356f4646d3"
    static let buildTime = "2026-03-20T14:58:59Z"
}
