// BuildInfo.swift
// Auto-generated by make test-mac. Do not edit manually.

enum BuildInfo {
    static let gitSHA = "591a40b7a377a28f2bbd57370e31d48e0cdd765c"
    static let buildTime = "2026-03-02T06:46:31Z"
}
