// BuildInfo.swift
// Auto-generated by make build-mac. Do not edit manually.

enum BuildInfo {
    static let gitSHA = "88d44509274cef3711ec15f09d2bd694addc333f"
    static let buildTime = "2026-03-13T19:22:56Z"
}
