#!/usr/bin/env bash
# check-buildinfo-placeholder.sh — keep generated build stamps out of git
#
# tools/visualiser-macos/VelocityVisualiser/App/BuildInfo.swift is regenerated by
# make build-mac, test-mac, and test-mac-cov, which stamp it with the current git
# SHA and a wall-clock timestamp. The file is tracked so the Xcode target always
# has something to compile, so .gitignore cannot keep the generated values out —
# an already-tracked file ignores it.
#
# Left unenforced, every macOS build dirties the tree and the stamp rides along
# in unrelated commits, producing pointless diffs and conflicts.
#
# Every string value in the file must therefore read "unknown" in git.
#
# Usage:
#   scripts/check-buildinfo-placeholder.sh          check, exit 1 on violation
#   scripts/check-buildinfo-placeholder.sh --fix    rewrite the placeholder
#
# Exit 0 if clean, 1 if the file carries generated values.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_INFO="tools/visualiser-macos/VelocityVisualiser/App/BuildInfo.swift"
TARGET="$REPO_ROOT/$BUILD_INFO"

PLACEHOLDER='// BuildInfo.swift
// Auto-generated at build time (make build-mac / test-mac). Do not edit manually.
//
// Committed as a placeholder only. Real values are stamped in by the build and
// must never be checked in — see scripts/check-buildinfo-placeholder.sh.

enum BuildInfo {
    static let gitSHA = "unknown"
    static let buildTime = "unknown"
}'

if [ "${1:-}" = "--fix" ]; then
    printf '%s\n' "$PLACEHOLDER" > "$TARGET"
    echo "Reset $BUILD_INFO to its placeholder"
    exit 0
fi

if [ ! -f "$TARGET" ]; then
    echo "ERROR: $BUILD_INFO is missing."
    echo "The macOS target needs it to compile. Restore it with:"
    echo "    make fix-buildinfo"
    exit 1
fi

# Any string literal that is not "unknown" is a stamped-in build value.
stamped="$(grep -nE 'static let [A-Za-z]+ *= *"' "$TARGET" | grep -v '"unknown"' || true)"

if [ -n "$stamped" ]; then
    echo "ERROR: $BUILD_INFO carries generated build values."
    echo ""
    echo "This file is regenerated by every macOS build. Only the placeholder"
    echo "belongs in git, so each value must read \"unknown\":"
    echo ""
    printf '%s\n' "$stamped" | sed 's/^/    /'
    echo ""
    echo "Reset it with:"
    echo "    make fix-buildinfo"
    echo ""
    echo "then stage the result. The macOS build will stamp it again locally;"
    echo "just do not commit that."
    exit 1
fi

echo "OK — $BUILD_INFO holds only placeholder values"
