// velocity.report LiDAR Visualiser Protocol
// Version: v1
// Package: velocity.visualiser.v1
//
// This protobuf schema defines the API contract between the Go LiDAR pipeline
// and the macOS visualiser application. It supports:
// - Live streaming of point clouds, clusters, and tracks
// - Playback control for recorded logs
// - Debug overlays for algorithm tuning
// - Labelling workflow for classifier training

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: visualiser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisualiserService_StreamFrames_FullMethodName    = "/velocity.visualiser.v1.VisualiserService/StreamFrames"
	VisualiserService_Pause_FullMethodName           = "/velocity.visualiser.v1.VisualiserService/Pause"
	VisualiserService_Play_FullMethodName            = "/velocity.visualiser.v1.VisualiserService/Play"
	VisualiserService_Seek_FullMethodName            = "/velocity.visualiser.v1.VisualiserService/Seek"
	VisualiserService_SetRate_FullMethodName         = "/velocity.visualiser.v1.VisualiserService/SetRate"
	VisualiserService_SetOverlayModes_FullMethodName = "/velocity.visualiser.v1.VisualiserService/SetOverlayModes"
	VisualiserService_GetCapabilities_FullMethodName = "/velocity.visualiser.v1.VisualiserService/GetCapabilities"
	VisualiserService_StartRecording_FullMethodName  = "/velocity.visualiser.v1.VisualiserService/StartRecording"
	VisualiserService_StopRecording_FullMethodName   = "/velocity.visualiser.v1.VisualiserService/StopRecording"
)

// VisualiserServiceClient is the client API for VisualiserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisualiserServiceClient interface {
	// Live streaming of frame bundles (server-streaming)
	StreamFrames(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FrameBundle], error)
	// Control RPCs for playback (replay mode)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PlaybackStatus, error)
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlaybackStatus, error)
	Seek(ctx context.Context, in *SeekRequest, opts ...grpc.CallOption) (*PlaybackStatus, error)
	SetRate(ctx context.Context, in *SetRateRequest, opts ...grpc.CallOption) (*PlaybackStatus, error)
	// Request specific overlay modes
	SetOverlayModes(ctx context.Context, in *OverlayModeRequest, opts ...grpc.CallOption) (*OverlayModeResponse, error)
	// Server capabilities query
	GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Recording control (live mode)
	StartRecording(ctx context.Context, in *RecordingRequest, opts ...grpc.CallOption) (*RecordingStatus, error)
	StopRecording(ctx context.Context, in *RecordingRequest, opts ...grpc.CallOption) (*RecordingStatus, error)
}

type visualiserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisualiserServiceClient(cc grpc.ClientConnInterface) VisualiserServiceClient {
	return &visualiserServiceClient{cc}
}

func (c *visualiserServiceClient) StreamFrames(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FrameBundle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VisualiserService_ServiceDesc.Streams[0], VisualiserService_StreamFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, FrameBundle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VisualiserService_StreamFramesClient = grpc.ServerStreamingClient[FrameBundle]

func (c *visualiserServiceClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PlaybackStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackStatus)
	err := c.cc.Invoke(ctx, VisualiserService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlaybackStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackStatus)
	err := c.cc.Invoke(ctx, VisualiserService_Play_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) Seek(ctx context.Context, in *SeekRequest, opts ...grpc.CallOption) (*PlaybackStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackStatus)
	err := c.cc.Invoke(ctx, VisualiserService_Seek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) SetRate(ctx context.Context, in *SetRateRequest, opts ...grpc.CallOption) (*PlaybackStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackStatus)
	err := c.cc.Invoke(ctx, VisualiserService_SetRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) SetOverlayModes(ctx context.Context, in *OverlayModeRequest, opts ...grpc.CallOption) (*OverlayModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverlayModeResponse)
	err := c.cc.Invoke(ctx, VisualiserService_SetOverlayModes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, VisualiserService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) StartRecording(ctx context.Context, in *RecordingRequest, opts ...grpc.CallOption) (*RecordingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordingStatus)
	err := c.cc.Invoke(ctx, VisualiserService_StartRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) StopRecording(ctx context.Context, in *RecordingRequest, opts ...grpc.CallOption) (*RecordingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordingStatus)
	err := c.cc.Invoke(ctx, VisualiserService_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisualiserServiceServer is the server API for VisualiserService service.
// All implementations must embed UnimplementedVisualiserServiceServer
// for forward compatibility.
type VisualiserServiceServer interface {
	// Live streaming of frame bundles (server-streaming)
	StreamFrames(*StreamRequest, grpc.ServerStreamingServer[FrameBundle]) error
	// Control RPCs for playback (replay mode)
	Pause(context.Context, *PauseRequest) (*PlaybackStatus, error)
	Play(context.Context, *PlayRequest) (*PlaybackStatus, error)
	Seek(context.Context, *SeekRequest) (*PlaybackStatus, error)
	SetRate(context.Context, *SetRateRequest) (*PlaybackStatus, error)
	// Request specific overlay modes
	SetOverlayModes(context.Context, *OverlayModeRequest) (*OverlayModeResponse, error)
	// Server capabilities query
	GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// Recording control (live mode)
	StartRecording(context.Context, *RecordingRequest) (*RecordingStatus, error)
	StopRecording(context.Context, *RecordingRequest) (*RecordingStatus, error)
	mustEmbedUnimplementedVisualiserServiceServer()
}

// UnimplementedVisualiserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisualiserServiceServer struct{}

func (UnimplementedVisualiserServiceServer) StreamFrames(*StreamRequest, grpc.ServerStreamingServer[FrameBundle]) error {
	return status.Error(codes.Unimplemented, "method StreamFrames not implemented")
}
func (UnimplementedVisualiserServiceServer) Pause(context.Context, *PauseRequest) (*PlaybackStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedVisualiserServiceServer) Play(context.Context, *PlayRequest) (*PlaybackStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedVisualiserServiceServer) Seek(context.Context, *SeekRequest) (*PlaybackStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Seek not implemented")
}
func (UnimplementedVisualiserServiceServer) SetRate(context.Context, *SetRateRequest) (*PlaybackStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRate not implemented")
}
func (UnimplementedVisualiserServiceServer) SetOverlayModes(context.Context, *OverlayModeRequest) (*OverlayModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOverlayModes not implemented")
}
func (UnimplementedVisualiserServiceServer) GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedVisualiserServiceServer) StartRecording(context.Context, *RecordingRequest) (*RecordingStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedVisualiserServiceServer) StopRecording(context.Context, *RecordingRequest) (*RecordingStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedVisualiserServiceServer) mustEmbedUnimplementedVisualiserServiceServer() {}
func (UnimplementedVisualiserServiceServer) testEmbeddedByValue()                           {}

// UnsafeVisualiserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisualiserServiceServer will
// result in compilation errors.
type UnsafeVisualiserServiceServer interface {
	mustEmbedUnimplementedVisualiserServiceServer()
}

func RegisterVisualiserServiceServer(s grpc.ServiceRegistrar, srv VisualiserServiceServer) {
	// If the following call panics, it indicates UnimplementedVisualiserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisualiserService_ServiceDesc, srv)
}

func _VisualiserService_StreamFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VisualiserServiceServer).StreamFrames(m, &grpc.GenericServerStream[StreamRequest, FrameBundle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VisualiserService_StreamFramesServer = grpc.ServerStreamingServer[FrameBundle]

func _VisualiserService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_Play_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).Play(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_Seek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).Seek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_Seek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).Seek(ctx, req.(*SeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_SetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).SetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_SetRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).SetRate(ctx, req.(*SetRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_SetOverlayModes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverlayModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).SetOverlayModes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_SetOverlayModes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).SetOverlayModes(ctx, req.(*OverlayModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).GetCapabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_StartRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).StartRecording(ctx, req.(*RecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).StopRecording(ctx, req.(*RecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisualiserService_ServiceDesc is the grpc.ServiceDesc for VisualiserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisualiserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.visualiser.v1.VisualiserService",
	HandlerType: (*VisualiserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pause",
			Handler:    _VisualiserService_Pause_Handler,
		},
		{
			MethodName: "Play",
			Handler:    _VisualiserService_Play_Handler,
		},
		{
			MethodName: "Seek",
			Handler:    _VisualiserService_Seek_Handler,
		},
		{
			MethodName: "SetRate",
			Handler:    _VisualiserService_SetRate_Handler,
		},
		{
			MethodName: "SetOverlayModes",
			Handler:    _VisualiserService_SetOverlayModes_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _VisualiserService_GetCapabilities_Handler,
		},
		{
			MethodName: "StartRecording",
			Handler:    _VisualiserService_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _VisualiserService_StopRecording_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrames",
			Handler:       _VisualiserService_StreamFrames_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "visualiser.proto",
}
